src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>Instance__c</fullName>
        <description>Indicates the instance of the repeat section</description>
        <label>Instance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QA-{00000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>MaxInstance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MaxInstance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProcessAnswerRecordsBatchTest.cls
/**
 * This test class is used to cover ProcessAnswerRecordsBatch class
 *
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 */
@isTest
private class ProcessAnswerRecordsBatchTest {

    static testMethod void testProcessAnswerRecords() {
        // The query used by the batch job.
        String parentAnswersQuery = 
            'SELECT ' +
                'Instance__c, ' +
                'Question__r.Id, ' +
                'Question__r.MaxInstance__c ' +
            'FROM ' +
                'Answer__c ';

        // Create answer records test data which will need testing
        List<Answer__c> listAnswer = AnswersTriggerTest.createAfterUpdatePreConditions(2, 3);
        insert listAnswer;
        Test.startTest();
        ProcessAnswerRecordsBatch processAnswerRecordsBatchInstance =
            new ProcessAnswerRecordsBatch(parentAnswersQuery);
        Database.executeBatch(processAnswerRecordsBatchInstance);
        Test.stopTest();

        // Verify batch worked properly
        if (listAnswer != null && !listAnswer.isEmpty()) {
            System.assertEquals(
                3, 
                [
                    SELECT
                        Question__r.MaxInstance__c
                    FROM
                        Answer__c
                    WHERE
                        Id = :listAnswer[0].Id
                ].Question__r.MaxInstance__c);
        }
    }
}