src/objects/AssignedTarget__c.object
<CustomObject>
    <description>Holds the target and actual values for a specific (Target, Contact) pair</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact for which this assigned target applies</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assigned Targets</relationshipLabel>
        <relationshipName>AssignedTargets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The date when this Assigned Target stops tracking values and a new one is created for the next timeframe.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PerformanceTarget__c</fullName>
        <description>The target to which this object belongs to</description>
        <label>Performance Target</label>
        <referenceTo>PerformanceTarget__c</referenceTo>
        <relationshipLabel>Assigned Targets</relationshipLabel>
        <relationshipName>Assigned_Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The date when the Assigned Target starts tracking the values</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Active means in use, closed means old</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TargetValue__c</fullName>
        <description>The target value for the Contact in the Target&apos;s time frame</description>
        <label>Target Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Assigned Target</label>
    <nameField>
        <displayFormat>AT-{0000000}</displayFormat>
        <label>Assigned Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mobile_User__c</fullName>
        <formula>IF( IsMobileUser__c &gt; 0
,
IMAGE(&apos;/img/checkbox_checked.gif&apos;, &apos;Checked&apos;)
,
IMAGE(&apos;/img/checkbox_unchecked.gif&apos;, &apos;Not Checked&apos;)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile User Count</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/JobTemplate__c.object
<CustomObject>
    <description>Job</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Defines if the Job can be downloaded to the phone. Closed jobs will be removed from mobile phones, but submissions of completed jobs are still possible.</description>
        <inlineHelpText>If Job is published its content cannot be edited. Only admits to change to Closed.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    -</CustomObject>

src/objects/Mobile_User__c.object
<CustomObject>
    <description>Contains information about a Field Officer&apos;s session in Salesforce</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Id of the Field Officer</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Mobile Users</relationshipLabel>
        <relationshipName>Mobile_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Mobile User</label>
    <nameField>
        <displayFormat>MU-{0000}</displayFormat>
        <label>Mobile User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PerformanceTarget__c.object
<CustomObject>
    <description>Contains the definition for a performance target</description>
    <fields>
        <fullName>DefaultValue__c</fullName>
        <description>Numeric value that holds the default value to apply to a Mobile User&apos;s target</description>
        <label>Default Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The date when the current time period finishes and a new set of Assigned Targets should be created for the following one.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>JobTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For Job Targets, it has a link to the corresponding Job. For Performance Indicators, it is NULL.</description>
        <label>Job</label>
        <referenceTo>JobTemplate__c</referenceTo>
        <relationshipLabel>Performance Target</relationshipLabel>
        <relationshipName>Performance_Target</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The date when the current period started for this target.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Active means in use, closed means not in use</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Performance Target</label>
    <nameField>
        <label>Performance Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performance Target</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MobileUserTriggerTest.cls
/**
 * Test class for the trigger for Mobile_User__c
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 *
 * @author Alejandro De Gregorio Tort - adegregorio@altimetrik.com
 */
@isTest
public with sharing class MobileUserTriggerTest {

    private static PerformanceTarget__c currentPerformanceTarget;

    /**
     * Test assigned target creation for job target when an active user is inserted
     */
    static testMethod void testTargetCreationForJobTargetOnActiveUserInsert() {
        // Given a job target
        createAJobTarget();

        Test.startTest();
        // When an active mobile user is inserted
        TestUtils.Surveyor activeSurveyor =
            TestUtils.createSurveyorWithStatus(MobileUserDO.STATUS_ACTIVE);
        Test.stopTest();

        // Then an assigned target is created
        checkAssignedTargetIsCreated(activeSurveyor);
    }

    /**
     * Test assigned target creation for indicator target when an active user is inserted
     */
    static testMethod void testTargetCreationForIndicatorTargetOnActiveUserInsert() {
        // Given an indicator target
        createPerformanceIndicatorTarget();

        Test.startTest();
        // When an active mobile user is inserted
        TestUtils.Surveyor activeSurveyor =
            TestUtils.createSurveyorWithStatus(MobileUserDO.STATUS_ACTIVE);
        Test.stopTest();

        // Then an assigned target is created
        checkAssignedTargetIsCreated(activeSurveyor);
    }

    /**
     * Test assigned target not created for a job target when an inactive user is inserted
     */
    static testMethod void testTargetNotCreatedForJobTargetOnInactiveUserInsert() {
        // Given a job target
        createAJobTarget();

        Test.startTest();
        // When an inactive mobile used is inserted
        TestUtils.createSurveyorWithStatus(MobileUserDO.STATUS_INACTIVE);
        Test.stopTest();

        // Then no assigned target is created
        System.assertEquals(0, [
            SELECT Id
            FROM AssignedTarget__c
            WHERE PerformanceTarget__c = :currentPerformanceTarget.Id
        ].size());
    }

    /**
     * Test assigned target not created for an indicator target when an inactive user is inserted
     */
    static testMethod void testTargetNotCreatedForIndicatorTargetOnInactiveUserInsert() {
        // Given an indicator target
        createPerformanceIndicatorTarget();

        Test.startTest();
        // When an inactive mobile used is inserted
        TestUtils.createSurveyorWithStatus(MobileUserDO.STATUS_INACTIVE);
        Test.stopTest();

        // Then no assigned target is created
        System.assertEquals(0, [
            SELECT Id
            FROM AssignedTarget__c
            WHERE PerformanceTarget__c = :currentPerformanceTarget.Id
        ].size());
    }

    /**
     * Test assigned target creation for job target when an inactive user becomes active
     */
    static testMethod void testTargetCreationForJobTargetOnUserActivate() {
        // Given a job target and an inactive mobile user
        createAJobTarget();
        TestUtils.Surveyor inactiveSurveyor =
            TestUtils.createSurveyorWithStatus(MobileUserDO.STATUS_INACTIVE);

        Test.startTest();
        // When the mobile user is activated
        TestUtils.Surveyor activatedSurveyor = TestUtils.changeSurveyorStatus(
            inactiveSurveyor,
            MobileUserDO.STATUS_ACTIVE
        );
        Test.stopTest();

        // Then an assigned target is created
        checkAssignedTargetIsCreated(activatedSurveyor);
    }

    /**
     * Test assigned target creation for indicator target when an inactive user becomes active
     */
    static testMethod void testTargetCreationForIndicatorTargetOnUserActivate() {
        // Given an indicator target and an inactive mobile user
        createPerformanceIndicatorTarget();
        TestUtils.Surveyor inactiveSurveyor =
            TestUtils.createSurveyorWithStatus(MobileUserDO.STATUS_INACTIVE);

        Test.startTest();
        // When the mobile user is activated
        TestUtils.Surveyor activatedSurveyor = TestUtils.changeSurveyorStatus(
            inactiveSurveyor,
            MobileUserDO.STATUS_ACTIVE
        );
        Test.stopTest();

        // Then an assigned target is created
        checkAssignedTargetIsCreated(activatedSurveyor);
    }

    /**
     * Test reopen an assigned target for a job target when an inactive user becomes active
     */
    static testMethod void testReopenTargetForJobTargetOnUserActivate() {
        // Given a job target and an inactive mobile user with a closed assigned target
        createAJobTarget();
        TestUtils.Surveyor inactiveSurveyor =
            TestUtils.createSurveyorWithStatus(MobileUserDO.STATUS_INACTIVE);
        AssignedTarget__c closedTarget = createClosedAssignedTargetFor(inactiveSurveyor);

        Test.startTest();
        // When the mobile used is activated
        TestUtils.Surveyor activatedSurveyor = TestUtils.changeSurveyorStatus(
            inactiveSurveyor,
            MobileUserDO.STATUS_ACTIVE
        );
        Test.stopTest();

        // Then the same assigned target is reopened
        checkAssignedTargetIsReopened(closedTarget);
    }

    /**
     * Test reopen an assigned target for an indicator target when an inactive user becomes active
     */
    static testMethod void testReopenTargetForIndicatorTargetOnUserActivate() {
        // Given an indicator target and an inactive mobile user with a closed assigned target
        createPerformanceIndicatorTarget();
        TestUtils.Surveyor inactiveSurveyor =
            TestUtils.createSurveyorWithStatus(MobileUserDO.STATUS_INACTIVE);
        AssignedTarget__c closedTarget = createClosedAssignedTargetFor(inactiveSurveyor);

        Test.startTest();
        // When the mobile used is activated
        TestUtils.Surveyor activatedSurveyor = TestUtils.changeSurveyorStatus(
            inactiveSurveyor,
            MobileUserDO.STATUS_ACTIVE
        );
        Test.stopTest();

        // Then the same assigned target is reopened
        checkAssignedTargetIsReopened(closedTarget);
    }

    /**
     * Test close assigned target of job target when user is deleted
     */
    static testMethod void testCloseTargetOfJobTargetOnDelete() {
        // Given a job target and an active mobile user
        createAJobTarget();
        TestUtils.Surveyor activeSurveyor =
            TestUtils.createSurveyorWithStatus(MobileUserDO.STATUS_ACTIVE);

        Test.startTest();
        // When the mobile user is deleted
        delete activeSurveyor.user;
        Test.stopTest();

        // Then the assigned target for this user is closed
        System.assertEquals(
            AssignedTargetDO.STATUS_CLOSED,
            [SELECT Status__c
             FROM AssignedTarget__c
             WHERE Contact__c = :activeSurveyor.theContact.Id].Status__c
        );
    }

    /**
     * Test close assigned target of indicator target when user is deleted
     */
    static testMethod void testCloseTargetOfIndicatorTargetOnDelete() {
        // Given an indicator target and an active mobile user
        createPerformanceIndicatorTarget();
        TestUtils.Surveyor activeSurveyor =
            TestUtils.createSurveyorWithStatus(MobileUserDO.STATUS_ACTIVE);

        Test.startTest();
        // When the mobile user is deleted
        delete activeSurveyor.user;
        Test.stopTest();

        // Then the assigned target for this user is closed
        System.assertEquals(
            AssignedTargetDO.STATUS_CLOSED,
            [SELECT Status__c
             FROM AssignedTarget__c
             WHERE Contact__c = :activeSurveyor.theContact.Id].Status__c
        );
    }

    /**
     * Test close assigned target of job target when user becomes inactive
     */
    static testMethod void testCloseTargetOfJobTargetOnDeactivate() {
        // Given a job target and an active mobile user
        createAJobTarget();
        TestUtils.Surveyor activeSurveyor =
            TestUtils.createSurveyorWithStatus(MobileUserDO.STATUS_ACTIVE);

        Test.startTest();
        // When the mobile user is deactivated
        TestUtils.Surveyor deactivatedSurveyor = TestUtils.changeSurveyorStatus(
            activeSurveyor,
            MobileUserDO.STATUS_INACTIVE
        );
        Test.stopTest();

        // Then the assigned target for this user is closed
        System.assertEquals(
            AssignedTargetDO.STATUS_CLOSED,
            [SELECT Status__c
             FROM AssignedTarget__c
             WHERE Contact__c = :activeSurveyor.theContact.Id].Status__c
        );
    }

    /**
     * Test close assigned target of indicator target when user becomes inactive
     */
    static testMethod void testCloseTargetOfIndicatorTargetOnDeactivate() {
        // Given a indicator target and an active mobile user
        createAJobTarget();
        TestUtils.Surveyor activeSurveyor =
            TestUtils.createSurveyorWithStatus(MobileUserDO.STATUS_ACTIVE);

        Test.startTest();
        // When the mobile user is deactivated
        TestUtils.Surveyor deactivatedSurveyor = TestUtils.changeSurveyorStatus(
            activeSurveyor,
            MobileUserDO.STATUS_INACTIVE
        );
        Test.stopTest();

        // Then the assigned target for this user is closed
        System.assertEquals(
            AssignedTargetDO.STATUS_CLOSED,
            [SELECT Status__c
             FROM AssignedTarget__c
             WHERE Contact__c = :activeSurveyor.theContact.Id].Status__c
        );
    }

    /**
     * Test the creation of assigned targets with the job filter on
     */
    static testMethod void testAssignedTargetCreationWithJobFilter() {
        // Create two users
        Profile sysAdmin = TestUtils.getSysAdminProfile();
        User user1 = TestUtils.createUser(sysAdmin.Id);
        User user2 = TestUtils.createUser(sysAdmin.Id);

        // Create two contacts
        Contact contact1 = new Contact(LastName = 'contact1');
        Contact contact2 = new Contact(LastName = 'contact2');
        insert new List<Contact> {contact1, contact2};

        // Create two job templates
        JobTemplate__c job1 = TestUtils.createPublishedDataCollectionJobTemplate('job1', 'Survey 1');
        JobTemplate__c job2 = TestUtils.createPublishedDataCollectionJobTemplate('job2', 'Survey 2');

        // Change the ownership
        contact1.OwnerId = user1.Id;
        contact2.OwnerId = user2.Id;
        update new List<Contact> {contact1, contact2};

        job1.OwnerId = user1.Id;
        job2.OwnerId = user2.Id;
        update new List<JobTemplate__c> {job1, job2};

        // Set the job filter on
        ApplicationSettingsUtils.setJobFilterSetting(
            ApplicationSettingsUtils.JOBS_FILTER_SF_USER
        );

        // Create two performance targets
        PerformanceTarget__c performanceTarget1 = PerformanceTargetDOTest.createJobTargetRecord(
            'PerformanceTarget1',
            job1.Id,
            50,
            PerformanceTargetDO.TIMEFRAME_WEEKLY,
            PerformanceTargetDO.getPreviousMonday(Date.today()),
            PerformanceTargetDO.getPreviousMonday(Date.today()).addDays(6),
            PerformanceTargetDO.TYPE_JOB_TARGET
        );
        PerformanceTarget__c performanceTarget2 = PerformanceTargetDOTest.createJobTargetRecord(
            'PerformanceTarget2',
            job2.Id,
            50,
            PerformanceTargetDO.TIMEFRAME_WEEKLY,
            PerformanceTargetDO.getPreviousMonday(Date.today()),
            PerformanceTargetDO.getPreviousMonday(Date.today()).addDays(6),
            PerformanceTargetDO.TYPE_JOB_TARGET
        );
        insert new List<PerformanceTarget__c> {
            performanceTarget1,
            performanceTarget2
        };
        performanceTarget1.OwnerId = user1.Id;
        performanceTarget2.OwnerId = user2.Id;
        update new List<PerformanceTarget__c> {
            performanceTarget1,
            performanceTarget2
        };

        // Insert two mobile users
        Mobile_User__c mUser1 = new Mobile_User__c(
            Username__c = 'user1',
            Password__c = 'pass1',
            Contact__c = contact1.Id,
            Status__c = MobileUserDO.STATUS_ACTIVE
        );
        Mobile_User__c mUser2 = new Mobile_User__c(
            Username__c = 'user2',
            Password__c = 'pass2',
            Contact__c = contact2.Id,
            Status__c = MobileUserDO.STATUS_ACTIVE
        );

        Test.startTest();
        System.runAs(user1) {
            insert mUser1;
        }
        System.runAs(user2) {
            insert mUser2;
        }
        Test.stopTest();

        // Check the first mobile user has an assigned target for the first job
        List<AssignedTarget__c> targets = new List<AssignedTarget__c> ([
            SELECT Id,
                   PerformanceTarget__r.JobTemplate__c
            FROM AssignedTarget__c
            WHERE Contact__c = :contact1.Id
        ]);
        System.assertEquals(1, targets.size());
        System.assertEquals(
            job1.Id,
            targets[0].PerformanceTarget__r.JobTemplate__c
        );

        // Check the second mobile user has an assigned target for the second job
        targets = new List<AssignedTarget__c> ([
            SELECT Id,
                   PerformanceTarget__r.JobTemplate__c
            FROM AssignedTarget__c
            WHERE Contact__c = :contact2.Id
        ]);
        System.assertEquals(1, targets.size());
        System.assertEquals(
            job2.Id,
            targets[0].PerformanceTarget__r.JobTemplate__c
        );
    }

    /**
     * Create a job target for the preconditions
     */
    private static void createAJobTarget() {
        PerformanceManagementTest.EndToEndTestWrapper endToEndTestWrapper =
                new PerformanceManagementTest.EndToEndTestWrapper();
        endToEndTestWrapper.initJobPerformanceTargetWrappers(
            PerformanceTargetDO.TIMEFRAME_WEEKLY,
            1,
            ''
        );
        currentPerformanceTarget = endToEndTestWrapper
                .getPerformanceTargetWrapperByCreationIndex(0).getPerformanceTarget();
    }

    /**
     * Check the creation o assigned targets for the given user
     *
     * @param activeSurveyor - The user to verify
     */
    private static void checkAssignedTargetIsCreated(TestUtils.Surveyor activeSurveyor) {
        List<AssignedTarget__c> assignedTargets = new List<AssignedTarget__c>([
            SELECT Id,
                   TargetValue__c,
                   StartDate__c,
                   EndDate__c,
                   Status__c,
                   Contact__c
            FROM AssignedTarget__c
            WHERE PerformanceTarget__c = :currentPerformanceTarget.Id
        ]);

        // Check an assigned target was created for the active user
        System.assertEquals(1, assignedTargets.size());
        System.assertEquals(activeSurveyor.theContact.Id, assignedTargets[0].Contact__c);

        // Check the assigned target has the default value and the right dates
        System.assertEquals(
            currentPerformanceTarget.DefaultValue__c,
            assignedTargets[0].TargetValue__c
        );
        System.assertEquals(
            currentPerformanceTarget.StartDate__c,
            assignedTargets[0].StartDate__c
        );
        System.assertEquals(currentPerformanceTarget.EndDate__c, assignedTargets[0].EndDate__c);
        System.assertEquals(AssignedTargetDO.STATUS_ACTIVE, assignedTargets[0].Status__c);
    }

    /**
     * Set preconditions for indicator target tests
     */
    private static void createPerformanceIndicatorTarget() {
        PerformanceManagementTest.EndToEndTestWrapper endToEndTestWrapper =
                new PerformanceManagementTest.EndToEndTestWrapper();
        endToEndTestWrapper.initPerfomanceIndicatorPerformanceTargetWrappers(
            PerformanceTargetDO.TIMEFRAME_WEEKLY,
            1,
            '',
            null,
            null,
            null,
            null,
            null,
            null
        );
        currentPerformanceTarget = endToEndTestWrapper
                .getPerformanceTargetWrapperByCreationIndex(0).getPerformanceTarget();
    }

    /**
     * Check the assigned target was reopened
     *
     * @param oldTarget - The old assigned target
     */
    private static void checkAssignedTargetIsReopened(AssignedTarget__c oldTarget) {
        List<AssignedTarget__c> assignedTargets = new List<AssignedTarget__c>([
            SELECT Id,
                   TargetValue__c,
                   StartDate__c,
                   EndDate__c,
                   Status__c
            FROM AssignedTarget__c
            WHERE PerformanceTarget__c = :currentPerformanceTarget.Id
        ]);

        // Check the assigned target was activated
        System.assertEquals(1, assignedTargets.size());
        System.assertEquals(oldTarget.Id, assignedTargets[0].Id);
        System.assertEquals(AssignedTargetDO.STATUS_ACTIVE, assignedTargets[0].Status__c);

        // Check the assigned target has the same value and dates
        System.assertEquals(oldTarget.TargetValue__c, assignedTargets[0].TargetValue__c);
        System.assertEquals(oldTarget.StartDate__c, assignedTargets[0].StartDate__c);
        System.assertEquals(oldTarget.EndDate__c, assignedTargets[0].EndDate__c);
    }

    /**
     * Create a closed assigned target for the given surveyor
     *
     * @param surveyor - The surveyor to create the assigned target for
     *
     * @return - The created assigned target
     */
    private static AssignedTarget__c createClosedAssignedTargetFor(TestUtils.Surveyor surveyor) {
        AssignedTarget__c closedTarget = AssignedTargetDO.createAssignedTarget(
            currentPerformanceTarget,
            surveyor.theContact.Id,
            0,
            Integer.valueOf(currentPerformanceTarget.DefaultValue__c),
            currentPerformanceTarget.StartDate__c,
            currentPerformanceTarget.EndDate__c,
            AssignedTargetDO.STATUS_CLOSED
        );
        insert closedTarget;

        return closedTarget;
    }
}