src/objects/AssignedTarget__c.object
<CustomObject>
    <description>Holds the target and actual values for a specific (Target, Contact) pair</description>
    <fields>
        <fullName>ActualValue__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The actual value that the Contact achieved so far</description>
        <label>Actual Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact for which this assigned target applies</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assigned Targets</relationshipLabel>
        <relationshipName>AssignedTargets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The date when this Assigned Target stops tracking values and a new one is created for the next timeframe.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PerformanceTarget__c</fullName>
        <description>The target to which this object belongs to</description>
        <label>Performance Target</label>
        <referenceTo>PerformanceTarget__c</referenceTo>
        <relationshipLabel>Assigned Targets</relationshipLabel>
        <relationshipName>Assigned_Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The date when the Assigned Target starts tracking the values</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Assigned Target</label>
    <nameField>
        <displayFormat>AT-{0000000}</displayFormat>
        <label>Assigned Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Assigned__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field Officer that completed the job activity.</description>
        <label>Staff</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Activities</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact for whom the job activity was completed (would be Interviewee for a survey).</description>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs of Client</relationshipLabel>
        <relationshipName>JobAsInterviewee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date and time when the job activity was completed.</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>JobTemplate__c</fullName>
        <description>Job for this Job Activity</description>
        <label>Job</label>
        <referenceTo>JobTemplate__c</referenceTo>
        <relationshipLabel>Job Activities</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date and time when the job activity was started.</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Job Activity</label>
    <nameField>
        <label>Job Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JobTemplate__c.object
<CustomObject>
    <description>Job</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    -</CustomObject>

src/objects/PerformanceTarget__c.object
<CustomObject>
    <description>Contains the definition for a performance target</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The date when the current time period finishes and a new set of Assigned Targets should be created for the following one.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>JobTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For Job Targets, it has a link to the corresponding Job. For Performance Indicators, it is NULL.</description>
        <label>Job</label>
        <referenceTo>JobTemplate__c</referenceTo>
        <relationshipLabel>Performance Target</relationshipLabel>
        <relationshipName>Performance_Target</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The date when the current period started for this target.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Timeframe__c</fullName>
        <description>The length of the lifetime of the target</description>
        <label>Timeframe</label>
        <picklist>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Performance Target</label>
    <nameField>
        <label>Performance Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performance Target</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/JobTargetCleanUpBatchTest.cls
/**
 * Test class for JobTargetCleanUpBatch
 *
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 *
 * @author - Owen Davies
 */
@isTest
public class JobTargetCleanUpBatchTest {

    /**
     * Test that the Assigned Targets are updated correctly.
     * One Mobile User has an AssignedTarget already. The other doesn't
     */
    static testMethod void testBatchUpdate() {

        // Create a contacts
        TestUtils.Surveyor testMobileUser1 = TestUtils.createSurveyor(
            'TESTJTCUBT1', 'username1', 'passsword1', MobileUserDO.STATUS_ACTIVE, false
        );
        TestUtils.Surveyor testMobileUser2 = TestUtils.createSurveyor(
            'TESTJTCUBT2', 'username2', 'passsword2', MobileUserDO.STATUS_ACTIVE, false
        );

        // Create a PerformanceTargetWrapper
        PerformanceManagementTest.EndToEndTestWrapper endToEndTestWrapper = new PerformanceManagementTest.EndToEndTestWrapper();
        endToEndTestWrapper.initJobPerformanceTargetWrappers(PerformanceTargetDO.TIMEFRAME_WEEKLY, 1, 'WEEKLY');
        endToEndTestWrapper.initJobPerformanceTargetWrappers(PerformanceTargetDO.TIMEFRAME_MONTHLY, 1, 'MONTHLY');

        // Create some JobActivities for the JobTemplate
        PerformanceManagementTest.PerformanceTargetWrapper performanceTargetWrapper1 =
            endToEndTestWrapper.getPerformanceTargetWrapperByCreationIndex(0);
        PerformanceManagementTest.JobTemplateWrapper jobTemplateWrapper1 = performanceTargetWrapper1.getJobTemplateWrapper();

        PerformanceManagementTest.PerformanceTargetWrapper performanceTargetWrapper2 =
            endToEndTestWrapper.getPerformanceTargetWrapperByCreationIndex(1);
        PerformanceManagementTest.JobTemplateWrapper jobTemplateWrapper2 = performanceTargetWrapper2.getJobTemplateWrapper();

        DateTime testDate = DateTime.now().addDays(-1);

        insert new List<Job__c>{
            new Job__c(
                Name = 'Job1', JobTemplate__c = jobTemplateWrapper1.jobTemplate.Id,
                Assigned__c = testMobileUser1.theContact.Id, StartDate__c = testDate, EndDate__c = testDate
            ),
            new Job__c(
                Name = 'Job2', JobTemplate__c = jobTemplateWrapper1.jobTemplate.Id,
                Assigned__c = testMobileUser2.theContact.Id, StartDate__c = testDate, EndDate__c = testDate
            ),
            new Job__c(
                Name = 'Job3', JobTemplate__c = jobTemplateWrapper2.jobTemplate.Id,
                Assigned__c = testMobileUser1.theContact.Id, StartDate__c = testDate, EndDate__c = testDate
            ),
            new Job__c(
                Name = 'Job4', JobTemplate__c = jobTemplateWrapper2.jobTemplate.Id,
                Assigned__c = testMobileUser1.theContact.Id, StartDate__c = testDate, EndDate__c = testDate
            )
        };

        // Add an AssingedTarget for mobile user 1 for both targets. Do not add weekly one if it is a Monday
        List<AssignedTarget__c> initialAssignedTargets = new List<AssignedTarget__c>();
        if (
                (
                    performanceTargetWrapper1.getPerformanceTarget().Timeframe__c.equals(
                        PerformanceTargetDO.TIMEFRAME_WEEKLY
                    ) &&
                    !PerformanceTargetDO.isMonday(Date.today())
                ) ||
                (performanceTargetWrapper1.getPerformanceTarget().Timeframe__c.equals(
                    PerformanceTargetDO.TIMEFRAME_MONTHLY
                    ) && Date.today().day() != 1)
        ) {
            initialAssignedTargets.add(AssignedTargetDO.createDefaultActiveAssignedTarget(
                performanceTargetWrapper1.getPerformanceTarget(), testMobileUser1.theContact.Id, 3
            ));
        }
        if (
                (
                    performanceTargetWrapper2.getPerformanceTarget().Timeframe__c.equals(
                        PerformanceTargetDO.TIMEFRAME_WEEKLY
                    ) &&
                    !PerformanceTargetDO.isMonday(Date.today())
                ) ||
                (performanceTargetWrapper2.getPerformanceTarget().Timeframe__c.equals(
                    PerformanceTargetDO.TIMEFRAME_MONTHLY
                ) && Date.today().day() != 1)
        ) {
            initialAssignedTargets.add(AssignedTargetDO.createDefaultActiveAssignedTarget(
                performanceTargetWrapper2.getPerformanceTarget(), testMobileUser1.theContact.Id, 2
            ));
        }
        if (initialAssignedTargets.size() > 0) {
            insert initialAssignedTargets;
        }

        ApplicationSettingsUtils.setReCalculateJobTarget(true, true);

        // Run the batch
        Test.startTest();
        Id batchInstanceId = Database.executeBatch(new JobTargetCleanUpBatch(), 5);
        Test.stopTest();

        // Check that the AssignedTarget have been updated
        AssignedTarget__c[] testTargets = [
            SELECT
                Id,
                ActualValue__c,
                Contact__c,
                PerformanceTarget__c
            FROM
                AssignedTarget__c
        ];
        System.assertEquals(3, testTargets.size());
        for (AssignedTarget__c testTarget : testTargets) {
            if (testTarget.Contact__c == testMobileUser1.theContact.Id) {
                if (testTarget.PerformanceTarget__c == performanceTargetWrapper1.getPerformanceTarget().Id) {

                    //Test Mobile User 1 with JobTarget 1
                    System.assertEquals(1, testTarget.ActualValue__c);
                } else {

                    //Test Mobile User 1 with JobTarget 2
                    System.assertEquals(2, testTarget.ActualValue__c);
                }
            } else {

                //Test Mobile User 2 with JobTarget 1
                System.assertEquals(1, testTarget.ActualValue__c);
            }
        }
    }
}