src/objects/AssignedTarget__c.object
<CustomObject>
    <description>Holds the target and actual values for a specific (Target, Contact) pair</description>
    <fields>
        <fullName>PerformanceTarget__c</fullName>
        <description>The target to which this object belongs to</description>
        <label>Performance Target</label>
        <referenceTo>PerformanceTarget__c</referenceTo>
        <relationshipLabel>Assigned Targets</relationshipLabel>
        <relationshipName>Assigned_Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Assigned Target</label>
    <nameField>
        <displayFormat>AT-{0000000}</displayFormat>
        <label>Assigned Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PerformanceTarget__c.object
<CustomObject>
    <description>Contains the definition for a performance target</description>
    <label>Performance Target</label>
    <nameField>
        <label>Performance Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performance Target</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AssignedTargetSelectorTest.cls
/**
 * Test class for the AssignedTargetSelector
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author - Aditi Satpute
 */
@isTest
public with sharing class AssignedTargetSelectorTest {

    /**
     * Test method to verify fetching Assigned Targets for partner users
     */
    static testmethod void testFetchingForPartnerUsers() {
        TestUtils.Surveyor activeSurveyor =
            TestUtils.createPartnerSurveyor('partnerContact', true);

        List<PerformanceTarget__c> performanceTargets =
            PerformanceTargetDOTest.createMultiplePerformanceIndicators(1);

        System.assertEquals(1, performanceTargets.size());

        PerformanceTargetDO performanceTargetDomainInstance =
            new PerformanceTargetDO.Constructor().constructWithRecords(performanceTargets);
        performanceTargetDomainInstance.insertRecords();

        // Create the corresponding assigned target for each user
        List<AssignedTarget__c> assignedTargets =
            AssignedTargetDOTest.createMultipleRecords(
                activeSurveyor.partnerUser.ContactId,
                2,
                performanceTargets[0],
                AssignedTargetDO.STATUS_ACTIVE,
                2
            );

        AssignedTargetDO assignedTargetDomainInstance =
            new AssignedTargetDO.Constructor().constructWithRecords(assignedTargets);
        assignedTargetDomainInstance.insertRecords();

        Test.startTest();
        List<AssignedTarget__c> actualAssignedTargets=
            new AssignedTargetSelector().getForPartnerUsers(
                performanceTargets[0].Id,
                PerformanceTargetDO.getPreviousMonday(Date.today()).addDays(6),
                new Set<Id> {activeSurveyor.partnerUser.ContactId}
            );
        Test.stopTest();

        System.assertEquals(2, actualAssignedTargets.size());
    }
}