src/objects/AssignedTarget__c.object
<CustomObject>
    <description>Holds the target and actual values for a specific (Target, Contact) pair</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact for which this assigned target applies</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assigned Targets</relationshipLabel>
        <relationshipName>AssignedTargets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The date when this Assigned Target stops tracking values and a new one is created for the next timeframe.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PerformanceTarget__c</fullName>
        <description>The target to which this object belongs to</description>
        <label>Performance Target</label>
        <referenceTo>PerformanceTarget__c</referenceTo>
        <relationshipLabel>Assigned Targets</relationshipLabel>
        <relationshipName>Assigned_Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TargetValue__c</fullName>
        <description>The target value for the Contact in the Target&apos;s time frame</description>
        <label>Target Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Assigned Target</label>
    <nameField>
        <displayFormat>AT-{0000000}</displayFormat>
        <label>Assigned Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mobile_User__c</fullName>
        <formula>IF( IsMobileUser__c &gt; 0
,
IMAGE(&apos;/img/checkbox_checked.gif&apos;, &apos;Checked&apos;)
,
IMAGE(&apos;/img/checkbox_unchecked.gif&apos;, &apos;Not Checked&apos;)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile User Count</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Mobile_User__c.object
<CustomObject>
    <description>Contains information about a Field Officer&apos;s session in Salesforce</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Id of the Field Officer</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Mobile Users</relationshipLabel>
        <relationshipName>Mobile_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Mobile User</label>
    <nameField>
        <displayFormat>MU-{0000}</displayFormat>
        <label>Mobile User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PerformanceTarget__c.object
<CustomObject>
    <description>Contains the definition for a performance target</description>
    <fields>
        <fullName>AggregationOperation__c</fullName>
        <description>Operator applied when tracked field is aggregated. Note CUSTOM is not an operator. It indicates that we do nothing with the ActualValue</description>
        <label>Aggregation Operation</label>
        <picklist>
            <picklistValues>
                <fullName>AVG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COUNT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CUSTOM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PERCENTAGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUM</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DefaultValue__c</fullName>
        <description>Numeric value that holds the default value to apply to a Mobile User&apos;s target</description>
        <label>Default Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The date when the current time period finishes and a new set of Assigned Targets should be created for the following one.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Timeframe__c</fullName>
        <description>The length of the lifetime of the target</description>
        <label>Timeframe</label>
        <picklist>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrackedSObjectApiName__c</fullName>
        <description>The API name of the SObject that the performance indicator is for</description>
        <externalId>true</externalId>
        <label>Tracked SObject Api Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrackedSObjectContactLookupFieldName__c</fullName>
        <description>The API name of the field of the tracked SObject where the lookup to the Contact is. It could be a indirect relationship</description>
        <label>Tracked SObject Contact Lookup Field Nam</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of performance target</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Job_Target</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Performance_Indicator</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Performance Target</label>
    <nameField>
        <label>Performance Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Performance Target</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateIndicatorTargetControllerTest.cls
/*
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 *
 * @author - Ernesto Quesada
 * @author - Aditi Satpute
 */
@isTest
public class CreateIndicatorTargetControllerTest {

    /**
     * Test the edition of the name of an indicator target
     */
    static testMethod void editIndicatorTargetName() {
        // Given a saved indicator target
        CreateIndicatorTargetController controller = createPreconditionsForIndicatorTargets(
            'targetName',
            PerformanceTargetDO.TIMEFRAME_WEEKLY,
            50,
            PerformanceTargetDOTest.ASSET_API_NAME,
            PerformanceTargetDOTest.CONTACT_ID_FIELD,
            '',
            true,
            PerformanceTargetDO.AGGREGATION_OPERATION_COUNT
        );

        Test.startTest();
        // When the name is edited and saved
        String newName = 'Some new name';
        controller.performanceTarget.Name = newName;
        controller.save();
        Test.stopTest();

        // Then the name is updated in the record
        System.assertEquals(
            newName,
            [SELECT Name FROM PerformanceTarget__c LIMIT 1][0].Name
        );
    }


    /**
     * Create new performance target with assigned targets with weekly timeframe
     */
    static testMethod void createAWeeklyIndicatorTargetWithDefaultTarget() {

        // Given the controller with an unsaved indicator target
        CreateIndicatorTargetController controller = createPreconditionsForIndicatorTargets(
            'pTarget',
            PerformanceTargetDO.TIMEFRAME_WEEKLY,
            50,
            PerformanceTargetDOTest.ASSET_API_NAME,
            PerformanceTargetDOTest.CONTACT_ID_FIELD,
            '',
            false,
            PerformanceTargetDO.AGGREGATION_OPERATION_COUNT
        );

        Test.startTest();
        // When the save action is ran
        controller.save();
        Test.stopTest();

        // Then the indicator target is saved and an assigned target is created
        checkIndicatorTargetWasSaved(PerformanceTargetDO.TIMEFRAME_WEEKLY);
        checkAnAssignedTargetWasCreated();
    }

    /**
     * Create Performance Indicator with Monthly Target
     */
    static testMethod void createAMonthlyIndicatorTargetWithDefaultTarget() {

        // Given the controller with an unsaved indicator target
        CreateIndicatorTargetController controller = createPreconditionsForIndicatorTargets(
            'pTarget',
            PerformanceTargetDO.TIMEFRAME_MONTHLY,
            50,
            PerformanceTargetDOTest.ASSET_API_NAME,
            PerformanceTargetDOTest.CONTACT_ID_FIELD,
            '',
            false,
            PerformanceTargetDO.AGGREGATION_OPERATION_COUNT
        );

        Test.startTest();
        // When the save action is ran
        controller.save();
        Test.stopTest();

        // Then the indicator target is saved and an assigned target is created
        checkIndicatorTargetWasSaved(PerformanceTargetDO.TIMEFRAME_MONTHLY);
        checkAnAssignedTargetWasCreated();
    }

    /**
     * Update a Indicator default value
     */
    static testMethod void updateIndicatorValues() {
        
        // Create preconditions to save
        CreateIndicatorTargetController controller = createPreconditionsForIndicatorTargets(
            'pTarget',
            PerformanceTargetDO.TIMEFRAME_MONTHLY,
            50,
            PerformanceTargetDOTest.ASSET_API_NAME,
            PerformanceTargetDOTest.CONTACT_ID_FIELD,
            '',
            false,
            PerformanceTargetDO.AGGREGATION_OPERATION_COUNT
        );
        // Save
        controller.save();

        PerformanceTarget__c performanceTarget = 
            [SELECT
                Id,
                EndDate__c,
                DefaultValue__c,
                (SELECT
                    PerformanceTarget__r.DefaultValue__c,
                    TargetValue__c,
                    Contact__c
                FROM
                    Assigned_Targets__r
                WHERE
                    EndDate__c = :controller.performanceTarget.EndDate__c)
            FROM
                PerformanceTarget__c
            WHERE
                Name = 'pTarget'];
        
        
        // Create preconditions to edit
        controller = createPreconditionsForIndicatorsEdition(performanceTarget);

        Test.startTest();
        // Save
        controller.save();
        Test.stopTest();

        // Check Target, and Default value is correctly saved on DB after edition
        system.assertEquals(120, Integer.ValueOf([SELECT
                                                        TargetValue__c
                                                    FROM
                                                        AssignedTarget__c LIMIT 1].TargetValue__c),
                                'Target value must be 120 after edition');

        system.assertEquals(200, Integer.ValueOf([SELECT
                                                        DefaultValue__c
                                                    FROM
                                                        PerformanceTarget__c LIMIT 1].DefaultValue__c),
                                'Default value must be 200 after edition');
    }

    /**
     * Test correct path modification
     */
    static testMethod void assertInvalidPath() {

        // get the fields throug the api in the case it has a namespace
        String parentIdField = Schema.sObjectType.Attachment.Fields.ParentId.getName();
        String contactField = Schema.sObjectType.Mobile_User__c.Fields.Contact__c.getName();
        String reportToId = Schema.sObjectType.Contact.Fields.ReportsToId.getName();

        // build the paths
        String fieldLookup = (parentIdField.replace('Id','') +
                '.' + contactField.replace('__c','__r') + '.' + reportToId);
        CreateIndicatorTargetController controller = createPreconditionsForIndicatorTargets(
            'pTarget',
            PerformanceTargetDO.TIMEFRAME_MONTHLY,
            50,
            Attachment.sObjectType.getDescribe().getName(),
            fieldLookup,
            '',
            false,
            PerformanceTargetDO.AGGREGATION_OPERATION_COUNT
        );

        Test.startTest();
        // Save
        controller.save();
        Test.stopTest();

        List<PerformanceTarget__c> performanceTargets = [
            SELECT
                DefaultValue__c,
                Timeframe__c,
                TrackedSObjectApiName__c,
                TrackedSObjectContactLookupFieldName__c,
                Type__c
            FROM
                PerformanceTarget__c
        ];

        // Check error messages
        System.assert(
            !Apexpages.getMessages().isEmpty(),
            'Should have complained that the path was broken'
        );
        // Check performance
        System.assert(
            performanceTargets.isEmpty(),
            'Must be empty since new Performance target was  not created'
        );
    }

    /**
     * Create a new Performance Indicator with default value for Sum
     */
    static testMethod void createIndicatorDefaultValuesForSum() {
        CreateIndicatorTargetController controller = createPreconditionsForIndicatorTargets(
            'pTarget',
            PerformanceTargetDO.TIMEFRAME_WEEKLY,
            50,
            PerformanceTargetDOTest.LEAD_API_NAME,
            PerformanceTargetDOTest.CONVERTED_CONTACT_ID_FIELD,
            PerformanceTargetDOTest.LEAD_NUMBER_OF_EMPLOYEES,
            false,
            PerformanceTargetDO.AGGREGATION_OPERATION_SUM
        );

        Test.startTest();
        controller.performanceTarget.AggregationOperation__c =
            PerformanceTargetDO.AGGREGATION_OPERATION_SUM;
        controller.getFieldList();
        controller.save();
        Test.stopTest();

        List<PerformanceTarget__c> performanceTargetList =
            new PerformanceTargetSelector().getAllForAggregationOperation(
                PerformanceTargetDOTest.LEAD_NUMBER_OF_EMPLOYEES,
                PerformanceTargetDO.AGGREGATION_OPERATION_SUM
            );

        System.assertEquals(
            1,
            performanceTargetList.size(),
            'Performance Target record for Sum Operation not inserted properly'
        );
    }

    /**
     * Update Performance Indicator with new default value for Sum
     */
    static testMethod void updateIndicatorValuesForSum() {
        CreateIndicatorTargetController controller = createPreconditionsForIndicatorTargets(
            'pTarget',
            PerformanceTargetDO.TIMEFRAME_WEEKLY,
            50,
            PerformanceTargetDOTest.LEAD_API_NAME,
            PerformanceTargetDOTest.CONVERTED_CONTACT_ID_FIELD,
            PerformanceTargetDOTest.LEAD_NUMBER_OF_EMPLOYEES,
            false,
            PerformanceTargetDO.AGGREGATION_OPERATION_SUM
        );
        controller.save();

        // Create preconditions to update Performance Target and Assigned Target
        controller = createPreconditionsForIndicatorsEdition(controller.performanceTarget);

        Test.startTest();
        // Perform update operation for Performance Target and Assignet Target records
        controller.save();
        Test.stopTest();

        PerformanceTarget__c performance =
            new PerformanceTargetSelector().getWithAssignedTargets(
                controller.performanceTarget.Id,
                controller.performanceTarget.EndDate__c
            );

        System.assert(performance != null, 'Performance Target record not found');
        System.assert(
            performance.Assigned_Targets__r.size() > 0,
            'There should be atleast one Assigned target record'
        );

        // Check Target and Default values are correctly saved on DB after performing update
        System.assertEquals(
            120,
            Integer.ValueOf(
                ((AssignedTarget__c) new AssignedTargetSelector().getRecordById(
                    performance.Assigned_Targets__r[0].Id
                )).TargetValue__c
            ),
            'Target value must be 120 after update'
        );

        System.assertEquals(
            200,
            Integer.ValueOf(
                ((PerformanceTarget__c) new PerformanceTargetSelector().getRecordById(
                    performance.Id
                )).DefaultValue__c
            ),
            'Default value must be 200 after update'
        );
    }

    /**
     * Create all preconditions for performance targets test
     *
     * @param targetName                - The performance target name
     * @param timeframe                 - The timeframe for the target
     * @param defaultValue              - The default target value
     * @param objectApiName             - The name of the object related
     * @param trackedContactLookUpField - The field use to track contact look up
     * @param trackedField              - The tracked field used for Sum operation
     * @param areForEdition             - Indicates if the preconditions are for edition
     *
     * @return - Instance of controller
     */
    private static CreateIndicatorTargetController createPreconditionsForIndicatorTargets(
            String targetName,
            String timeframe,
            Integer defaultValue,
            String objectApiName,
            String trackedContactLookUpField,
            String trackedField,
            Boolean areForEdition,
            String aggregationOperation
    ) {

        TestUtils.Surveyor activeSurveyor =
            TestUtils.createPartnerSurveyor('partnerContact', true);

        PerformanceTarget__c indicatorTarget;

        if (areForEdition) {
            PerformanceManagementTest.EndToEndTestWrapper endToEndTestWrapper =
                new PerformanceManagementTest.EndToEndTestWrapper();
            endToEndTestWrapper.initPerfomanceIndicatorPerformanceTargetWrappers(
                timeframe,
                1,
                '',
                null,
                null,
                null,
                null,
                null,
                null
            );
            indicatorTarget = endToEndTestWrapper
                .getPerformanceTargetWrapperByCreationIndex(0).getPerformanceTarget();

            indicatorTarget.Name = targetName;
            indicatorTarget.DefaultValue__c = defaultValue;
            update indicatorTarget;
        } else {
            indicatorTarget = PerformanceTargetDOTest.createPerformanceIndicatorRecord(
                targetName,
                defaultValue,
                timeframe,
                Date.today(),
                Date.today(),
                objectApiName,
                aggregationOperation,
                trackedField,
                trackedContactLookUpField
            );
        }

        ApexPages.StandardController stdController =
            new ApexPages.StandardController(indicatorTarget);
        CreateIndicatorTargetController controller =
            new CreateIndicatorTargetController(stdController);

        // Fill the individual target values
        for (AssignedTargetDO at : controller.assignedTargetWrappers) {
            at.targetValue = 50;
        }

        return controller;
    }

    /**
     * Check the indicator target was saved
     *
     * @param timeframe - The timeframe to check
     */
    private static void checkIndicatorTargetWasSaved(String timeframe) {
        List<PerformanceTarget__c> performanceTargets = [
            SELECT
                DefaultValue__c,
                Timeframe__c,
                TrackedSObjectApiName__c,
                TrackedSObjectContactLookupFieldName__c,
                Type__c
            FROM
                PerformanceTarget__c
        ];

        System.assert(
            !performanceTargets.isEmpty(),
            'Cannot be empty since new Performance target was created'
        );
        System.assertEquals(
            PerformanceTargetDO.TYPE_INDICATOR,
            performanceTargets[0].Type__c
        );
        System.assertEquals(
            timeframe,
            performanceTargets[0].Timeframe__c
        );
        System.assertEquals(50, Integer.ValueOf(performanceTargets[0].DefaultValue__c));
        System.assertEquals(
            PerformanceTargetDOTest.ASSET_API_NAME,
            performanceTargets[0].TrackedSObjectApiName__c
        );
        System.assertEquals(
            PerformanceTargetDOTest.CONTACT_ID_FIELD,
            performanceTargets[0].TrackedSObjectContactLookupFieldName__c
        );
    }

    /**
     * Check an assigned target was created with the given value
     */
    private static void checkAnAssignedTargetWasCreated() {
        List<AssignedTarget__c> assignedTargets = [SELECT TargetValue__c FROM AssignedTarget__c];
        System.assert(
            !assignedTargets.isEmpty(),
            'Cannot be empty since new Assigned target was created'
        );
        System.assertEquals(50, Integer.ValueOf(assignedTargets[0].TargetValue__c));
    }

    /**
     * Preconditions to edit a performance indicator target
     *
     * @param performanceTarget - Performance target to edit
     *
     * @return controller - Instance of controller
     */
    private static CreateIndicatorTargetController 
        createPreconditionsForIndicatorsEdition(PerformanceTarget__c performanceTarget) {

        ApexPages.StandardController stdController = new ApexPages.StandardController(performanceTarget);
        CreateIndicatorTargetController controller = new CreateIndicatorTargetController(stdController);

        // Set new target values for all assigned targets for the current job target
        for(AssignedTargetDO aT : controller.assignedTargetWrappers) {
            aT.targetValue = 120;
        }

        // Set new default value for the current job target
        controller.performanceTarget.DefaultValue__c = 200;

        return controller;
    }
}