src/objects/CascadingLevel__c.object
<CustomObject>
    <description>Represents a Level of a Cascading select question type.</description>
    <fields>
        <fullName>CascadingSelect__c</fullName>
        <description>The Cascading Select this level belongs to.</description>
        <label>Cascading Select</label>
        <referenceTo>CascadingSelect__c</referenceTo>
        <relationshipLabel>Cascading Levels</relationshipLabel>
        <relationshipName>Cascading_Levels</relationshipName>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <description>The Position of the select level</description>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Cascading Level</label>
    <nameField>
    <displayFormat>CL-{00000000}</displayFormat>
        <label>Cascading Level Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cascading Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Position of the option within the option group</description>
        <label>Position</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Parent question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RemoteId__c</fullName>
        <description>The Id of Option as it is in the org that the group was downloaded from</description>
        <externalId>true</externalId>
        <label>Remote Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CascadingLevel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Cascading Level which this Question belongs to.</description>
        <label>Cascading Level</label>
        <referenceTo>CascadingLevel__c</referenceTo>
        <relationshipLabel>Cascading Levels</relationshipLabel>
        <relationshipName>Cascading_Levels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CascadingSelect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Cascading Select that this question represents(only if the question is of cascading type)</description>
        <label>Cascading Select</label>
        <referenceTo>CascadingSelect__c</referenceTo>
        <relationshipLabel>Cascading Select</relationshipLabel>
        <relationshipName>Cascading_Select</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ControllingQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The controlling question of this question(only for cascading questions)</description>
        <label>Controlling Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Controlling Questions</relationshipLabel>
        <relationshipName>ControllingQuestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrentTime__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set date of the day and current time(take from device) as initial value</description>
        <label>Use current date/time as default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DoAfter__c</fullName>
        <label>DoAfter</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DoBefore__c</fullName>
        <label>DoBefore</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FromVersion__c</fullName>
        <label>First Version</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hint__c</fullName>
        <description>A hint for the question</description>
        <label>Supporting text / Instructions</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsDraft__c</fullName>
        <description>Does the question belong to a survey version that can be edited? (1 = True, 0 = False)</description>
        <formula>IF(
    AND(FromVersion__c &lt;= Survey__r.Version__c,
        OR(ToVersion__c = 0,
        ToVersion__c &gt;= Survey__r.Version__c)
    ),1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Can be edited</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsRemoteEditable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Can be edited in downloaded survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MaxInstance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>MaxInstance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum__c</fullName>
        <label>Maximum</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum__c</fullName>
        <label>Minimum</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PpiResultsField__c</fullName>
        <label>PPI Result Field</label>
        <picklist>
            <picklistValues>
                <fullName>ClientId__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gender__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HouseholdSize__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JoinedDate__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geolocation__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerOne__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerTwo__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerThree__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerFour__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerFive__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerSix__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerSeven__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerEight__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerNine__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerTen__c</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PreviousVersionQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous version</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>New version</relationshipLabel>
        <relationshipName>NewVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RemoteId__c</fullName>
        <description>The Id of Question as it is in the org that the survey was downloaded from</description>
        <externalId>true</externalId>
        <label>Remote Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RemoteServerId__c</fullName>
        <description>Deprecated. Use RemoteId__c as it is indexed</description>
        <label>Remote Server Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RepeatSourceValue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Source Question to determine the times a repeated question must be repeated</description>
        <label>Repeat Source Value</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Source Question</relationshipLabel>
        <relationshipName>SourceQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RepeatTimes__c</fullName>
        <description>The number of times that a question must repeat</description>
        <label>Repeat Times</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this question must be answered before moving to the next question</description>
        <inlineHelpText>Check if this question must be answered before moving to the next question</inlineHelpText>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SamePage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>All questions of a section show on same page</description>
        <label>Show all questions on one page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SkipLogicBehavior__c</fullName>
        <label>SkipLogicBehavior</label>
        <picklist>
            <picklistValues>
                <fullName>Show</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hide</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SkipLogicOperator__c</fullName>
        <label>SkipLogicOperator</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Any</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ToVersion__c</fullName>
        <label>Last Version</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>RemoteId__c</fullName>
        <description>The Id of Survey as it is in the org that the survey was downloaded from</description>
        <externalId>true</externalId>
        <label>Remote Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyVersions</relationshipLabel>
        <relationshipName>SurveyVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuestionSelector.cls
/**
 * Selector class for the Question__c object
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author Kaushik Ray
 * @author Owen Davies - odavies@grameenfoundation.org
 */
public with sharing class QuestionSelector extends SObjectSelector {

    public Schema.SObjectType getSObjectType() {
        return Question__c.sObjectType;
    }

    public List<Schema.SObjectField> getDefaultSelectFields() {
        return new List<Schema.SObjectField> {
            Question__c.Id,
            Question__c.Name,
            Question__c.Caption__c,
            Question__c.CascadingLevel__c,
            Question__c.CascadingSelect__c,
            Question__c.ControllingQuestion__c,
            Question__c.CurrentTime__c,
            Question__c.DoAfter__c,
            Question__c.DoBefore__c,
            Question__c.FromVersion__c,
            Question__c.Hint__c,
            Question__c.IsDraft__c,
            Question__c.IsRemoteEditable__c,
            Question__c.MaxInstance__c,
            Question__c.Maximum__c,
            Question__c.Minimum__c,
            Question__c.Parent__c,
            Question__c.Position__c,
            Question__c.RemoteId__c,
            Question__c.PpiResultsField__c,
            Question__c.PreviousVersionQuestion__c,
            Question__c.RemoteServerId__c,
            Question__c.RepeatSourceValue__c,
            Question__c.RepeatTimes__c,
            Question__c.Required__c,
            Question__c.SamePage__c,
            Question__c.SkipLogicBehavior__c,
            Question__c.SkipLogicOperator__c,
            Question__c.Survey__c,
            Question__c.ToVersion__c,
            Question__c.Type__c
        };
    }

    public String pathToJobFiltering() {
        return null;
    }

    /**
     * Return the default order by clause
     */
    public override String getDefaultOrderByClause() {
        StringBuilder.FieldListBuilder fieldListBuilder = new StringBuilder.FieldListBuilder(
            new List<Schema.SObjectField> {
                Question__c.Parent__c,
                Question__c.Position__c
            }
        );
        fieldListBuilder.processFieldList();
        return fieldListBuilder.generateString() + ' ' + SObjectSelector.ASCENDING_OPERATOR;
    }

    /**
     * Get all the questions for a given survey
     * TODO: Convert to use SurveyVersion__c when VERSIONING is done
     */
    public List<Question__c> getAllForSurveyIds(Set<String> surveyIds) {
        this.createSurveyWhereClause(surveyIds);
        return
            (List<Question__c>) runSoqlQuery(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Get all Questions related to specified SurveyIds
     */
    public List<Question__c> getAllForSurveyIds(Set<String> surveyIds, Integer isDraftSurvey) {
        this.createIsDraftWhereClause(isDraftSurvey);
        this.mainQueryBuilder.addRelationshipToSelect(
            new List<Schema.SObjectField> {
                Question__c.Survey__c,
                Survey__c.Status__c
            }
        );
        this.addToMainOrderByClause(
            this.mainQueryBuilder.generateOrderByClause(
                createOrderByClause()
            )
        );
        return getAllForSurveyIds(surveyIds);
    }

    /**
     * Create list of Order by clauses
     */
    private List<SObjectSelector.OrderByBuilder> createOrderByClause() {
        return new List<SObjectSelector.OrderByBuilder> {
            new SObjectSelector.OrderByBuilder(
                Question__c.Position__c,
                SObjectSelector.ASCENDING_OPERATOR
            ),
            new SObjectSelector.OrderByBuilder(
                Question__c.Parent__c,
                SObjectSelector.ASCENDING_OPERATOR
            ),
            new SObjectSelector.OrderByBuilder(
                Question__c.Survey__c,
                SObjectSelector.ASCENDING_OPERATOR
            )
        };
    }

    /**
     * Method to add survey Ids to where clause
     */
    private void createSurveyWhereClause(Set<String> surveyIds) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardInWhereClause(
                Question__c.Survey__c.getDescribe().getName(),
                SObjectSelector.IN_OPERATOR,
                surveyIds
            )
        );
    }

    /**
     * Method to add isDraft to where clause
     */
    private void createIsDraftWhereClause(Integer isDraftSurvey) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                Question__c.IsDraft__c.getDescribe().getName(),
                SObjectSelector.EQUALS_OPERATOR,
                isDraftSurvey
            )
        );
    }

    /**
     * Get all Questions related to a Survey and is PPI and Template
     */
    public List<Question__c> getAllForPpiSurveyId(Id surveyId) {
        this.createSurveyWhereClause(surveyId);
        this.createIsPPIWhereClause(true);
        this.createIsTemplateWhereClause(true);
        this.createIsDraftWhereClause(1);
        this.createNotCascadingSelectWhereClause(QuestionDO.TYPE_CASCADING_LEVEL);
        this.createRemoteIdNullWhereClause();
        this.addToMainOrderByClause(
            this.mainQueryBuilder.generateOrderByClause(
                generateOrderByClause()
            )
        );
        return
            (List<Question__c>) runSoqlQuery(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Get Question records with option records inner query
     * TODO: Convert to use SurveyVersion__c when VERSIONING is done
     */
    public List<Question__c> getWithOptions(Id surveyId, Integer offset) {
        this.mainQueryBuilder.setSelectClauseWithAllFields();
        this.mainQueryBuilder.addRelationshipToSelect(
            new List<List<Schema.SObjectField>> {
                new List<Schema.SObjectField> {
                    Question__c.RepeatSourceValue__c,
                    Question__c.Name
                },
                new List<Schema.SObjectField> {
                    Question__c.CascadingSelect__c,
                    CascadingSelect__c.Name
                }
            }
        );
        this.createSurveyWhereClause(surveyId);
        this.createIsDraftWhereClause(1);
        this.setOffsetAmount(offset);
        this.addToMainOrderByClause(
            this.mainQueryBuilder.generateOrderByClause(
                generateOrderByClause()
            )
        );
        this.addOptionsInnerQuery();
        return (List<Question__c>) runSoqlQuery(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Create list of Order by clauses
     */
    private List<SObjectSelector.OrderByBuilder> generateOrderByClause() {
        return new List<SObjectSelector.OrderByBuilder> {
            new SObjectSelector.OrderByBuilder(
                Question__c.Survey__c,
                SObjectSelector.ASCENDING_OPERATOR
            ),
            new SObjectSelector.OrderByBuilder(
                this.getMainQueryBuilder().generateLookUp(
                    new List<Schema.SObjectField>{
                        Question__c.Parent__c,
                        Question__c.Position__c
                    }
                ),
                SObjectSelector.ASCENDING_OPERATOR
            ),
            new SObjectSelector.OrderByBuilder(
                Question__c.Position__c,
                SObjectSelector.ASCENDING_OPERATOR
            )
        };
    }

    /**
     * Method to add inner query for Option records
     */
    private void addOptionsInnerQuery() {
        this.addInnerSelectQuery(
            new SobjectSelector.SoqlQueryBuilder(
                'Options__r',
                Option__c.sObjectType.getDescribe().getName(),
                new OptionSelector().getDefaultSelectFields(),
                Option__c.Position__c.getDescribe().getName()
            )
        );
    }

    /**
     * Method to add Survey Remote Id where clause
     */
    private void createRemoteIdNullWhereClause() {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                this.getMainQueryBuilder().generateLookUp(
                    new List<Schema.SObjectField>{
                        Question__c.Survey__c,
                        Survey__c.RemoteId__c
                    }
                ),
                SObjectSelector.EQUALS_OPERATOR,
                SObjectSelector.NULL_VALUE
            )
        );
    }

    /**
     * Method to add Cascading Select type to where clause
     */
    private void createNotCascadingSelectWhereClause(String cascadingSelect) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                Question__c.Type__c.getDescribe().getName(),
                SObjectSelector.NOT_EQUALS_OPERATOR,
                cascadingSelect
            )
        );
    }

    /**
     * Method to add survey Id to where clause
     */
    private void createSurveyWhereClause(Id surveyId) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                Question__c.Survey__c.getDescribe().getName(),
                SObjectSelector.EQUALS_OPERATOR,
                surveyId
            )
        );
    }

    /**
     * Method to add Survey__r.isPPI__c value to where clause
     */
    private void createIsPPIWhereClause(Boolean isPPI) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                this.getMainQueryBuilder().generateLookUp(
                    new List<Schema.SObjectField> {
                        Question__c.Survey__c,
                        Survey__c.IsPPI__c
                    }
                ),
                SObjectSelector.EQUALS_OPERATOR,
                isPPI
            )
        );
    }

    /**
     * Method to add Survey__r.IsTemplate__c value to where clause
     */
    private void createIsTemplateWhereClause(Boolean isTemplate) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                this.getMainQueryBuilder().generateLookUp(
                    new List<Schema.SObjectField> {
                        Question__c.Survey__c,
                        Survey__c.IsTemplate__c
                    }
                ),
                SObjectSelector.EQUALS_OPERATOR,
                isTemplate
            )
        );
    }

    /**
     * Method to add isDraft value to where clause
     */
    private void createIsDraftWhereClause(Double isDraft) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                Question__c.IsDraft__c.getDescribe().getName(),
                SObjectSelector.EQUALS_OPERATOR,
                isDraft
            )
        );
    }
}