src/objects/CascadingLevel__c.object
<CustomObject>
    <description>Represents a Level of a Cascading select question type.</description>
    <fields>
        <fullName>CascadingSelect__c</fullName>
        <description>The Cascading Select this level belongs to.</description>
        <label>Cascading Select</label>
        <referenceTo>CascadingSelect__c</referenceTo>
        <relationshipLabel>Cascading Levels</relationshipLabel>
        <relationshipName>Cascading_Levels</relationshipName>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <description>The Position of the select level</description>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Cascading Level</label>
    <nameField>
    <displayFormat>CL-{00000000}</displayFormat>
        <label>Cascading Level Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cascading Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CascadingSelect__c.object
<CustomObject>
    <description>Represents a Cascading select question type model.</description>
        <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Processing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cascading Select</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cascading Selects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LicenseSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>To block or enable functionality in the client package . Indicates whether a function is enable or if there is a limit to use it.</description>
    <fields>
        <fullName>PPI_Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PPI_Editable</label>
        <type>Checkbox</type>
    </fields>
    <label>LicenseSettings</label>
</CustomObject>

src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Position of the option within the option group</description>
        <label>Position</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Parent question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CascadingLevel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Cascading Level which this Question belongs to.</description>
        <label>Cascading Level</label>
        <referenceTo>CascadingLevel__c</referenceTo>
        <relationshipLabel>Cascading Levels</relationshipLabel>
        <relationshipName>Cascading_Levels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CascadingSelect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Cascading Select that this question represents(only if the question is of cascading type)</description>
        <label>Cascading Select</label>
        <referenceTo>CascadingSelect__c</referenceTo>
        <relationshipLabel>Cascading Select</relationshipLabel>
        <relationshipName>Cascading_Select</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>repeat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-short</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-long</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-decimal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-datetime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>static-content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>end_of_survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>barcode</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>gps-location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>picture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-select</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-level</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SkipCondition__c.object
<CustomObject>
    <fields>
        <fullName>Condition__c</fullName>
        <description>Condition to apply to the source question value.</description>
        <label>Condition</label>
        <picklist>
            <picklistValues>
                <fullName>Answered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Is</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LesserThan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GreaterThan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InRange</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Negate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determine if the result of the evaluation must be negated (return true instead of false, and back-wise).</description>
        <label>Negate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <description>Question on which this condition is applied</description>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Skip Conditions</relationshipLabel>
        <relationshipName>SkipConditions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SkipValue__c</fullName>
        <externalId>true</externalId>
        <label>SkipValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceQuestion__c</fullName>
        <description>Question whose result will be evaluated to determine if the parent question is shown. This question must be previous to the parent question in the survey.</description>
        <label>SourceQuestion</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Affected Skip Conditions</relationshipLabel>
        <relationshipName>AffectedSkipConditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Skip Condition</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Skip Condition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skip Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <description>This is the alias of the Survey</description>
        <label>Alias</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SurveyQuestionLogicControllerTest.cls
/*
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 */
@isTest
private class SurveyQuestionLogicControllerTest {

//------------
// Utility
//------------

    /**
     * Auxiliary method to create a new survey, and an instance of the controller and sets the current page for testing with the needed parameter
     * @param sectionType type of the section to create
     * @return SurveyQuestionLogicController instance
     */
    public static SurveyQuestionLogicController getNewController(String sectionType){

        Survey__c newSurvey = new Survey__c(Status__c = SurveyDO.STATUS_DRAFT); insert newSurvey;
        Question__c section = new Question__c(Survey__c = newSurvey.Id, Caption__c = QuestionDO.TYPE_SECTION, Name = QuestionDO.TYPE_SECTION, Type__c = sectionType );
        insert section;
        getQuestionsList(newSurvey.Id, section.Id,'Q');
        ApexPages.StandardController stdController = new ApexPages.StandardController(newSurvey);

        PageReference currentPage = Page.SurveyQuestionLogic;
        Test.setCurrentPage(currentPage);
        currentPage.getParameters().put('id', newSurvey.Id);

        return new SurveyQuestionLogicController(stdController);
    }

  // creates a list of 5 new questions and inserts them
  // also creates options and conditions for them
  public static list<Question__c> getQuestionsList(string surveyId, string parentId,string prefix){

    list<Question__c> listReturn = new list<Question__c>();
    Question__c auxQuestion;
    for (integer i = 0; i < 5; i++){
        auxQuestion = new Question__c (Survey__c = surveyId, Caption__c = prefix + i, Name = prefix + i, Parent__c = parentId,Type__c = 'Text', Position__c = i+1);
        listReturn.add(auxQuestion);
    }
    insert listReturn;

    Option__c auxOption;
    list<Option__c> listOptions = new list<Option__c>();
    SkipCondition__c auxCondition;
    list<SkipCondition__c> listConditions = new list<SkipCondition__c>();
    for (integer i = 0; i < 5; i++){
        auxOption = new Option__c (Question__c = listReturn[i].Id, Name = prefix + i, Position__c = i+1);
        listOptions.add(auxOption);
        if (i != 0) {
            auxCondition = new SkipCondition__c (
                Parent__c = listReturn[i].Id,
                SourceQuestion__c = listReturn[0].Id,
                Condition__c = 'Is',
                Negate__c = false,
                SkipValue__c = 'Test'
            );
            listConditions.add(auxCondition);
        }
    }
    insert listOptions;
    insert listConditions;

    return listReturn;
  }

    /**
     * Auxiliary method to generalize testing for section type with a simple skipLogic
     * @param sectionType type of the section to create
     */
    static void testSectionSimpleSkipLogic(String sectionType){
        LicenseSettings__c testLicense = newLicense(false,'Test');
        insert testLicense;
        SurveyQuestionLogicController controller = getNewController(sectionType);

        // test with values
        Question__c sectionQuestion = [SELECT Id, Caption__c, Name, Type__c FROM Question__c WHERE Type__c =:sectionType][0];
        Question__c theQuestion = [SELECT Id, Caption__c, Name, Type__c FROM Question__c WHERE Type__c='Text'][0];

        // generate the json string with skip logic on "theQuestion" asociated to "sectionQuestion"
        string jsonSkipLogic =
        '[{'+
            '"type":"'+sectionQuestion.Type__c+'",'+
            '"id":"'+sectionQuestion.Id+'",'+
            '"caption":"'+sectionQuestion.Caption__c+'",'+
            '"skipLogicOperator":"All",'+
            '"skipLogicBehavior":"Show",'+
            '"skipconditions":[{"id":"ha1elfu9","sourceQuestionId":"'+theQuestion.Id+'","condition":"Is","value":"1","negate":false}]'+
        '}]';

        PageReference currentPage = Page.SurveyQuestionLogic;
        currentPage.getParameters().put('questions', jsonSkipLogic);
        currentPage.getParameters().put('quicksave', 'true');
        Test.setCurrentPage(currentPage);

        system.assertEquals(null, controller.save());
        System.assert(!ApexPages.hasMessages(ApexPages.Severity.FATAL) && !ApexPages.hasMessages(ApexPages.Severity.ERROR),
            'Should not have failed since the survey status is draft');

        // Verify skip condition is correctly associated with the repeated section
        System.assertEquals(
            1,
            [
                SELECT
                    Name
                FROM
                    SkipCondition__c
                WHERE
                    Condition__c = 'Is'
                    AND Negate__c = false
                    AND Parent__c =: sectionQuestion.Id
                    AND SourceQuestion__c=:theQuestion.Id
                    AND SkipValue__c='1'
            ].size()
        );
    }


    /**
     * Test method for repeated section with skip logic
     */
    static testMethod void saveTestRepeatedSection(){
        Test.startTest();
            testSectionSimpleSkipLogic(QuestionDO.TYPE_REPEAT);
        Test.stopTest();
    }


    /**
     * Test method for section with skip logic
     */
    static testMethod void saveTestSection(){
        Test.startTest();
            testSectionSimpleSkipLogic(QuestionDO.TYPE_SECTION);
        Test.stopTest();
    }

    /**
     * Simple test method for skip conditions
     */
    static testMethod void saveTest(){
        LicenseSettings__c testLicense = newLicense(false,'Test');
        insert testLicense;

        SurveyQuestionLogicController controller = getNewController(QuestionDO.TYPE_SECTION);

        // test with values
        Question__c firstQuestion = [SELECT Id, Caption__c, Name, Type__c FROM Question__c][1];
        Question__c theQuestion   = [SELECT Id, Caption__c, Name, Type__c FROM Question__c][2];
        
        string newQuestion = '[{'
            +'"id":"' + theQuestion.Id + '",'
            +'"caption":"' + theQuestion.Caption__c + '",'
            +'"type":"' + theQuestion.Type__c + '",'
            +'"options":[{"id":"a","name":"a-orig","position":"1"},{"id":"b","name":"b","position":"2"}],'
            +'"skipconditions":[{"id":"123","sourceQuestionId":"' + firstQuestion.Id + '","condition":"Is","value":"Test","negate":true},{"id":"456","sourceQuestionId":"' + firstQuestion.Id + '","condition":"Is","value":"OtherTest","negate":true}]'
            +'}]';

        PageReference currentPage = Page.SurveyQuestionLogic;
        currentPage.getParameters().put('questions', newQuestion);
        currentPage.getParameters().put('quicksave', 'true');
        Test.setCurrentPage(currentPage);

        system.assertEquals(null, controller.save());
        System.assert(!ApexPages.hasMessages(ApexPages.Severity.FATAL) && !ApexPages.hasMessages(ApexPages.Severity.ERROR));


        // test with non-draft survey
        Survey__c theSurvey = [SELECT id, Status__c FROM Survey__c];
        SurveyDO.updateSurveysStatus(new List <Survey__c> {theSurvey}, SurveyDO.STATUS_PUBLISHED);
        
        Test.startTest();
            controller.save();
        Test.stopTest();
        System.assert(ApexPages.hasMessages(ApexPages.Severity.FATAL) || ApexPages.hasMessages(ApexPages.Severity.ERROR),
                    'Should have failed since the survey is non-draft');
    }

    /**
     * Test case that test skip condition for GPS Question depending on previous question and future question
     */
    static testMethod void saveGPSQuestionLogic() {
        // Create a survey record
        Survey__c survey = TestUtils.createSurvey('survey');

        // Create a new section
        Question__c sectionQuestion = TestUtils.addQuestion(survey , 1, 'section' , QuestionDO.TYPE_SECTION);

        // Create questions
        Question__c freeTextQuestion = TestUtils.addQuestion(sectionQuestion, 1, 'freeText', QuestionDO.TYPE_TEXT_SHORT);
        Question__c gpsQuestion = TestUtils.addQuestion(sectionQuestion, 2, 'gps', QuestionDO.TYPE_GPS);
        Question__c staticQuestion = TestUtils.addQuestion(sectionQuestion, 3,'static', QuestionDO.TYPE_STATIC);

        // Verify questions are inserted properly
        System.assertEquals(true, freeTextQuestion != null);
        System.assertEquals(true, gpsQuestion != null);
        System.assertEquals(true, staticQuestion != null);

        String newQuestion = '[{'
            +'"id":"' + gpsQuestion.Id + '",'
            +'"caption":"' + gpsQuestion.Caption__c + '",'
            +'"type":"' + gpsQuestion.Type__c + '",'
            +'"skipconditions":[{"id":"previousGPS","sourceQuestionId":"' + freeTextQuestion.Id + '","condition":"Is","value":"Test","negate":false}]'
            +'},{'
            +'"id":"' + staticQuestion.Id + '",'
            +'"caption":"' + staticQuestion.Caption__c + '",'
            +'"type":"' + staticQuestion.Type__c + '",'
            +'"skipconditions":[{"id":"futureGPS","sourceQuestionId":"' + gpsQuestion.Id + '","condition":"ANSWERED","negate":true}]'
            +'}]';

        ApexPages.StandardController stdController = new ApexPages.StandardController(survey);
        PageReference currentPage = Page.SurveyQuestionLogic;
        currentPage.getParameters().put('id', survey.Id);
        currentPage.getParameters().put('questions', newQuestion);
        currentPage.getParameters().put('quicksave', 'true');
        Test.setCurrentPage(currentPage);

        SurveyQuestionLogicController controller = new SurveyQuestionLogicController(stdController);
        Test.startTest();
        controller.save();
        Test.stopTest();

        // Verify skip condition is correctly associated with the GPS question dependent on previous question
        System.assertEquals(
            1,
            [
                SELECT
                    Name
                FROM
                    SkipCondition__c
                WHERE
                    Condition__c = 'Is'
                    AND Negate__c = false
                    AND Parent__c = :gpsQuestion.Id
                    AND SourceQuestion__c = :freeTextQuestion.Id
                    AND SkipValue__c = 'Test'
            ].size()
        );

        // Verify skip condition is correctly associated with the future question dependent on GPS question
        System.assertEquals(
            1,
            [
                SELECT
                    Name
                FROM
                    SkipCondition__c
                WHERE
                    Condition__c = 'ANSWERED'
                    AND Negate__c = true
                    AND Parent__c = :staticQuestion.Id
                    AND SourceQuestion__c = :gpsQuestion.Id
            ].size()
        );
    }

    static LicenseSettings__c newLicense(Boolean PPIEditable, String licName){
        list<LicenseSettings__c> lS = [SELECT PPI_Editable__c FROM LicenseSettings__c limit 1];
        delete lS;
        LicenseSettings__c li = new LicenseSettings__c(PPI_Editable__c = PPIEditable, Name = licName);
        return li;
    }

    /**
     * This test the proper throw an error when I try to make changes in the Field mapping
     * for this survey mean while the survey is been update.
     * This should not let me save the changes since the survey was modified.
     */
    static testMethod void testOutofSyncSaveError(){

        // PREPARE: Create a base survey that will be edited
        Survey__c survey = new Survey__c(Name='survey');
        insert survey;
        Question__c section = new Question__c(Survey__c=survey.Id,Name=QuestionDO.TYPE_SECTION,Caption__c=QuestionDO.TYPE_SECTION,Position__c=1,Type__c=QuestionDO.TYPE_SECTION);
        insert section;
        Question__c sourceq = new Question__c(Survey__c=survey.Id,Name='source',Parent__c=section.Id, Caption__c='source',Position__c=1,Type__c=QuestionDO.TYPE_TEXT_SHORT);
        Question__c targetq = new Question__c(Survey__c=survey.Id,Name='target',Parent__c=section.Id, Caption__c='target',Position__c=2,Type__c=QuestionDO.TYPE_TEXT_SHORT);
        insert new Question__c[]{sourceq,targetq};

        // TEST: Have someone else edit the survey, and try to edit the skip condition
        string newQuestion = '[{'
            +'"id":"' + section.Id + '",'
            +'"caption":"' + section.Caption__c + '",'
            +'"type":"' + section.Type__c + '",'
            +'"skipconditions":[]'
            +'},{'
            +'"id":"' + sourceq.Id + '",'
            +'"caption":"' + sourceq.Caption__c + '",'
            +'"type":"' + sourceq.Type__c + '",'
            +'"skipconditions":[]'
            +'},{'
            +'"id":"' + targetq.Id + '",'
            +'"caption":"' + targetq.Caption__c + '",'
            +'"type":"' + targetq.Type__c + '",'
            +'"skipconditions":['
                +'{'
                +'"id":"qwerty",'
                +'"sourceQuestionId":"' + sourceq.Id + '",'
                +'"condition":"' + SkipConditionDO.CONDITION_ISANSWERED + '",'
                +'"value":"Test",'
                +'"negate":true}]'
            +'}]';

        PageReference currentPage = Page.SurveyQuestionLogic;
        currentPage.getParameters().put('id', survey.Id);
        Test.setCurrentPage(currentPage);
        SurveyQuestionLogicController controller = new SurveyQuestionLogicController(new ApexPages.StandardController(survey));

        Test.startTest();
            // Edit the survey outside the controller
            C.wait(1);
            survey = [SELECT Id, Alias__c FROM Survey__c WHERE Id = :survey.Id];
            survey.Alias__c = 'Changed';
            update survey;

            currentPage.getParameters().put('questions', newQuestion);
            currentPage.getParameters().put('quicksave', 'true');
            controller.save();
        Test.stopTest();

        //It should throw an error popup to refresh the page
        System.assert(controller.concurrentSave, 'Should throw an error popup to refresh the page');
    }

    /**
     * Validate the insertion of a skip condition with an invalid source question
     */
    static testMethod void validateInsertionOfConditionWithNonValidQuestionAsSourceQuestion(){
        // Try to insert
        prepareInsertAndUpdateInvalidQuestionAsSourceQuestion(true);
        
    }

    /**
     * Validate the update of a skip condition with an invalid source question
     */
    static testMethod void validateUpdateOfConditionWithNonValidQuestionAsSourceQuestion(){
        // Try to update
        prepareInsertAndUpdateInvalidQuestionAsSourceQuestion(false);
        
    }

    /**
     * Auxiliary test that prepares the conditions to execute the test of:
     * 1- Try to insert a skip condition with a cascading as a source question.
     * 2- Try to update an existent valid skip condition changing actual source question for a cascading question.
     */
    public static void prepareInsertAndUpdateInvalidQuestionAsSourceQuestion(Boolean isInsertingWrong){
        LicenseSettings__c testLicense = newLicense(false,'Test');
        insert testLicense;

        Survey__c newSurvey = new Survey__c(Name = 'Test source logic');
        insert newSurvey;
        
        PageReference currentPage = Page.SurveyQuestionLogic;
        currentPage.getParameters().put('id', newSurvey.Id);
        Test.setCurrentPage(currentPage);

        ApexPages.StandardController stdController = new ApexPages.StandardController(newSurvey);
        SurveyQuestionLogicController controller   = new SurveyQuestionLogicController(stdController);
        


        Question__c section = new Question__c(Name       = 'section1', 
                                              Caption__c = 'Section1',
                                              Type__c    = QuestionDO.TYPE_SECTION,
                                              Survey__c  = newSurvey.Id);
        insert section;
        
        // Create cascading select library
        // Build a matrix with the data for the levels
        // Similar to the CSV
        List<List<String>> levelsData = new List<List<String>> {
            new List<String> {'Make', 'Model', 'Year'},
            new List<String> {'Audi', 'A3', '2001'}
        };

        // Create the cascading select with all the levels and values
        List<CascadingLevel__c> levels = TestUtils.createCascadingSelect('Cascading Select', levelsData);

        Question__c cascading = new Question__c(Name               = 'cascading', 
                                                Caption__c         = 'cascading',
                                                Survey__c          = newSurvey.Id, 
                                                Parent__c          = section.Id, 
                                                Position__c        = 1,
                                                Type__c            = QuestionDO.TYPE_CASCADING_SELECT,
                                                CascadingSelect__c = levels[0].CascadingSelect__r.Id);

        Question__c freeText  = new Question__c(Name        = 'freeText', 
                                                Caption__c  = 'freeText', 
                                                Survey__c   = newSurvey.Id, 
                                                Parent__c   = section.Id,
                                                Position__c = 2,
                                                Type__c     = QuestionDO.TYPE_TEXT_SHORT);
        
        Question__c freeText2 = new Question__c(Name        = 'freeText2', 
                                                Caption__c  = 'freeText2', 
                                                Survey__c   = newSurvey.Id, 
                                                Parent__c   = section.Id,
                                                Position__c = 3,
                                                Type__c     = QuestionDO.TYPE_TEXT_SHORT);
        insert new List<Question__c>{cascading, freeText, freeText2};

        if (isInsertingWrong) {
            SkipCondition__c logic = new SkipCondition__c(
                SourceQuestion__c = cascading.Id,
                Condition__c = '',
                Parent__c = freeText.Id,
                SkipValue__c = ''
            );
            Test.startTest();
                try{
                    insert logic;
                    system.assert(false, 'This condition cannot be inserted cause source question is type cascading');
                }catch(Exception e){
                    system.assert(e.getMessage().contains(String.format(System.Label.SKIP_CONDITION_INVALID_SOURCEQUESTION, new String[]{cascading.Name, ' '}) + System.Label.SKIP_CONDITION_INVALID_SOURCEQUESTIONFINALMESSAGE), 'This condition cannot be inserted cause source question is type cascading');
                }
            Test.stopTest();
        } else {
            SkipCondition__c logic = new SkipCondition__c(
                SourceQuestion__c = freeText.Id,
                Condition__c = '',
                Parent__c = freeText2.Id,
                SkipValue__c = ''
            );
            insert logic;

            // Change source question to cascading
            logic.SourceQuestion__c = cascading.Id;

            Test.startTest();
                try{
                    update logic;
                    system.assert(false, 'This condition cannot be updated cause source question is type cascading');
                }catch(Exception e){
                    system.assert(e.getMessage().contains(String.format(System.Label.SKIP_CONDITION_INVALID_SOURCEQUESTION, new String[]{cascading.Name, ' '}) + System.Label.SKIP_CONDITION_INVALID_SOURCEQUESTIONFINALMESSAGE), 'This condition cannot be updated cause source question is type cascading');
                }
            Test.stopTest();
        }
    }
}