src/objects/CascadingSelect__c.object
<CustomObject>
    <description>Represents a Cascading select question type model.</description>
        <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Processing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cascading Select</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cascading Selects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PPIScore__c</fullName>
        <description>The score that PpiScoreValue__c contains. This needs to be manually updated via a trigger each time the PpiScoreValue__c is changed. If PpiScoreValue__c is blank then this left blank. Should only be set by the trigger on ScoreValue__c</description>
        <label>PPI Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Position of the option within the option group</description>
        <label>Position</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Parent question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CascadingSelect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Cascading Select that this question represents(only if the question is of cascading type)</description>
        <label>Cascading Select</label>
        <referenceTo>CascadingSelect__c</referenceTo>
        <relationshipLabel>Cascading Select</relationshipLabel>
        <relationshipName>Cascading_Select</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CurrentTime__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set date of the day and current time(take from device) as initial value</description>
        <label>Use current date/time as default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DoAfter__c</fullName>
        <label>DoAfter</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DoBefore__c</fullName>
        <label>DoBefore</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Hint__c</fullName>
        <description>A hint for the question</description>
        <label>Supporting text / Instructions</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsDraft__c</fullName>
        <description>Does the question belong to a survey version that can be edited? (1 = True, 0 = False)</description>
        <formula>IF(
    AND(FromVersion__c &lt;= Survey__r.Version__c,
        OR(ToVersion__c = 0,
        ToVersion__c &gt;= Survey__r.Version__c)
    ),1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Can be edited</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsRemoteEditable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Can be edited in downloaded survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Maximum__c</fullName>
        <label>Maximum</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum__c</fullName>
        <label>Minimum</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RemoteServerId__c</fullName>
        <description>Deprecated. Use RemoteId__c as it is indexed</description>
        <label>Remote Server Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RepeatSourceValue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Source Question to determine the times a repeated question must be repeated</description>
        <label>Repeat Source Value</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Source Question</relationshipLabel>
        <relationshipName>SourceQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this question must be answered before moving to the next question</description>
        <inlineHelpText>Check if this question must be answered before moving to the next question</inlineHelpText>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SamePage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>All questions of a section show on same page</description>
        <label>Show all questions on one page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SkipLogicBehavior__c</fullName>
        <label>SkipLogicBehavior</label>
        <picklist>
            <picklistValues>
                <fullName>Show</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hide</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SkipLogicOperator__c</fullName>
        <label>SkipLogicOperator</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Any</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>repeat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-short</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-long</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-decimal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-datetime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>static-content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>end_of_survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>barcode</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>gps-location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>picture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-select</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-level</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SkipCondition__c.object
<CustomObject>
    <fields>
        <fullName>Condition__c</fullName>
        <description>Condition to apply to the source question value.</description>
        <label>Condition</label>
        <picklist>
            <picklistValues>
                <fullName>Answered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Is</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LesserThan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GreaterThan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InRange</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Negate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determine if the result of the evaluation must be negated (return true instead of false, and back-wise).</description>
        <label>Negate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <description>Question on which this condition is applied</description>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Skip Conditions</relationshipLabel>
        <relationshipName>SkipConditions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SkipValue__c</fullName>
        <externalId>true</externalId>
        <label>SkipValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceQuestion__c</fullName>
        <description>Question whose result will be evaluated to determine if the parent question is shown. This question must be previous to the parent question in the survey.</description>
        <label>SourceQuestion</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Affected Skip Conditions</relationshipLabel>
        <relationshipName>AffectedSkipConditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Skip Condition</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Skip Condition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skip Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <description>This is the alias of the Survey</description>
        <label>Alias</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the survey is a PPI Survey</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this survey is actually a template. If this is checked then this survey cannot be distributed on its own. It must be included into another survey</description>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SurveyQuestionLogicController.cls
/*
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved*
 */
public with sharing class SurveyQuestionLogicController {

    public Survey__c survey{get; set;}
    // ERROR MESSAGES
    public static final String ERR_UNKNOWN_QUESTION = system.label.QUESTION_BUILDER_ERR_UNKNOWN_QUESTION;
    public static final String ERR_SURVEY_ALREADY_PUBLISHED= system.label.QUESTION_BUILDER_ERR_SURVEY_ALREADY_PUBLISHED;
    public String SurveyAlreadyPublished{get{return ERR_SURVEY_ALREADY_PUBLISHED;}}
    private DateTime lastModified;
    public Boolean concurrentSave{ get; set; }
    public static final String FIRST_SECTION='1'; //Constant to handle the First Section of the page

    // Labels for conditions, behaviors and operators
    public String getConditions(){
        return JSON.serialize(SkipConditionDO.getConditionTranslations());
    }
    public String getBehaviors(){
        return JSON.serialize(QuestionDO.getSkipConditionBehaviorTranslations());
    }
    public String getOperators(){
        return JSON.serialize(QuestionDO.getSkipConditionOperatorsTranslations());
    }

    // Maps to keep correspondence between builder objects and actual Salesforce objects.
    private Map<String,Question__c> sfquestions = new Map<String,Question__c>();
    private Map<String,Option__c> sfoptions = new Map<String,Option__c>();
    private Map<String,SkipCondition__c> sfskipconditions = new Map<String, SkipCondition__c>();
    public boolean hasApexMessage{get{
                            return (ApexPages.hasMessages(ApexPages.Severity.ERROR) || ApexPages.hasMessages(ApexPages.Severity.FATAL));
                            }set;}
    public Boolean isPublished {
                            get{
                                return (survey.Status__c == SurveyDO.STATUS_PUBLISHED);
                            }set;}
    private Integer offset;            // offset to retrieve next batch of questions
    private Boolean hasMoreQuestions;  // set if all questions have already been retrieved
    private BuilderQuestion[] lastBatchOfQuestions;

    public Integer getOffset(){ return offset; }
    public Boolean getHasMoreQuestions(){ return hasMoreQuestions; }
    public String getLastBatchOfquestions(){ return JSON.serialize(lastBatchOfQuestions); }

    //CONSTRUCTOR
    public SurveyQuestionLogicController(ApexPages.StandardController stdController) {
        this.survey = (Survey__c)stdController.getRecord();


        // Catching when the url id is null
        if(this.survey.Id != null) {
            GenericObjectCreator surveyCreator =
                new GenericObjectCreator(Survey__c.SObjectType);
            surveyCreator.checkObjectAccessible();
            surveyCreator.checkFieldsAccessible(new List<Schema.SObjectField> {
                Survey__c.Name,
                Survey__c.Status__c,
                Survey__c.Alias__c,
                Survey__c.Version__c,
                Survey__c.IsPPI__c,
                Survey__c.IsTemplate__c
            });
            this.survey = [SELECT Id, Name, Alias__c, Version__c, LastModifiedDate, IsPPI__c, IsTemplate__c, Status__c FROM Survey__c WHERE Id=:this.survey.id limit 1];
        } else {
            throw new C.InvalidUrlException(system.Label.BUILDER_ERR_INVALIDURL);
        }

        // setting concurrent save to false
        concurrentSave = false;

        offset = 0;
        lastBatchOfQuestions = new BuilderQuestion[]{};

        lastModified = this.survey.LastModifiedDate;

        loadMoreQuestions();

        //if the survey is published add an error
        if (survey.Status__c == SurveyDO.STATUS_PUBLISHED){
            ApexPages.message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, system.Label.BUILDER_ERR_SURVEYALREADYPUBLISHED);
            ApexPages.addMessage(myMsg);
        }
    }

    public void loadMoreQuestions(){
        hasMoreQuestions = false;
        lastBatchOfQuestions.clear();

        GenericObjectCreator questionCreator =
            new GenericObjectCreator(Question__c.SObjectType);
        questionCreator.checkObjectAccessible();
        questionCreator.checkFieldsAccessible(
            new List<Schema.SObjectField> {
                Question__c.Name,
                Question__c.Type__c,
                Question__c.Caption__c,
                Question__c.Survey__c,
                Question__c.Parent__c,
                Question__c.Hint__c,
                Question__c.Position__c,
                Question__c.Minimum__c,
                Question__c.Maximum__c,
                Question__c.DoBefore__c,
                Question__c.DoAfter__c,
                Question__c.Required__c,
                Question__c.SamePage__c,
                Question__c.CurrentTime__c,
                Question__c.SkipLogicBehavior__c,
                Question__c.SkipLogicOperator__c,
                Question__c.CascadingSelect__c
            }
        );

        GenericObjectCreator optionCreator =
            new GenericObjectCreator(Option__c.SObjectType);
        optionCreator.checkObjectAccessible();
        optionCreator.checkFieldsAccessible(new List<Schema.SObjectField>{
            Option__c.Name,
            Option__c.Caption__c,
            Option__c.Position__c,
            Option__c.Question__c,
            Option__c.PPIScore__c
        });

        GenericObjectCreator skipConditionCreator =
            new GenericObjectCreator(SkipCondition__c.SObjectType);
        skipConditionCreator.checkObjectAccessible();
        skipConditionCreator.checkFieldsAccessible(
            new List<Schema.SObjectField> {
                SkipCondition__c.Parent__c,
                SkipCondition__c.SkipValue__c,
                SkipCondition__c.SourceQuestion__c,
                SkipCondition__c.Condition__c,
                SkipCondition__c.Negate__c
            }
        );

        // Obtain all questions, with their options and skip conditions
        Question__c[] questionList = [
                SELECT Id, Name, Survey__c, Type__c, Parent__c, Caption__c, Hint__c, Position__c,
                       Minimum__c, Maximum__c, DoBefore__c, DoAfter__c, Required__c, SamePage__c,
                       CurrentTime__c, SkipLogicBehavior__c, SkipLogicOperator__c, CascadingSelect__c, CascadingSelect__r.Name,
                       IsRemoteEditable__c, RemoteServerId__c, RepeatSourceValue__c, RepeatSourceValue__r.Name,
                       (SELECT Id, Name, Caption__c, Position__c, Question__c, PPIScore__c
                        FROM   Options__r
                        ORDER BY Position__c),
                       (
                           SELECT
                               Id,
                               Parent__c,
                               SourceQuestion__c,
                               Condition__c,
                               Negate__c,
                               SkipValue__c
                           FROM
                               SkipConditions__r
                           ORDER BY Id
                       )
                FROM   Question__c
                WHERE  Survey__c = :this.survey.Id AND IsDraft__c = 1
                ORDER BY Survey__r.Id, Parent__r.Position__c, Position__c
                OFFSET :offset];

        Set<Id> processedQuestions = new Set<Id>();

        Integer cpuTimeLimit = Limits.getLimitCpuTime() - 1000; // save some CPU time for score values
        for(Question__c q : questionList){

            sfquestions.put(q.Id, q);
            BuilderQuestion bq = new BuilderQuestion(q);
            lastBatchOfQuestions.add(bq);

            for(Option__c o : q.Options__r){
                sfoptions.put(o.Id, o);
                bq.options.add(new BuilderQuestion.Option(o));
            }

            for(SkipCondition__c c : q.SkipConditions__r){
                sfskipconditions.put(c.Id, c);
                bq.skipconditions.add(new BuilderQuestion.SkipCondition(c));
            }

            offset++;
            processedQuestions.add(q.Id);

            if (cpuTimeLimit > 0 && cpuTimeLimit < Limits.getCpuTime()) {
                hasMoreQuestions = true;
                return;
            }
        }
    }

    // Shorthand method
    private String getParam(String key){ return ApexPages.CurrentPage().getParameters().get(key); }

    // Saves the list of questions to the database
    public PageReference save(){

        GenericObjectCreator surveyCreator =
            new GenericObjectCreator(Survey__c.SObjectType);
        surveyCreator.checkObjectAccessible();
        surveyCreator.checkObjectUpdateable();
        surveyCreator.checkFieldsAccessible(new List<Schema.SObjectField> {
            Survey__c.Status__c,
            Survey__c.IsPPI__c
        });

        GenericObjectCreator skipConditionCreator =
            new GenericObjectCreator(SkipCondition__c.SObjectType);
        skipConditionCreator.checkObjectAccessible();
        skipConditionCreator.checkObjectDeletable();
        skipConditionCreator.checkObjectCreateable();

        GenericObjectCreator questionCreator =
            new GenericObjectCreator(Question__c.SObjectType);
        questionCreator.checkObjectAccessible();
        questionCreator.checkObjectUpdateable();

        Boolean hasError = false;
        this.survey = [SELECT Status__c,LastModifiedDate FROM Survey__c WHERE Id = :this.survey.Id];
        if (this.survey.Status__c != SurveyDO.STATUS_DRAFT) {
            ApexPages.message myMsg = new ApexPages.Message(
                ApexPages.Severity.ERROR,
                System.label.BUILDER_ERR_SURVEYALREADYPUBLISHED
            );
            ApexPages.addMessage(myMsg);
            return null;
        } else if (this.survey.LastModifiedDate != lastModified){
            // Set boolean to true to display popup to refresh the page
            concurrentSave = true;
            return null;
        }

        try {
            surveyCreator.checkObjectUpdateable();
            update survey;
        }
            // Do not add an apex error message because the trigger does
        catch (DmlException e) {
            system.debug(e);
            hasError = true;
        }
        String pquestions = getParam('questions');
        String pquicksave = getParam('quicksave');

        if (!hasError) {
            this.survey = [SELECT LastModifiedDate, IsPPI__c, Status__c  FROM Survey__c WHERE Id=:this.survey.id limit 1];
            lastModified = survey.LastModifiedDate;

            JSONParser parser = JSON.createParser(pquestions);
            BuilderQuestion[] newQuestions = (BuilderQuestion[])parser.readValueAs(BuilderQuestion[].class);

                
            // Delete all existing conditions from local or editbable questions.
            delete [
                SELECT
                    Id
                FROM
                    SkipCondition__c
                WHERE
                    Parent__r.Survey__c = :this.survey.Id
                    AND (Parent__r.RemoteServerId__c = null
                    OR Parent__r.IsRemoteEditable__c = true)
            ];

            // Create all conditions again
            SkipCondition__c[] conditions = new SkipCondition__c[]{};
            Question__c[] questions = new Question__c[]{};
            for(BuilderQuestion bq : newQuestions) {
                Question__c question = sfquestions.get(bq.id);

                // Prevent edition of readonly qustions (protect from html-js hacker users -- it's ok if page crashes on their face)
                if (question.RemoteServerId__c != null && question.RemoteServerId__c != '' && !question.IsRemoteEditable__c)
                    SurveyException.raise(System.Label.BUILDER_ERR_NONEDITABLEQUESTION + ' ' + question.Id);

                bq.updateQuestion(question);
                questions.add(question);
                for(BuilderQuestion.SkipCondition cond : bq.skipconditions)
                    conditions.add( cond.createSkipCondition(question) );
            }

            try {
                insert conditions;
            } catch(Exception e) {
                system.debug(e);
            }

            try {
                update questions;
            } catch (Exception e) {
                system.debug(e);
            }

            PageReference goPreview = Page.SurveyFieldMapping;
            goPreview.setRedirect(true);
            goPreview.getParameters().put('id', this.survey.Id);

            return pquicksave == 'true' ? null : goPreview;

        } else {
            return null;
        }
    }
}