src/objects/CascadingSelect__c.object
<CustomObject>
    <description>Represents a Cascading select question type model.</description>
        <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Processing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cascading Select</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cascading Selects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CascadingSelect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Cascading Select that this question represents(only if the question is of cascading type)</description>
        <label>Cascading Select</label>
        <referenceTo>CascadingSelect__c</referenceTo>
        <relationshipLabel>Cascading Select</relationshipLabel>
        <relationshipName>Cascading_Select</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>repeat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-short</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-long</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-decimal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-datetime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>static-content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>end_of_survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>barcode</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>gps-location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>picture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-select</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-level</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CascadingSelectTriggerTest.cls
/**
* Test for the Cascading Select Trigger
* (c) Copyright 2013 Grameen Foundation USA. All rights reserved
*
* @author  Ernesto Quesada
*/
@isTest
private class CascadingSelectTriggerTest{

    /*
    * Delete unused cascading selects that are in ready status
    */
    static testMethod void testCorrectDeleteCascading(){
    
        // Create and insert an uploaded cascading (no need to create levels or values)
        CascadingSelect__c cascadingSelect = new CascadingSelect__c(Name = 'cascadingS1', Status__c = C.CASCADING_STATUS_UPLOADED);
        insert cascadingSelect;
        try {
            delete cascadingSelect;
            system.assert(true);
        } catch (Exception e){
            system.assert(false);
        }
    
    }


    /*
    * Avoid to delete a processing cascading test
    */
    static testMethod void testAvoidDeleteProcessingCascading(){
    
        // Create and insert a uploaded cascading (no need to create levels or values)
        CascadingSelect__c cascadingSelect = new CascadingSelect__c(Name = 'cascadingS1', Status__c = C.CASCADING_STATUS_PROCESSING);
        insert cascadingSelect;
        try {
            delete cascadingSelect;
            system.assert(false);
        } catch (Exception e) {
            system.assert(true);
        }
    }
    
    
    /*
    * Avoid to publish a Job with associated Form Status Draft
    */
    static testMethod void testAvoidDeleteUsedCascading(){
        
        // Create and insert a uploaded cascading (no need to create levels or values)
        CascadingSelect__c cascadingSelect = new CascadingSelect__c(Name = 'cascadingS1', Status__c = C.CASCADING_STATUS_UPLOADED);
        insert cascadingSelect;
        
        // Create a survey 
        Survey__c survey = new Survey__c(Name = 'surveyCascading',
                                                            Status__c  = SurveyDO.STATUS_DRAFT,
                                                            Version__c = 1);
        insert survey;
        Question__c section1 = new Question__c(Name = 'section1',
                                         Caption__c = 'section1',
                                         Survey__c = survey.Id,
                                         Type__c = QuestionDO.TYPE_SECTION,
                                         Position__c = 1);
        insert section1;
                                         
        Question__c q1 = new Question__c(Name = 'cascadingQuestion',
                                         Caption__c = 'cascadingQuestion',
                                         Parent__c = section1.Id,
                                         Survey__c = survey.Id,
                                         Type__c = QuestionDO.TYPE_CASCADING_SELECT,
                                         Position__c = 1,
                                         CascadingSelect__c = cascadingSelect.Id);
        insert q1;
        try {
            delete cascadingSelect;
            system.assert(false);
        } catch (Exception e){
            system.assert(true);
        }
    }
}