src/objects/CascadingSelect__c.object
<CustomObject>
    <description>Represents a Cascading select question type model.</description>
        <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Processing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cascading Select</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cascading Selects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LicenseSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>To block or enable functionality in the client package . Indicates whether a function is enable or if there is a limit to use it.</description>
    <fields>
        <fullName>PPI_Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PPI_Editable</label>
        <type>Checkbox</type>
    </fields>
    <label>LicenseSettings</label>
</CustomObject>

src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Position of the option within the option group</description>
        <label>Position</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Parent question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrentTime__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set date of the day and current time(take from device) as initial value</description>
        <label>Use current date/time as default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DoAfter__c</fullName>
        <label>DoAfter</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DoBefore__c</fullName>
        <label>DoBefore</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Hint__c</fullName>
        <description>A hint for the question</description>
        <label>Supporting text / Instructions</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Maximum__c</fullName>
        <label>Maximum</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minimum__c</fullName>
        <label>Minimum</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this question must be answered before moving to the next question</description>
        <inlineHelpText>Check if this question must be answered before moving to the next question</inlineHelpText>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SamePage__c</fullName>
        <defaultValue>false</defaultValue>
        <description>All questions of a section show on same page</description>
        <label>Show all questions on one page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SkipLogicBehavior__c</fullName>
        <label>SkipLogicBehavior</label>
        <picklist>
            <picklistValues>
                <fullName>Show</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hide</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SkipLogicOperator__c</fullName>
        <label>SkipLogicOperator</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Any</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>repeat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-short</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-long</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-decimal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-datetime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>static-content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>end_of_survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>barcode</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>gps-location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>picture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-select</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-level</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ScoreValue__c.object
<CustomObject>
    <fields>
        <fullName>ScoringGroup__c</fullName>
        <label>Scoring Group</label>
        <referenceTo>ScoringGroup__c</referenceTo>
        <relationshipLabel>Score Values</relationshipLabel>
        <relationshipName>Score_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Score Value</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>Score Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ScoringGroup__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyVersion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Version</label>
        <referenceTo>SurveyVersion__c</referenceTo>
        <relationshipLabel>Scoring Groups</relationshipLabel>
        <relationshipName>Scoring_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Scoring Groups</relationshipLabel>
        <relationshipName>Scoring_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Scoring Group</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Scoring Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SkipCondition__c.object
<CustomObject>
    <fields>
        <fullName>Parent__c</fullName>
        <description>Question on which this condition is applied</description>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Skip Conditions</relationshipLabel>
        <relationshipName>SkipConditions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Skip Condition</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Skip Condition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skip Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <fields>
        <fullName>CloseReason__c</fullName>
        <label>Close Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Automatically Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deprecated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyVersions</relationshipLabel>
        <relationshipName>SurveyVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SurveyPreviewController.cls
/*
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 */
public with sharing class SurveyPreviewController {

    public Survey__c survey{get; set;} // Survey to be shown.
    public List<ScoringGroup> scoringGroups {get;set;} //Scoring groups related to this survey.
    public Boolean builder{get;set;}
    public Boolean isPreview{get;set;}

    public Boolean hasPPILicense{get;set;}  // check if has ppi license
    public Boolean sameOrg{get;set;} // To render the close button just when is in the same org
    public String jsonScoringGroups {get;set;} //Json scoring groups related to this survey.

    private Integer offset;            // offset to retrieve next batch of questions
    private Boolean hasMoreQuestions;  // set if all questions have already been retrieved
    private BuilderQuestion[] lastBatchOfQuestions;

    public Integer getOffset(){ return offset; }
    public Boolean getHasMoreQuestions(){ return hasMoreQuestions; }
    public String getLastBatchOfquestions(){ return JSON.serialize(lastBatchOfQuestions); }

    // Labels for conditions, behaviors and operators
    public String getConditions(){
        return JSON.serialize(SkipConditionDO.getConditionTranslations());
    }
    public String getBehaviors(){
        return JSON.serialize(QuestionDO.getSkipConditionBehaviorTranslations());
    }
    public String getOperators(){
        return JSON.serialize(QuestionDO.getSkipConditionOperatorsTranslations());
    }

    public SurveyPreviewController(ApexPages.StandardController stdController) {
        builder = Apexpages.currentPage().getParameters().get('b') == '0';
        isPreview = true;
        this.survey = (Survey__c)stdController.getRecord();

        setDataForPreview();

        // Set to true when is the same org to show the preview.
        sameOrg = Site.getName() == null;

        // Check if has ppi license
        LicenseSettings__c license = C.getLicense();
        hasPPILicense = license.PPI_Editable__c;

        scoringGroups = new List<ScoringGroup>();

        GenericObjectCreator scoringGroupCreator =
            new GenericObjectCreator(ScoringGroup__c.SObjectType);
        scoringGroupCreator.checkObjectAccessible();
        scoringGroupCreator.checkFieldsAccessible(new List<Schema.SObjectField>{
            ScoringGroup__c.Name,
            ScoringGroup__c.Caption__c
        });

        for (
                ScoringGroup__c scoringGroup :
                    new ScoringGroupSelector().getAllForSurveyPpiOrderByCreatedDate(
                        this.survey.Id,
                        false
                    )
        ) {
            ScoringGroup newScoringGroup = new ScoringGroup(scoringGroup);
            scoringGroups.add( newScoringGroup );
        }
        jsonScoringGroups = JSON.serialize(scoringGroups);

        offset = 0;
        lastBatchOfQuestions = new BuilderQuestion[]{};

        loadMoreQuestions();

        GenericObjectCreator surveyVersionCreator =
            new GenericObjectCreator(SurveyVersion__c.SObjectType);
        surveyVersionCreator.checkObjectAccessible();

        // Validate if the survey was automatically closed, by preview, and show message
        if (this.survey.Status__c == SurveyDO.STATUS_CLOSED) {
            List<SurveyVersion__c> versions = [
                SELECT
                    Id
                FROM
                    SurveyVersion__c
                WHERE
                    Survey__c = :this.survey.Id
                    AND CloseReason__c = :SurveyDO.STATUS_CLOSED_AUTO
                    ORDER BY Version__c DESC
            ];

            if (!versions.isEmpty()) {
                ApexPages.addMessage(new ApexPages.Message(
                    ApexPages.severity.INFO,
                    System.Label.ERR_SURVEY_PREVIEW_WRONGMAP
                ));
            }
        }
    }

    public void loadMoreQuestions() {
        hasMoreQuestions = false;
        lastBatchOfQuestions.clear();

        List<BuilderQuestion.ScoreValue> scoreTempList = new List<BuilderQuestion.ScoreValue>();

        GenericObjectCreator questionCreator =
            new GenericObjectCreator(Question__c.SObjectType);
        questionCreator.checkObjectAccessible();
        questionCreator.checkFieldsAccessible(
            new List<Schema.SObjectField> {
                Question__c.Name,
                Question__c.Survey__c,
                Question__c.Type__c,
                Question__c.Parent__c,
                Question__c.Caption__c,
                Question__c.Hint__c,
                Question__c.Position__c,
                Question__c.Minimum__c,
                Question__c.Maximum__c,
                Question__c.DoBefore__c,
                Question__c.DoAfter__c,
                Question__c.Required__c,
                Question__c.SamePage__c,
                Question__c.CurrentTime__c,
                Question__c.SkipLogicBehavior__c,
                Question__c.SkipLogicOperator__c,
                Question__c.CascadingSelect__c,
                Question__c.IsRemoteEditable__c,
                Question__c.RemoteServerId__c,
                Question__c.RepeatSourceValue__c,
                Question__c.RepeatTimes__c
            }
        );
        GenericObjectCreator cascadingSelectCreator =
            new GenericObjectCreator(CascadingSelect__c.SObjectType);
        cascadingSelectCreator.checkObjectAccessible();
        cascadingSelectCreator.checkFieldsAccessible(new List<Schema.SObjectField>{
            CascadingSelect__c.Name
        });
        GenericObjectCreator optionCreator =
            new GenericObjectCreator(Option__c.SObjectType);
        optionCreator.checkObjectAccessible();
        optionCreator.checkFieldsAccessible(new List<Schema.SObjectField>{
            Option__c.Name,
            Option__c.Caption__c,
            Option__c.Position__c,
            Option__c.Question__c,
            Option__c.PPIScore__c
        });
        GenericObjectCreator skipConditionCreator =
            new GenericObjectCreator(SkipCondition__c.SObjectType);
        skipConditionCreator.checkObjectAccessible();
        skipConditionCreator.checkFieldsAccessible(
            new List<Schema.SObjectField> {
                SkipCondition__c.Parent__c,
                SkipCondition__c.SourceQuestion__c,
                SkipCondition__c.Condition__c,
                SkipCondition__c.Negate__c,
                SkipCondition__c.SkipValue__c
            }
        );

        // Obtain all questions, with their options and skip conditions
        Question__c[] questionList = [
            SELECT
                Id,
                Name,
                Survey__c,
                Type__c,
                Parent__c,
                Caption__c,
                Hint__c,
                Position__c,
                Minimum__c,
                Maximum__c,
                DoBefore__c,
                DoAfter__c,
                Required__c,
                SamePage__c,
                CurrentTime__c,
                SkipLogicBehavior__c,
                SkipLogicOperator__c,
                CascadingSelect__c,
                CascadingSelect__r.Name,
                IsRemoteEditable__c,
                RemoteServerId__c,
                RepeatSourceValue__c,
                RepeatSourceValue__r.Name,
                RepeatTimes__c,
                (
                    SELECT
                        Id,
                        Name,
                        Caption__c,
                        Position__c,
                        Question__c,
                        PPIScore__c
                    FROM
                        Options__r
                        ORDER BY Position__c
                ),
                (
                   SELECT
                       Id,
                       Parent__c,
                       SourceQuestion__c,
                       Condition__c,
                       Negate__c,
                       SkipValue__c
                   FROM
                       SkipConditions__r
                       ORDER BY Id
                )
            FROM
                Question__c
            WHERE
                Survey__c = :this.survey.Id
                AND IsDraft__c = 1
                ORDER BY Survey__r.Id, Parent__r.Position__c, Position__c
                OFFSET :offset
        ];

        Set<Id> processedQuestions = new Set<Id>();
        Map<Id,BuilderQuestion.Option> builderOptions = new Map<Id,BuilderQuestion.Option>();

        Integer cpuTimeLimit = Limits.getLimitCpuTime() - 1000; // save some CPU time for score values
        for(Question__c q : questionList){

            // sfquestions.put(q.Id, q);
            BuilderQuestion bq = new BuilderQuestion(q);
            lastBatchOfQuestions.add(bq);

            for(Option__c o : q.Options__r){
                // sfoptions.put(o.Id, o);
                BuilderQuestion.Option bo = new BuilderQuestion.Option(o);
                bq.options.add(bo);
                builderOptions.put(o.Id, bo);
            }

            for(SkipCondition__c c : q.SkipConditions__r){
                bq.skipconditions.add(new BuilderQuestion.SkipCondition(c));
            }

            offset++;
            processedQuestions.add(q.Id);

            if (cpuTimeLimit > 0 && cpuTimeLimit < Limits.getCpuTime()) {
                hasMoreQuestions = true;
                return;
            }
        }

        GenericObjectCreator scoreValueCreator =
            new GenericObjectCreator(ScoreValue__c.SObjectType);
        scoreValueCreator.checkObjectAccessible();
        scoreValueCreator.checkFieldsAccessible(new List<Schema.SObjectField>{
            ScoreValue__c.Value__c,
            ScoreValue__c.Option__c,
            ScoreValue__c.ScoringGroup__c
        });

        // Obtain ScoreValues for questions selected.
        for (ScoreValue__c scoreValue : [
                SELECT
                    Id,
                    Option__c,
                    Value__c,
                    ScoringGroup__c
                FROM
                    ScoreValue__c
                WHERE
                    Option__r.Question__c IN :processedQuestions
                    ORDER BY ScoringGroup__r.CreatedDate
            ]
        ) {
            builderOptions.get(scoreValue.Option__c).scoreValues.add(
                new BuilderQuestion.ScoreValue(scoreValue)
            );
        }
    }

    // Sets the preview Survey__c object and data to be shown.
    public void setDataForPreview() {

        GenericObjectCreator surveyCreator =
            new GenericObjectCreator(Survey__c.SObjectType);
        surveyCreator.checkObjectAccessible();
        surveyCreator.checkFieldsAccessible(new List<Schema.SObjectField> {
            Survey__c.Name,
            Survey__c.IsPPI__c,
            Survey__c.Alias__c,
            Survey__c.Description__c,
            Survey__c.Deployment__c,
            Survey__c.IsTemplate__c,
            Survey__c.Close_Message__c,
            Survey__c.Status__c
        });

        if (this.survey.Id != null) {
            survey = [
                SELECT
                    Id,
                    Name,
                    IsPPI__c,
                    Alias__c,
                    Description__c,
                    Deployment__c,
                    IsTemplate__c,
                    Close_Message__c,
                    Status__c
                FROM
                    Survey__c
                WHERE
                    Id = :this.survey.Id
            ][0];
        } else {
            throw new C.InvalidUrlException(system.Label.BUILDER_ERR_INVALIDURL);
        }
        String referer = ApexPages.currentPage().getHeaders().get('Referer');
        if (referer != null) {
            String lowerCaseReferer = ApexPages.currentPage().getHeaders().get('Referer').toLowerCase();
            integer refererIndex = lowerCaseReferer.indexOf('surveymanager');
        }
    }

    /*
    *  Given a BuilderQuestion.Option, and a List of BuilderQuestion.ScoreValues, adds the related scoreValues
    *  to the given BuilderQuestion.Option.
    */
    private BuilderQuestion.Option addCorrectScoreValues(BuilderQuestion.Option opt, List<BuilderQuestion.ScoreValue> scoreList ){
        if(scoreList != null && scoreList.size() > 0){
            String idOpt = opt.Id;
            for( BuilderQuestion.ScoreValue sv : scoreList ){
                if(sv.optionId == idOpt){
                    opt.scoreValues.add(sv);
                }
            }
        }
        return opt;
    }

    public with sharing class ScoringGroup {
        public String scoringNumber {get;set;}
        public String caption {get;set;}
        public String id {get;set;}

        public ScoringGroup(ScoringGroup__c source){
            this.scoringNumber = source.Name;
            this.caption = source.Caption__c;
            this.id = source.Id;
        }

    }
}