src/objects/CascadingLevel__c.object
<CustomObject>
    <description>Represents a Level of a Cascading select question type.</description>
    <fields>
        <fullName>CascadingSelect__c</fullName>
        <description>The Cascading Select this level belongs to.</description>
        <label>Cascading Select</label>
        <referenceTo>CascadingSelect__c</referenceTo>
        <relationshipLabel>Cascading Levels</relationshipLabel>
        <relationshipName>Cascading_Levels</relationshipName>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ControllingLevel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Level object parent to this one.</description>
        <label>Controlling Level</label>
        <referenceTo>CascadingLevel__c</referenceTo>
        <relationshipLabel>Cascading Levels</relationshipLabel>
        <relationshipName>CascadingLevels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>The Level Name</description>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <description>The Position of the select level</description>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Cascading Level</label>
    <nameField>
    <displayFormat>CL-{00000000}</displayFormat>
        <label>Cascading Level Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cascading Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CascadingSelect__c.object
<CustomObject>
    <description>Represents a Cascading select question type model.</description>
    <label>Cascading Select</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cascading Selects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CascadingLevelDomainTest.cls
/**
 * Test class for the CascadingLevel__c object domain class
 * Deals with:
 *     - Creation of cascading levels
 *
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 *
 * @author Owen Davies - odavies@grameenfoundation.org
 */
@isTest
public class CascadingLevelDomainTest {

    public static List<CascadingLevel__c> createCascadingLevels(Integer numberOflevels) {
        List<CascadingLevel__c> cascadingLevels = new List<CascadingLevel__c>();
        for (Integer i = 1; i <= numberOflevels; i++) {
            cascadingLevels.add(createCascadingLevel(new Map<Schema.SObjectField, Object>{
                CascadingLevel__c.Name__c => 'Level_' + i,
                CascadingLevel__c.Position__c => i
            }));
        }
        return cascadingLevels;
    }

    public static CascadingLevel__c createCascadingLevel(Map<Schema.SObjectField, Object> fieldMap) {

        GenericObjectCreator creator = new GenericObjectCreator(CascadingLevel__c.getSObjectType());
        CascadingLevel__c cascadingLevel = (CascadingLevel__c) creator.createNewRecord();
        creator.populateFields(
            cascadingLevel,
            fieldMap
        );
        return cascadingLevel;
    }

    /**
     * Adds the passed in CascadingLevel__c to a unit of work.
     * Assumes that the controllingCascadingSelect has already been added
     */
    public static UnitOfWork addLevelsToUnitOfWork(
            List<CascadingLevel__c> cascadingLevels,
            CascadingSelect__c controllingCascadingSelect,
            UnitOfWork unitOfWork
    ) {
        Schema.SObjectType cascadingLevelObjectType = CascadingLevel__c.getSObjectType();
        Integer level = unitOfWork.addToInsertionOrder(cascadingLevelObjectType);
        unitOfWork.addToInsertList(
            cascadingLevels[0],
            CascadingLevel__c.CascadingSelect__c,
            controllingCascadingSelect,
            level
        );
        for (Integer i = 1; i < cascadingLevels.size(); i++) {
            level = unitOfWork.addToInsertionOrder(cascadingLevelObjectType);
            unitOfWork.addToInsertList(
                cascadingLevels[i],
                CascadingLevel__c.CascadingSelect__c,
                controllingCascadingSelect,
                level
            );
            unitOfWork.createRelationship(
                cascadingLevels[i],
                CascadingLevel__c.ControllingLevel__c,
                cascadingLevels[i - 1],
                level
            );
        }
        return unitOfWork;
    }
}