src/objects/Client_Assignation__c.object
<CustomObject>
    <description>Junction object for many to many relationship between Contact and Mobile User objects</description>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Mobile Users Assigned to this Contact</relationshipLabel>
        <relationshipName>Client_Assignations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mobile_User__c</fullName>
        <label>Mobile User</label>
        <referenceTo>Mobile_User__c</referenceTo>
        <relationshipLabel>Assigned Clients</relationshipLabel>
        <relationshipName>Client_Assignations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Client Assignment</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>Client Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mobile_User__c</fullName>
        <formula>IF( IsMobileUser__c &gt; 0
,
IMAGE(&apos;/img/checkbox_checked.gif&apos;, &apos;Checked&apos;)
,
IMAGE(&apos;/img/checkbox_unchecked.gif&apos;, &apos;Not Checked&apos;)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile User Count</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Mobile_User__c.object
<CustomObject>
    <description>Contains information about a Field Officer&apos;s session in Salesforce</description>
    <label>Mobile User</label>
    <nameField>
        <displayFormat>MU-{0000}</displayFormat>
        <label>Mobile User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClientAssignationTest.cls
/*
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 */
@isTest
public class ClientAssignationTest{

    // Client assignment must be unique.
    static testMethod void clientAssignationMustBeUnique() {
        Contact ctc = TestUtils.createContact();
        Mobile_User__c mu = TestUtils.createMobileUser(ctc, 'robert', '1234', MobileUserDO.STATUS_ACTIVE);

        insert new Client_Assignation__c(Client__c = ctc.Id, Mobile_User__c = mu.Id);
        
        Test.startTest();
            // Insert existing assignment
            try {
                insert new Client_Assignation__c(Client__c = ctc.Id, Mobile_User__c = mu.Id);
                system.assert(false, 'Should fail here since ther is a duplicate value');
            }
            catch(DMLException e) {
                system.assert(e.getMessage().contains('duplicate value found'));
            }
        
            // Insert both assignments at same time
            try {
                insert new Client_Assignation__c[]{
                                new Client_Assignation__c(Client__c = ctc.Id, Mobile_User__c = mu.Id),
                                new Client_Assignation__c(Client__c = ctc.Id, Mobile_User__c = mu.Id)};
                system.assert(false, 'Should fail here since are the same assignations to insert');
            }
            catch(DMLException e) {
                system.assert(e.getMessage().contains('duplicate value found'));
            }
        Test.stopTest();
    }
}