src/objects/ContactGroup__c.object
<CustomObject>
    <description>This is a group where a contacts and surveys can be assigned. After that the surveys in the group will be distributed to the users in the group.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Indicates whether the Group is active or inactive</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ContactGroupMember__c.object
<CustomObject>
    <description>Junction object for many to many relationship between Contact and Contact Group objects</description>
    <fields>
        <fullName>ContactGroup__c</fullName>
        <label>Contact Group</label>
        <referenceTo>ContactGroup__c</referenceTo>
        <relationshipLabel>Contact Groups</relationshipLabel>
        <relationshipName>Contact_Group_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Groups</relationshipLabel>
        <relationshipName>Contact_Group_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>CGA-{00000000}</displayFormat>
        <label>Contact Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ContactGroupSurveyAssignment__c.object
<CustomObject>
    <description>Junction object for many to many relationship between Survey and Contact Group objects</description>
    <fields>
        <fullName>ContactGroup__c</fullName>
        <label>Contact Group</label>
        <referenceTo>ContactGroup__c</referenceTo>
        <relationshipName>ContactGroupSurveyAssignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Contact Group Survey Assignment</relationshipLabel>
        <relationshipName>Contact_Group_Survey_Assignment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Assigned Survey</label>
    <nameField>
        <displayFormat>CGSA-{00000000}</displayFormat>
        <label>Assignment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PPITableDataSet__c.object
<CustomObject>
    <description>A junction object that links a Survey Version to a PPI Table. This allows for a m-m relationship between these two objects so that a PPI Table can be referenced by a Survey Version as opposed to needing to be copied. All fields on this object are deprecated and moved to PPI Table except for Survey Version and PPI Table. Survey is kept here as it cannot be moved. It is not needed any more</description>
    <fields>
        <fullName>Survey__c</fullName>
        <description>The Survey that this Data Set links to. Not really needed but as we cannot remove fields from a package yet this is kept. When allowed will be removed and only the Survey Version will be used. Do not reference to this field in any code</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>PPI Table Data Sets</relationshipLabel>
        <relationshipName>PPI_Table_Data_Sets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PPI Table Data Set</label>
    <nameField>
        <displayFormat>PTDS-{00000000}</displayFormat>
        <label>PPI Table Data Set Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPI Table Data Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PPITableLine__c.object
<CustomObject>
    <description>Represents a bucket in the Poverty Table. Used to convert raw score in to a probability</description>
    <fields>
        <fullName>PPITableDataSet__c</fullName>
        <description>Field is deprecated. Use PpiTable__c instead. Set to null in all future PPITableLine records. Leaving existing values to allow for backwards compatibility</description>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PPI Table Data Set</label>
        <referenceTo>PPITableDataSet__c</referenceTo>
        <relationshipLabel>PPI Table Lines</relationshipLabel>
        <relationshipName>PPI_Table_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <description>Probability of being below the poverty line for the specified scoring range</description>
        <label>Probability</label>
        <precision>4</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <label>PPI Table Line</label>
    <nameField>
        <displayFormat>PPIL-{00000000}</displayFormat>
        <label>PPI Table Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPI Table Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Group</label>
        <referenceTo>ContactGroupSurveyAssignment__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Uploading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploaded - Processed after Survey Automatically Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploaded After Survey Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Surveyor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Surveyor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Submissions (Surveyor)</relationshipLabel>
        <relationshipName>SubmissionObtained</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SubmissionPpiAssociation__c.object
<CustomObject>
    <fields>
        <fullName>PpiTableLine__c</fullName>
        <description>The PPI Table line that this record maps to</description>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>PPI Table Line</label>
        <referenceTo>PPITableLine__c</referenceTo>
        <relationshipLabel>Submission PPI Associations</relationshipLabel>
        <relationshipName>Submission_Ppi_Associations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <description>The probability taken from the PPI Table Line that this submission value maps to</description>
        <formula>PpiTableLine__r.Probability__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Probability</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <description>The Submission record that this value belongs to</description>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission</label>
        <referenceTo>Submission__c</referenceTo>
        <relationshipLabel>Submission PPI Associations</relationshipLabel>
        <relationshipName>Submission_Ppi_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission PPI Association</label>
    <nameField>
        <displayFormat>SPA-{0000000000}</displayFormat>
        <label>Junction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission PPI Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SubmissionPPIValue__c.object
<CustomObject>
    <fields>
        <fullName>PPITableLine__c</fullName>
        <description>The PPI Table line that this record maps to</description>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>PPI Table Line</label>
        <referenceTo>PPITableLine__c</referenceTo>
        <relationshipName>Submition_PPI_Values</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <label>Submission</label>
        <referenceTo>Submission__c</referenceTo>
        <relationshipName>Submition_PPI_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submission PPI Value</label>
    <nameField>
        <displayFormat>SPV-{0000000000}</displayFormat>
        <label>Junction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission PPI Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubmissionDO.cls
/**
 * Helper class that contains shared methods for submissions
 *
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 *
 */
public with sharing class SubmissionDO {

    public static final String SEPARATOR = ':';

    public class SubmissionException extends BaseException {}

    /**
     * Find and add the latest group that the surveyor joined to the Submission
     *
     * @param submissions - A list of the submissions to be processed
     *
     * @return - The submissions with the Assignment__c added to it
     */
    public static List<Submission__c> linkSubmissionsAssignmentGroups(List<Submission__c> submissions) {

        // Get the latest assignment for each survey:contact pair in the submissions
        SubmissionAssigner sa = new SubmissionAssigner();
        Map<String,Id> assignments = sa.getAssignments(submissions);
        if (!assignments.isEmpty()) {

            // Go through the submission map and add all the assignment groups to the submissions
            for (Submission__c submission : submissions) {
                sa.populateAssignment(submission, assignments);
            }
        }

        return submissions;
    }

    /**
     * Get the Submission PPI Values for the given submissions
     */
    public static Map<Id, List<SubmissionPPIValue__c>> getSubmissionsPPIValues(
            List<Submission__c> submissions
    ) {
        Map<Id, List<SubmissionPPIValue__c>> ppiValuesBySubmission =
                new Map<Id, List<SubmissionPPIValue__c>>();
        GenericObjectCreator ppiTableLineCreator =
            new GenericObjectCreator(PPITableLine__c.SObjectType);
        ppiTableLineCreator.checkObjectAccessible();
        ppiTableLineCreator.checkFieldsAccessible(new List<Schema.SObjectField> {
            PPITableLine__c.Probability__c,
            PPITableLine__c.PPITableDataSet__c
        });

        GenericObjectCreator submissionPpiValueCreator =
            new GenericObjectCreator(SubmissionPPIValue__c.SObjectType);
        submissionPpiValueCreator.checkObjectAccessible();
        submissionPpiValueCreator.checkFieldsAccessible(new List<Schema.SObjectField> {
            SubmissionPPIValue__c.PPITableLine__c,
            SubmissionPPIValue__c.Submission__c
        });

        for (SubmissionPPIValue__c ppiValue : [
                SELECT
                    Id,
                    Submission__c,
                    PPITableLine__c,
                    PPITableLine__r.Probability__c,
                    PPITableLine__r.PPITableDataSet__c
                FROM
                    SubmissionPPIValue__c
                WHERE
                    Submission__c IN :submissions
        ]) {
            List<SubmissionPPIValue__c> ppiValues =
                    ppiValuesBySubmission.get(ppiValue.Submission__c);

            if (ppiValues == null) {
                ppiValues = new List<SubmissionPPIValue__c>();
                ppiValuesBySubmission.put(ppiValue.Submission__c, ppiValues);
            }
            ppiValues.add(ppiValue);
        }

        return ppiValuesBySubmission;
    }

    /**
     * Get all submission Ppi associations for a specific List of submissions
     */
    public static Map<Id, List<SubmissionPpiAssociation__c>> getSubmissionPpiAssociations(
            List<Submission__c> submissions
    ) {
        Map<Id, List<SubmissionPpiAssociation__c>> ppiAssociationsBySubmission =
            new Map<Id, List<SubmissionPpiAssociation__c>>();
        Set<Id> submissionIds = new Map<Id, Submission__c>(submissions).keySet();
        for (
                SubmissionPpiAssociation__c submissionPpiAssociation :
                    new SubmissionPpiAssociationSelector().getForSubmissionIds(submissionIds)
        ) {
            if (submissionPpiAssociation.Submission__c != null) {
                if (!ppiAssociationsBySubmission.containsKey(submissionPpiAssociation.Submission__c)) {
                    ppiAssociationsBySubmission.put(
                        submissionPpiAssociation.Submission__c,
                        new List<SubmissionPpiAssociation__c> {submissionPpiAssociation}
                    );
                } else {
                    List<SubmissionPpiAssociation__c> submissionPpiAssciations =
                        ppiAssociationsBySubmission.get(
                            submissionPpiAssociation.Submission__c
                        );
                    submissionPpiAssciations.add(submissionPpiAssociation);
                    ppiAssociationsBySubmission.put(
                        submissionPpiAssociation.Submission__c,
                        submissionPpiAssciations
                    );
                }
            }
        }
        return ppiAssociationsBySubmission;
    }

    /**
     * Helper class to get all assignments in the system regardless record sharing,
     * and to link submissions to their right assignment.
     */
    private without sharing class SubmissionAssigner {

        /**
         * Get all assignments for the surveys and surveyors of the given list of submissions.
         * @param submissions the list of submissions to assign
         * @return a map from 'SurveyId:ContactId' to AssignmentId, where the assignment is the
         * last assignment for that contact in that survey
         */
        public Map<String,Id> getAssignments(List<Submission__c> submissions) {

            // Get lists of contacts and surveys to consider
            Set<Id> surveyorIds = new Set<Id>();
            Set<Id> surveyIds   = new Set<Id>();
            for (Submission__c submission : submissions){
                surveyorIds.add(submission.Surveyor__c);
                surveyIds.add(submission.Survey__c);
            }

            GenericObjectCreator contactGroupCreator =
                new GenericObjectCreator(ContactGroup__c.SObjectType);
            contactGroupCreator.checkObjectAccessible();
            GenericObjectCreator contactGroupSurveyAssignmentCreator =
                new GenericObjectCreator(ContactGroupSurveyAssignment__c.SObjectType);
            contactGroupSurveyAssignmentCreator.checkObjectAccessible();
            contactGroupSurveyAssignmentCreator.checkFieldsAccessible(
                new List<Schema.SObjectField> {
                    ContactGroupSurveyAssignment__c.Survey__c
                }
            );
            GenericObjectCreator contactGroupMemberCreator =
                new GenericObjectCreator(ContactGroupMember__c.SObjectType);
            contactGroupMemberCreator.checkObjectAccessible();
            contactGroupMemberCreator.checkFieldsAccessible(new List<Schema.SObjectField> {
                ContactGroupMember__c.Contact__c
            });

            // Create the map
            Map<String,Id> assignments = new Map<String,Id>();
            for (ContactGroup__c cgroup : [
                    SELECT
                        Id,
                        (
                            SELECT
                                Id,
                                Contact__c
                            FROM
                                Contact_Group_Assignments__r
                            WHERE
                                Contact__c IN :surveyorIds
                                ORDER BY LastModifiedDate ASC
                        ),
                        (
                            SELECT
                                Id,
                                Survey__c
                            FROM
                                ContactGroupSurveyAssignment__r
                            WHERE
                                Survey__c IN :surveyIds
                        )
                    FROM
                        ContactGroup__c
                    WHERE
                        Status__c = :C.GROUP_STATUS_ACTIVE
                ]
            ) {

                // Create an entry on the map for each survey:contact pair (newer pairs overwrite old pairs)
                for (ContactGroupSurveyAssignment__c assignment : cgroup.ContactGroupSurveyAssignment__r){
                    for (ContactGroupMember__c member : cgroup.Contact_Group_Assignments__r){
                        String assignmentKey = assignment.Survey__c + SEPARATOR + member.Contact__c;
                        assignments.put(assignmentKey, assignment.Id);
                    }
                }
            }

            return assignments;
        }

        /**
         * Associates to the submission the corresponding assignment from the list.
         * @param submission the Submission__c object that will be associated to an assignment.
         * @param assignments a map from 'SurveyId:ContactId' to AssignmentId, where the assignment is the
         * last assignment for that contact in that survey
         */
        private void populateAssignment(Submission__c submission, Map<String,Id> assignments) {
            GenericObjectCreator submissionCreator =
                new GenericObjectCreator(Submission__c.SObjectType);
            String assignmentKey = submission.Survey__c + SEPARATOR + submission.Surveyor__c;
            submissionCreator.populateFields(
                submission,
                new Map<Schema.SObjectField, Object> {
                    Submission__c.Assignment__c => assignments.get(assignmentKey)
                }
            );
        }

    }
}