src/objects/ContactGroup__c.object
<CustomObject>
    <description>This is a group where a contacts and surveys can be assigned. After that the surveys in the group will be distributed to the users in the group.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>A description for the group</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ContactGroupMember__c.object
<CustomObject>
    <description>Junction object for many to many relationship between Contact and Contact Group objects</description>
    <fields>
        <fullName>ContactGroup__c</fullName>
        <label>Contact Group</label>
        <referenceTo>ContactGroup__c</referenceTo>
        <relationshipLabel>Contact Groups</relationshipLabel>
        <relationshipName>Contact_Group_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Groups</relationshipLabel>
        <relationshipName>Contact_Group_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>CGA-{00000000}</displayFormat>
        <label>Contact Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ContactGroupSurveyAssignment__c.object
<CustomObject>
    <description>Junction object for many to many relationship between Survey and Contact Group objects</description>
    <fields>
        <fullName>ContactGroup__c</fullName>
        <label>Contact Group</label>
        <referenceTo>ContactGroup__c</referenceTo>
        <relationshipName>ContactGroupSurveyAssignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Contact Group Survey Assignment</relationshipLabel>
        <relationshipName>Contact_Group_Survey_Assignment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Assigned Survey</label>
    <nameField>
        <displayFormat>CGSA-{00000000}</displayFormat>
        <label>Assignment Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Group</label>
        <referenceTo>ContactGroupSurveyAssignment__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Surveyor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Surveyor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Submissions (Surveyor)</relationshipLabel>
        <relationshipName>SubmissionObtained</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubmissionDOTest.cls
/**
 * Test class for SubmissionDO
 *
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 */
@isTest
public with sharing class SubmissionDOTest {

        static testMethod void testUpdateSubmissions() {

        // Create some surveys
        Survey__c s1 = new Survey__c( Name = 'Testing Survey 1', Description__c = 'A Description' );
        Survey__c s2 = new Survey__c( Name = 'Testing Survey 2', Description__c = 'A Description' );
        Database.insert(new Survey__c[]{s1,s2});

        // Create a three Groups
        ContactGroup__c g1 = new ContactGroup__c( Name = 'Group1aaaaaa' );
        ContactGroup__c g2 = new ContactGroup__c( Name = 'Group2bbbbbb' );
        Database.insert(new ContactGroup__c[]{g1,g2});

        // Create a couple of surveyors
        Contact c1 = new Contact( LastName = 'c1' );
        Contact c2 = new Contact( LastName = 'c2' );
        Database.insert(new Contact[]{c1,c2});

        // Assign surveys to the groups
        ContactGroupSurveyAssignment__c cgsa1 = new ContactGroupSurveyAssignment__c( Survey__c = s1.Id, ContactGroup__c = g1.Id );
        ContactGroupSurveyAssignment__c cgsa2 = new ContactGroupSurveyAssignment__c( Survey__c = s1.Id, ContactGroup__c = g2.Id );
        ContactGroupSurveyAssignment__c cgsa3 = new ContactGroupSurveyAssignment__c( Survey__c = s2.Id, ContactGroup__c = g1.Id );
        ContactGroupSurveyAssignment__c cgsa4 = new ContactGroupSurveyAssignment__c( Survey__c = s2.Id, ContactGroup__c = g2.Id );
        Database.insert( new ContactGroupSurveyAssignment__c[]{cgsa1, cgsa2, cgsa3, cgsa4} );

        // Assign members to the groups
        Database.insert(new List<ContactGroupMember__c>{
            new ContactGroupMember__c( Contact__c = c1.Id , ContactGroup__c = g1.Id ),
            new ContactGroupMember__c( Contact__c = c2.Id , ContactGroup__c = g1.Id ),
            new ContactGroupMember__c( Contact__c = c1.Id , ContactGroup__c = g2.Id )
        });

        // Create some submissions
        Submission__c[] submissions = new Submission__c[]{
            new Submission__c ( Survey__c = s1.Id, Surveyor__c = c1.Id ),
            new Submission__c ( Survey__c = s1.Id, Surveyor__c = c1.Id ),
            new Submission__c ( Survey__c = s2.Id, Surveyor__c = c1.Id ),
            new Submission__c ( Survey__c = s1.Id, Surveyor__c = c2.Id ),
            new Submission__c ( Survey__c = s2.Id, Surveyor__c = c2.Id )
        };

        // Add the assignment group to the submission
        Test.startTest();
        List<Submission__c> resultSubmissions = SubmissionDO.linkSubmissionsAssignmentGroups(submissions);
        Test.stopTest();
        System.assertEquals(resultSubmissions.size(), 5);

        System.assertEquals(cgsa2.Id, resultSubmissions[0].Assignment__c, resultSubmissions[0]);
        System.assertEquals(cgsa2.Id, resultSubmissions[1].Assignment__c, resultSubmissions[1]);
        System.assertEquals(cgsa4.Id, resultSubmissions[2].Assignment__c, resultSubmissions[2]);
        System.assertEquals(cgsa1.Id, resultSubmissions[3].Assignment__c, resultSubmissions[3]);
        System.assertEquals(cgsa3.Id, resultSubmissions[4].Assignment__c, resultSubmissions[4]);
    }
}