src/objects/ISO_Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>The alpha-2 country codes and the short country names from ISO 3166-1</description>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>The short country names from ISO 3166-1</description>
        <label>Short Name</label>
        <length>70</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ISO_Country</label>
</CustomObject>

src/objects/Language__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>List of languages to select</description>
    <fields>
        <fullName>ShortLanguageName__c</fullName>
        <defaultValue>&apos;English&apos;</defaultValue>
        <label>ShortLanguageName</label>
        <length>70</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Language</label>
</CustomObject>

src/objects/LicenseSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>To block or enable functionality in the client package . Indicates whether a function is enable or if there is a limit to use it.</description>
    <fields>
        <fullName>Can_Distribute__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Can_Distribute</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PPI_Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PPI_Editable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UsePPI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UsePPI</label>
        <type>Checkbox</type>
    </fields>
    <label>LicenseSettings</label>
</CustomObject>

src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PPIScore__c</fullName>
        <description>The score that PpiScoreValue__c contains. This needs to be manually updated via a trigger each time the PpiScoreValue__c is changed. If PpiScoreValue__c is blank then this left blank. Should only be set by the trigger on ScoreValue__c</description>
        <label>PPI Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Position of the option within the option group</description>
        <label>Position</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Parent question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RemoteServerId__c</fullName>
        <description>Deprecated. Use RemoteId__c as it is indexed</description>
        <label>Remote Server Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>repeat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-short</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-long</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-decimal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-datetime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>static-content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>end_of_survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>barcode</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>gps-location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>picture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-select</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-level</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ScoreValue__c.object
<CustomObject>
    <fields>
        <fullName>Option__c</fullName>
        <label>Option</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Score Values</relationshipLabel>
        <relationshipName>Score_Values</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ScoringGroup__c</fullName>
        <label>Scoring Group</label>
        <referenceTo>ScoringGroup__c</referenceTo>
        <relationshipLabel>Score Values</relationshipLabel>
        <relationshipName>Score_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Score Value</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>Score Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ScoringGroup__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Scoring Group is for a PPI Template</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Scoring Groups</relationshipLabel>
        <relationshipName>Scoring_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Scoring Group</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Scoring Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <description>This is the alias of the Survey</description>
        <label>Alias</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountryCode__c</fullName>
        <description>The ISO 3166-1 alpha-2 country code</description>
        <label>Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the survey is a PPI Survey</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LanguageCode__c</fullName>
        <defaultValue>&apos;EN&apos;</defaultValue>
        <label>Language Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PPIDataYear__c</fullName>
        <description>Data year for the PPI survey</description>
        <label>Data Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SurveyScoringControllerTest.cls
/*
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 */
@isTest
public class SurveyScoringControllerTest{

    /**
     * Test for Scoring controller apex error messages when name of the scoring value has no
     * related group name.
     */
    static testMethod void testScoringErrorsGroupName() {
        Survey__c survey1 = newSurvey('FirstSurvey');
        Question__c question1 =
            newQuestion(survey1.Id, 'Name', 'Caption1', QuestionDO.TYPE_SECTION);
        Option__c option1 = newOption(question1.Id, 'NameOption', 1);
        setPPILicenseSetting(false);

        Test.startTest();
        ApexPages.StandardController stdController = new ApexPages.StandardController(survey1);
        SurveyScoringController controller = new SurveyScoringController(stdController);

        // Fails because the name of the scoring value has no related group name.
        controller.scoringGroupStr = '[{"caption":"ScoringGroup2"}]';
        controller.scoringValuesJson  =
            '[{"optionId":"' + option1.Id + '","groupName":"ScoringGroup1","value":"1"}]';
        controller.saveScoring();
        Test.stopTest();
        System.assertEquals(1, Apexpages.getMessages().size());
    }

    /**
     *    Test for Scoring controller apex error messages when the survey is not SurveyDO.STATUS_DRAFT;
     */
    static testMethod void testScoringErrorsStatusClosed(){
        Survey__c survey1 = newSurvey('FirstSurvey');
        Question__c question1 = newQuestion(survey1.Id, 'Name', 'Caption1', QuestionDO.TYPE_SECTION);
        Option__c option1 = newOption(question1.Id, 'NameOption', 1);
        setPPILicenseSetting(false);
        
        Test.startTest();
            ApexPages.StandardController stdController = new ApexPages.StandardController(survey1);
            SurveyScoringController controller = new SurveyScoringController(stdController);

            SurveyDO.updateSurveysStatus(new List <Survey__c> {survey1}, SurveyDO.STATUS_CLOSED);
            System.assertEquals(SurveyDO.STATUS_CLOSED, [SELECT Id, Status__c FROM Survey__c WHERE Id =: survey1.Id].Status__c, 'The status must be closed.');
            controller.saveScoring();
        Test.stopTest();
        // Returns 1 error message.
        System.assertEquals(1, Apexpages.getMessages().size());
    }

    /**
     *    Test for Scoring controller apex error messages when the group has no valid name.
     */
    static testMethod void testScoringErrorsInvalidGroupName(){
        Survey__c survey1 = newSurvey('FirstSurvey');
        Question__c question1 = newQuestion(survey1.Id, 'Name', 'Caption1', QuestionDO.TYPE_SECTION);
        Option__c option1 = newOption(question1.Id, 'NameOption', 1);
        setPPILicenseSetting(false);
        Test.startTest();
            ApexPages.StandardController stdController = new ApexPages.StandardController(survey1);
            SurveyScoringController controller = new SurveyScoringController(stdController);

            // Fails because group has no valid name.
            survey1.Status__c = SurveyDO.STATUS_DRAFT;
            update survey1;
            controller = new SurveyScoringController(stdController);
            controller.scoringGroupStr = '[{"caption":""}]';
            controller.scoringValuesJson  = '[{"optionId":"' + option1.Id + '","groupName":"ScoringGroup4","value":"-1"}]';
            controller.saveScoring();
        Test.stopTest();
        System.assertEquals(1, Apexpages.getMessages().size());
    }

    /**
     *    Test for Scoring controller
     */
    static testMethod void testScoring(){
        Test.startTest();
            testScoringSimple(QuestionDO.TYPE_SECTION);
        Test.stopTest();
    }

    /**
     *    Test for Scoring controller for controls in a repeated section
     */
    static testMethod void testScoringRepeated(){
        Test.startTest();
            testScoringSimple(QuestionDO.TYPE_REPEAT);
        Test.stopTest();
    }

    // Test for Render Scoring
    static testMethod void testRendering(){
        Survey__c survey1 = newSurvey('FirstSurvey');
        Question__c question1 = newQuestion(survey1.Id, 'Name', 'Caption1', QuestionDO.TYPE_SECTION);
        Option__c option1 = newOption(question1.Id, 'NameOption', 1);
        ScoringGroup__c group1 = newScoringGroup('FirstGroup', survey1.Id);
        ScoreValue__c scoreValue1 = newScoreValue(5, group1.Id, option1.Id);
        setPPILicenseSetting(false);
        
        Test.startTest();
            ApexPages.StandardController stdController = new ApexPages.StandardController(survey1);
            SurveyScoringController controller = new SurveyScoringController(stdController);
            System.assertEquals(1, controller.listScoreValues.size());
        Test.stopTest();
    }

    /**
     * This test the proper throw an error when i try to make changes in the Field mapping for this survey mean while the survey is been update.
     * This should not let me save the changes since the survey was modified.
     */
    static testMethod void testOutofSyncUpdateError(){
        Survey__c survey1 = newSurvey('FirstSurvey');
        Question__c question1 = newQuestion(survey1.Id, 'Name', 'Caption1', QuestionDO.TYPE_SECTION);
        Option__c option1 = newOption(question1.Id, 'NameOption', 1);
        ScoringGroup__c group1 = newScoringGroup('FirstGroup', survey1.Id);
        ScoreValue__c scoreValue1 = newScoreValue(5, group1.Id, option1.Id);
        
        Test.startTest();
            ApexPages.StandardController stdController = new ApexPages.StandardController(survey1);
            SurveyScoringController controller = new SurveyScoringController(stdController);

            //Update the survey directly(this is not using the controller.)
            survey1.Alias__c = 'as';

            C.wait(1);
            update survey1;
            survey1 = [Select LastModifiedDate FROM Survey__c WHERE Id=:survey1.Id limit 1];
            DateTime currentLastModifiedDate = survey1.LastModifiedDate;
            //If i try to save the survey from the controller it shouldnt be posible.
            controller.saveScoring();
             //It should throw an error popup to refresh the page
            System.assert(controller.concurrentSave, 'Should throw an error popup to refresh the page');
            //And it shouldn't update the survey.
            survey1 = [Select LastModifiedDate FROM Survey__c WHERE Id=:survey1.Id limit 1];
            System.assertEquals(currentLastModifiedDate,survey1.LastModifiedDate);
        Test.stopTest();
    }

    /**
     * This test if mean while im updating the field mapping no body is updating the survey. So all should be right.
     */
    static testMethod void testOutofSyncUpdateRight(){
        Survey__c survey = newSurvey('FirstSurvey');
        Question__c question1 = newQuestion(survey.Id, 'Name', 'Caption1', QuestionDO.TYPE_SECTION);
        Option__c option1 = newOption(question1.Id, 'NameOption', 1);
        ScoringGroup__c group1 = newScoringGroup('FirstGroup', survey.Id);
        ScoreValue__c scoreValue1 = newScoreValue(5, group1.Id, option1.Id);
        
        Test.startTest();
            ApexPages.StandardController stdController = new ApexPages.StandardController(survey);
            SurveyScoringController controller = new SurveyScoringController(stdController);
            // The following json is an array that includes one object(ScoreValue), with the following attributes: option.Id, GroupScore name, and Value.
            // Given this data I'll try to insert it in the database.
            controller.scoringGroupStr = '[{"caption":"ScoringGroup1"}]';
            controller.scoringValuesJson  = '[{"optionId":"' + option1.Id + '","groupName":"ScoringGroup1","value":"1"}]';
            controller.continueAfterwards = 'true';

            C.wait(1);
            survey = [Select LastModifiedDate FROM Survey__c WHERE Id=:survey.Id limit 1];
            DateTime currentLastModifiedDate = survey.LastModifiedDate;
            //If i try to save the survey from the controller it should be posible.
            controller.saveScoring();

            //It should throw no error
            System.assert(!(ApexPages.hasMessages(ApexPages.Severity.FATAL) || ApexPages.hasMessages(ApexPages.Severity.ERROR)));

            //And it should update the survey.
            survey = [SELECT LastModifiedDate FROM Survey__c WHERE Id = :survey.Id];
            System.assertNotEquals(currentLastModifiedDate,survey.LastModifiedDate);
        Test.stopTest();
    }

    static testMethod void editDistributedPPIScore(){
        // Add license to create new ppi surveys
        LicenseSettings__c license = C.getLicense();
        license.PPI_Editable__c = true;
        license.UsePPI__c = true;
        update license;

        ISO_Country__c countryCode = new ISO_Country__c(Name='AA',ShortName__c='Test');
        insert countryCode;
        Language__c language = new Language__c(Name = 'XX',ShortLanguageName__c = 'XXLanguage');
        insert language;
        // Insert Survey to test
        Survey__c survey = new Survey__c(IsPPI__c=true,CountryCode__c='AA',LanguageCode__c='XX',PPIDataYear__c = 2003, Status__c = 'Draft');
        insert survey;
        // Setting license to true
        setPPILicenseSetting(true);
        // Insert Question in the sruvey
        Question__c question = newQuestion(survey.Id, 'QTest', 'Caption1',QuestionDO.TYPE_SECTION);
        // Insert Option for that question
        Option__c option1 = newOption(question.Id, 'OTest1', 1);
        Option__c option2 = newOption(question.Id, 'OTest2', 2);
        Option__c option3 = newOption(question.Id, 'OTest3', 3);
        // Setting ppi scores values
        option1.PPIScore__c = 1;
        option2.PPIScore__c = 2;
        option3.PPIScore__c = 3;
        update new List<Option__c>{option1, option2, option3};
        // Setting origin id != null to trigger test
        question.RemoteServerId__c = '1234';
        update question;
        
        Test.startTest();
            // Testing if it is a distributed survey
            ApexPages.StandardController stdController = new ApexPages.StandardController(survey);
            SurveyScoringController controller = new SurveyScoringController(stdController);
            System.assert(controller.wasDownloaded, 'Must be true since origin id is not null');
            // Edit some ppi score value to test the trigger
            option2.PPIScore__c = 25;
            try{
                update option2;
                System.assert(false,'Should fail since option2 change ppi score and is a distributed survey');
            }catch(Exception e){
                System.assert(e.getMessage().contains(System.label.SCORE_ERR_CANTEDITDISTRUBUTEDPPISCORE));
            }
        Test.stopTest();
    }

    /**
     *    Auxiliary method to test scoring, passing the section type as parameter
     *    @param sectionType Type of the section to create
     */
    static void testScoringSimple(String sectionType){
        Survey__c survey1 = newSurvey('FirstSurvey');
        Question__c question1 = newQuestion(survey1.Id, 'Name', 'Caption1', sectionType);
        Option__c option1 = newOption(question1.Id, 'NameOption', 1);
        setPPILicenseSetting(false);

        ApexPages.StandardController stdController = new ApexPages.StandardController(survey1);
        SurveyScoringController controller = new SurveyScoringController(stdController);
        String questionString = controller.getQuestions();
        String lGroupsString = controller.getListGroups();
        String lScoresValues = controller.getListScoreValues();

        controller.scoringGroupStr = '[{"caption":"ScoringGroup1"}]';
        // The following json is an array that includes one object(ScoreValue), with the following attributes: option.Id, GroupScore name, and Value.
        // Given this data I'll try to insert it in the database.
        controller.scoringValuesJson  = '[{"optionId":"' + option1.Id + '","groupName":"ScoringGroup1","value":"1"}]';
        controller.continueAfterwards = 'true';
        controller.saveScoring();
        ScoringGroup__c myGroup = [select Id, Caption__c from ScoringGroup__c where Caption__c = 'ScoringGroup1'][0];
        ScoreValue__c myScoreValue = [select Id, Value__c, ScoringGroup__c from ScoreValue__c where ScoringGroup__c = :myGroup.Id][0];
        // After this I'll compare the harcoded value (from the json array) with the retrieved value.
        System.assertEquals(1, myScoreValue.Value__c);
    }

    /**
     * Utility Methods. TODO - Move to SoC architecture
     */

    private static void setPPILicenseSetting(Boolean value){
        LicenseSettings__c l = C.getLicense();
        l.PPI_Editable__c = value;
        l.UsePPI__c = true;
        l.Can_Distribute__c = value;
        update l;
    }

    static Survey__c newSurvey(String surveyName){
        Survey__c v = new Survey__c(Status__c = SurveyDO.STATUS_DRAFT, Name = surveyName);
        insert v;
        return v;
    }
    static Question__c newQuestion(Id surveyId, String name, String caption, String type){
        Question__c q = new Question__c(Name = name, Survey__c = surveyId, Caption__c = caption, Type__c = type);
        insert q;
        return q;
    }
    static Option__c newOption(Id questionId, String name, Integer position){
        Option__c o = new Option__c(Name = name, Position__c = position, Question__c = questionId);
        insert o;
        return o;
    }
    static ScoringGroup__c newScoringGroup(String caption, Id surveyId){
        ScoringGroup__c sg = new ScoringGroup__c (Caption__c = caption, Survey__c = surveyId);
        insert sg;
        return sg;
    }
    static ScoreValue__c newScoreValue(Decimal val, Id groupId, Id optionId){
        ScoreValue__c sv = new ScoreValue__c(Value__c = val, ScoringGroup__c = groupId, Option__c = optionId);
        insert sv;
        return sv;
    }
}