src/objects/ISO_Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>The alpha-2 country codes and the short country names from ISO 3166-1</description>
    <fields>
        <fullName>ShortName__c</fullName>
        <description>The short country names from ISO 3166-1</description>
        <label>Short Name</label>
        <length>70</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ISO_Country</label>
</CustomObject>

src/objects/Language__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>List of languages to select</description>
    <fields>
        <fullName>ShortLanguageName__c</fullName>
        <defaultValue>&apos;English&apos;</defaultValue>
        <label>ShortLanguageName</label>
        <length>70</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Language</label>
</CustomObject>

src/objects/LicenseSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>To block or enable functionality in the client package . Indicates whether a function is enable or if there is a limit to use it.</description>
    <fields>
        <fullName>PPI_Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PPI_Editable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UsePPI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UsePPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UseTemplates__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UseTemplates</label>
        <type>Checkbox</type>
    </fields>
    <label>LicenseSettings</label>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PpiResultsField__c</fullName>
        <label>PPI Result Field</label>
        <picklist>
            <picklistValues>
                <fullName>ClientId__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gender__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Age__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HouseholdSize__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JoinedDate__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geolocation__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerOne__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerTwo__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerThree__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerFour__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerFive__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerSix__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerSeven__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerEight__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerNine__c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AnswerTen__c</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RemoteId__c</fullName>
        <description>The Id of Question as it is in the org that the survey was downloaded from</description>
        <externalId>true</externalId>
        <label>Remote Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SurveyLibrary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Survey Library that the Question was downloaded from</description>
        <label>Remote Library</label>
        <referenceTo>SurveyLibrary__c</referenceTo>
        <relationshipLabel>Question</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>repeat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-short</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-long</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-decimal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-datetime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>static-content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>end_of_survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>barcode</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>gps-location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>picture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-select</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-level</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>CountryCode__c</fullName>
        <description>The ISO 3166-1 alpha-2 country code</description>
        <label>Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the survey is a PPI Survey</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this survey is actually a template. If this is checked then this survey cannot be distributed on its own. It must be included into another survey</description>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LanguageCode__c</fullName>
        <defaultValue>&apos;EN&apos;</defaultValue>
        <label>Language Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PPIDataYear__c</fullName>
        <description>Data year for the PPI survey</description>
        <label>Data Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RemoteId__c</fullName>
        <description>The Id of Survey as it is in the org that the survey was downloaded from</description>
        <externalId>true</externalId>
        <label>Remote Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SurveyLibrary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The survey library that the survey was downloaded from. Allows easy update</description>
        <label>Survey Library</label>
        <referenceTo>SurveyLibrary__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyLibrary__c.object
<CustomObject>
    <description>Stores the connection details for a library on another server that this org can download surveys from</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Information about the library</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the remote library allows downloads of PPI Templates</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this library allows downloads of templates</description>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <label>Survey Library</label>
    <nameField>
        <label>Survey Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deprecated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyVersions</relationshipLabel>
        <relationshipName>SurveyVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TemplateManagerTest.cls
/*
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 */
@isTest
public class TemplateManagerTest {

    static Question__c newQuestion(
            Survey__c survey,
            Question__c parent,
            String type,
            String name,
            String caption,
            Integer position
    ) {
        return new Question__c(
            Survey__c = survey.Id,
            Parent__c = (parent != null ? parent.Id : null),
            Type__c = type,
            Name = name,
            Caption__c = caption,
            Position__c = position
        );
    }

    /**
     * Test getting the new templates
     * Test getting a new ppi template from grameen
     */
    static testMethod void testNewGetPPI() {

        PageReference templateManager = Page.TemplateManager;
        templateManager.getParameters().put(C.TEMPLATE_ACTION, C.GET_PPI_ACTION);
        Test.setCurrentPageReference(templateManager);

        Test.startTest();
        TemplateManagerController controller =
            new TemplateManagerController(new ApexPages.StandardController(new Survey__c()));
        PageReference newPage = controller.newTemplate();
        String expectedUrl = newPage.getUrl().subString(0, newPage.getUrl().indexOf('?'));
        Test.stopTest();
        System.assertEquals(expectedUrl, Page.RemoteSurveyList.getUrl());
        System.assertEquals(newPage.getParameters().get(C.LIBRARY_NAME), C.GRAMEEN_LIBRARY);
        System.assertEquals(newPage.getParameters().get(C.FORM_TYPE), C.FORM_TYPE_PPI);
    }

    /**
     * Test downloading a new template
     */
    static testMethod void  testDownloadTemplate() {

        String libraryName = 'Lobster';
        PageReference templateManager = Page.TemplateManager;
        templateManager.getParameters().put(C.TEMPLATE_ACTION, C.DOWNLOAD_ACTION);
        templateManager.getParameters().put(C.LIBRARY_NAME, libraryName);
        Test.setCurrentPageReference(templateManager);

        Test.startTest();
        TemplateManagerController controller =
            new TemplateManagerController(new ApexPages.StandardController(new Survey__c()));
        PageReference newPage = controller.newTemplate();
        String expectedUrl = newPage.getUrl().subString(0, newPage.getUrl().indexOf('?'));
        Test.stopTest();
        System.assertEquals(expectedUrl, Page.RemoteSurveyList.getUrl());
        System.assertEquals(newPage.getParameters().get(C.LIBRARY_NAME), libraryName);
        System.assertEquals(newPage.getParameters().get(C.FORM_TYPE), C.FORM_TYPE_TEMP);
    }

    /**
     * Test creating a new template
     */
    static testMethod void testNewTemplate() {

        PageReference templateManager = Page.TemplateManager;
        templateManager.getParameters().put(C.TEMPLATE_ACTION, C.CREATE_NEW_TEMPLATE);
        Test.setCurrentPageReference(templateManager);

        Test.startTest();
        TemplateManagerController controller =
            new TemplateManagerController(new ApexPages.StandardController(new Survey__c()));
        PageReference newPage = controller.newTemplate();
        String expectedUrl = newPage.getUrl().subString(0, newPage.getUrl().indexOf('?'));
        Test.stopTest();
        System.assertEquals(expectedUrl, Page.SurveySetting.getUrl());
        System.assertEquals(newPage.getParameters().get(C.START_FORM), C.CREATE_NEW_TEMPLATE);
    }

    /**
     * Test a non-existing action
     */
    static testMethod void testWrongAction() {

        PageReference templateManager = Page.TemplateManager;
        templateManager.getParameters().put(C.TEMPLATE_ACTION, 'Great');
        Test.setCurrentPageReference(templateManager);

        Test.startTest();
        TemplateManagerController controller =
            new TemplateManagerController(new ApexPages.StandardController(new Survey__c()));
        PageReference newPage = controller.newTemplate();
        Test.stopTest();
        System.assertEquals(newPage, null);
    }

    /**
     * Test use it
     */
    static testMethod void testUseIt() {

        PageReference templateManager = Page.TemplateManager;

        Survey__c survey = SurveyDOTest.createPpiTemplate();
        survey.Version__c = 2;
        survey.RemoteId__c = null;
        insert survey;
        TestSurveyData testSurvey = TestSurveyData.createSamplePPITemplateQuestions(survey);
        templateManager.getParameters().put(C.BASE_TEMPLATES, testSurvey.testSurvey.Id);
        Test.setCurrentPageReference(templateManager);

        Test.startTest();
        TemplateManagerController controller =
            new TemplateManagerController(new ApexPages.StandardController(new Survey__c()));
        PageReference newPage = controller.useIt();
        String expectedUrl = newPage.getUrl().subString(0, newPage.getUrl().indexOf('?'));
        Test.stopTest();
        System.assertEquals(expectedUrl, Page.SurveySetting.getUrl());
        System.assertEquals(newPage.getParameters().get(C.START_FORM), C.CREATE_FROM_TEMPLATE);
        System.assertEquals(newPage.getParameters().get(C.BASE_TEMPLATES), testSurvey.testSurvey.Id);
        QuestionDo questionDomain = new QuestionDo();
        assertQuestionPPIResults(testSurvey.testSurvey, questionDomain);
    }

    /**
     * Test Distribute
     */
    static testMethod void testDistribute() {
        Survey__c survey = SurveyDOTest.createPpiTemplate();
        survey.Version__c = 2;
        survey.RemoteId__c = null;
        insert survey;
        TestSurveyData testSurvey = TestSurveyData.createSamplePPITemplateQuestions(survey);
        PageReference templateManager = Page.TemplateManager;
        templateManager.getParameters().put(C.BASE_TEMPLATES, testSurvey.testSurvey.Id);
        Test.setCurrentPageReference(templateManager);
        Test.startTest();
        TemplateManagerController controller =
            new TemplateManagerController(new ApexPages.StandardController(new Survey__c()));
        PageReference newPage = controller.distributeIt();
        Test.stopTest();
        QuestionDo questionDomain = new QuestionDo();
        assertQuestionPPIResults(testSurvey.testSurvey, questionDomain);
    }

    /**
     * Test edit it
     */
    static testMethod void testEditIt() {

        PageReference templateManager = Page.TemplateManager;
        templateManager.getParameters().put(C.BASE_TEMPLATES, 'North');
        Test.setCurrentPageReference(templateManager);

        Test.startTest();
        TemplateManagerController controller =
            new TemplateManagerController(new ApexPages.StandardController(new Survey__c()));
        PageReference newPage = controller.editIt();
        String expectedUrl = newPage.getUrl().subString(0, newPage.getUrl().indexOf('?'));
        Test.stopTest();
        System.assertEquals(expectedUrl, Page.SurveySetting.getUrl());
        System.assertEquals(newPage.getParameters().get(C.START_FORM), C.EDIT_TEMPLATE);
        System.assertEquals(newPage.getParameters().get('id'), 'North');
    }

    /**
     * Test delete it
     */
    static testMethod void testDeleteIt() {

        List<Survey__c> surveys = new List<Survey__c>();
        Survey__c s1 = new Survey__c(
            Name = 'Test Template',
            Description__c  = 'This is a description & % <',
            Version__c = 1.0
        );
        surveys.add(s1);
        Database.insert(surveys);

        // Add Questions, Skip Logic, etc
        Question__c q1 = newQuestion(s1, null, 'section', 'q1', 'Caption1', 1);
        Database.insert(q1);
        Question__c q2 = newQuestion(s1, q1, 'text', 'q2', 'Caption2', 2);
        Database.insert(q2);

        PageReference templateManager = Page.TemplateManager;
        templateManager.getParameters().put(C.BASE_TEMPLATES, s1.id);
        Test.setCurrentPageReference(templateManager);

        Test.startTest();
        TemplateManagerController controller =
            new TemplateManagerController(new ApexPages.StandardController(new Survey__c()));
        controller.surveyIdToDelete = s1.id;
        controller.deleteIt();
        Test.stopTest();
        Survey__c[] deletedSurveys = [SELECT Id FROM Survey__c WHERE id = :s1.Id];
        System.assert(deletedSurveys.isEmpty());
    }

    /**
     * Test filter display
     */
    static testMethod void testFilter() {

        // Add license to insert new survey
        LicenseSettings__c license = C.getLicense();
        license.PPI_Editable__c = true;
        license.UsePPI__c = true;
        license.UseTemplates__c = true;
        update license;

        // Create a country code and a language
        Database.insert(new Language__c( Name='JJ', ShortLanguageName__c = 'TEST' ));
        Database.insert(new ISO_Country__c( Name='JJ', ShortName__c = 'TEST' ));

        List<Survey__c> surveys = new List<Survey__c>();
        Survey__c s1 = new Survey__c(
            Name = 'Test Filter 1',
            Description__c  = 'This is a description & % <',
            Version__c = 1.0,
            PPIDataYear__c = 2012,
            CountryCode__c = 'JJ',
            LanguageCode__c = 'JJ',
            IsPPI__c = true,
            IsTemplate__c = true
        );
        surveys.add(s1);
        Survey__c s2= new Survey__c(
            Name = 'Test Filter 2',
            Description__c  = 'This is a description & % <',
            Version__c = 1.0,
            IsTemplate__c = true
        );
        surveys.add(s2);
        Database.insert(surveys);

        PageReference templateManager = Page.TemplateManager;
        Test.setCurrentPageReference(templateManager);
        Test.startTest();
        TemplateManagerController controller =
            new TemplateManagerController(new ApexPages.StandardController(new Survey__c()));

        // Test set up
        System.assertEquals(controller.getTemplates().size(), 2);

        // Test get template only
        templateManager.getParameters().put(C.LIBRARY_NAME, 'default');
        templateManager.getParameters().put('showPpi', 'false');
        templateManager.getParameters().put('showAll', 'false');
        controller.filterDisplay();
        System.assertEquals(controller.getTemplates().size(), 1);

        // Test get PPPI only
        templateManager.getParameters().put('showPpi', 'true');
        templateManager.getParameters().put('showAll', 'false');
        controller.filterDisplay();
        System.assertEquals(controller.getTemplates().size(), 1);

        // Test get all
        templateManager.getParameters().put('showPpi', 'true');
        templateManager.getParameters().put('showAll', 'true');
        controller.filterDisplay();
        System.assertEquals(controller.getTemplates().size(), 2);
        Test.stopTest();
    }

    /**
     * Test method to verify fetching of SurveyVersion records with status not equal to Deprecated
     */
    static testMethod void testFetchingOfSurveyVersionRecords() {

        // Create survey with Status Draft
        Survey__c surveyWithStatusDraft = SurveyDOTest.createInsertedPpiTemplate();
        System.assert(surveyWithStatusDraft != null, 'Survey record could not be created.');

        // Create survey with Status Deprecated
        Survey__c surveyWithStatusDeprecated = SurveyDOTest.createInsertedPpiTemplate();
        System.assert(surveyWithStatusDeprecated != null, 'Survey record could not be created.');

        List<SurveyVersion__c> surveyVersionRecords =
            new SurveyVersionSelector().getAllWithSurveyIds(
                new Set<String> {surveyWithStatusDeprecated.Id}
            ); 
        System.assert(
            surveyVersionRecords.size() == 1,
            'SurveyVersion records could not be fetched.'
        );

        surveyVersionRecords[0].Status__c = SurveyDO.STATUS_DEPRECATED;
        SurveyVersionDomain surveyVersionDomain = new SurveyVersionDomain();
        surveyVersionDomain.addRecords(surveyVersionRecords);
        surveyVersionDomain.updateRecords();

        System.assert(surveyVersionDomain.records.size() == 1);
        System.assert(surveyVersionDomain.records[0].Id != null);

        List<Survey__c> surveyRecord =
            (List<Survey__c>) new SurveySelector().getRecordsById(
                new Set<Id> {surveyWithStatusDeprecated.Id}
            );
        System.assert(surveyRecord.size() == 1, 'Survey record could not be fetched properly.');
        System.assertEquals(SurveyDO.STATUS_DEPRECATED, surveyRecord[0].Status__c);

        // Create a SurveyLibrary with Name other than 'Default', 'myLib' and 
        // assign it to both surveys
        SurveyLibrary__c surveyLibrary = SurveyLibraryDomainTest.addLibraryToDatabase();
        System.assert(surveyLibrary != null, 'SurveyLibrary record could not be created.');

        surveyWithStatusDraft.SurveyLibrary__c = surveyLibrary.Id;
        surveyWithStatusDeprecated.SurveyLibrary__c = surveyLibrary.Id;
        SurveyDO surveyDomain = new SurveyDO();
        surveyDomain.addRecords(
            new List<Survey__c> {surveyWithStatusDraft, surveyWithStatusDeprecated}
        );
        surveyDomain.updateRecords();

        List<Survey__c> surveyRecords =
            (List<Survey__c>) new SurveySelector().getRecordsById(
                new Set<Id> {surveyWithStatusDraft.Id, surveyWithStatusDeprecated.Id}
            );
        System.assert(surveyRecords.size() == 2, 'Survey record could not be fetched properly.');
        System.assert(surveyRecords[0].SurveyLibrary__c != null);
        System.assert(surveyRecords[1].SurveyLibrary__c != null);

        Test.startTest();
        TemplateManagerController controller =
            new TemplateManagerController(new ApexPages.StandardController(new Survey__c()));
        controller.setUpPagination(true);
        Test.stopTest();

        System.assert(controller.paginator != null, 'Records are not assigned properly.');
        List<SurveyVersion__c> surveyVersionList =
            (List<SurveyVersion__c>) controller.paginator.getRecords();
        System.assert(
            surveyVersionList.size() == 1,
            'Survey Version records could not be fetched.'
        );
        System.assert(surveyVersionList[0].Survey__r.Status__c != SurveyDO.STATUS_DEPRECATED);
    }

    /**
     * Method to verify asserts for all Questions that have their PPIResults field populated
     */
    public static void assertQuestionPPIResults(Survey__c testSurvey, QuestionDo questionDomain) {
        // Prepare for values so that we can provide proper system asserts.
        String namespace = C.getClassNameSpace(QuestionDO.class.getName());
        namespace = (namespace == null) ? '' : namespace + '__';
        List<Schema.PicklistEntry> picklistValuesPPIResults =
            DescribeHandler.getFieldPicklist(questionDomain.sObjectName, namespace + 'PpiResultsField__c');
        QuestionSelector selector = new QuestionSelector();
        Integer recordCount = 0;
        for (Question__c questionInstance : selector.getAllForPpiSurveyId(testSurvey.Id)) {
            if (questionInstance.get(namespace + 'Parent__c') != null) {
                System.assertEquals(
                    picklistValuesPPIResults[recordCount].getValue(),
                    String.valueOf(questionInstance.get(namespace + 'PpiResultsField__c')),
                    'Field API and PPIResults field value does not match'
                );
                recordCount++;
            }
        }
    }
}