src/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Assigned__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field Officer that completed the job activity.</description>
        <label>Staff</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Activities</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact for whom the job activity was completed (would be Interviewee for a survey).</description>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs of Client</relationshipLabel>
        <relationshipName>JobAsInterviewee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date and time when the job activity was completed.</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>JobTemplate__c</fullName>
        <description>Job for this Job Activity</description>
        <label>Job</label>
        <referenceTo>JobTemplate__c</referenceTo>
        <relationshipLabel>Job Activities</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date and time when the job activity was started.</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Job Activity</label>
    <nameField>
        <label>Job Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JobTemplate__c.object
<CustomObject>
    <description>Job</description>
    <fields>
        <fullName>Hierarchy__c</fullName>
        <description>Contains information about hierarchy in JSON format</description>
        <label>Hierarchy</label>
        <length>16000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Defines if the Job can be downloaded to the phone. Closed jobs will be removed from mobile phones, but submissions of completed jobs are still possible.</description>
        <inlineHelpText>If Job is published its content cannot be edited. Only admits to change to Closed.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    -</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deprecated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyVersions</relationshipLabel>
        <relationshipName>SurveyVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date and time when the task was completed.</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date and time when the task was started.</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TaskTemplate__c</fullName>
        <label>Task</label>
        <referenceTo>TaskTemplate__c</referenceTo>
        <relationshipLabel>Task Activities</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task Activity</label>
    <nameField>
        <label>Task Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TaskTemplate__c.object
<CustomObject>
    <description>Templates for Task contained into Jobs.</description>
    <fields>
        <fullName>JobTemplate__c</fullName>
        <description>Id of the job that contains this task</description>
        <inlineHelpText>Select the Job this task belongs to.</inlineHelpText>
        <label>Job</label>
        <referenceTo>JobTemplate__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Task_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/JobActivitiesListControllerTest.cls
/**
*   Grameen: Salesforce - SF Field Force, SF - Jobs
*   Test for the controller of JobActivitiesList.
*   (c) Copyright 2013 Grameen Foundation USA. All rights reserved
*
*   @author Sebastian Piazza
*   @author Claudio Soto csoto@altimetrik.com
*/
@isTest
private class JobActivitiesListControllerTest {

     /**
     * Test method to verify loadObjectSelectList method is working correctly
     * must create a json object and then serialize it to a json string
     * this json object stores all the information from the objects from the org
     **/
    static testmethod  void getJobActivitiesTest(){

        // Create contact...
        Contact newContact  = new Contact();
        newContact.LastName = 'Last Name';
        insert newContact;

        // Create JobTemplate...
        JobTemplate__c newJobTemplate = new JobTemplate__c(Name = 'NameJobTemplate',
                                                        Status__c = JobTemplateDO.STATUS_DRAFT,
                                                        Hierarchy__c = '[]');
        insert newJobTemplate;

        // Job template with empty values...
        Job__c emptyJob         = new Job__c();
        emptyJob.Name           = 'emptyJob';
        emptyJob.Assigned__c    = newContact.Id;
        emptyJob.Contact__c     = newContact.Id;
        emptyJob.JobTemplate__c = newJobTemplate.Id;
        emptyJob.StartDate__c   = null;
        emptyJob.EndDate__c     = null;
        insert emptyJob;

        List<JobActivitiesListController.JobActivity>  listActivities = (List <JobActivitiesListController.JobActivity>) JobActivitiesListController.getJobActivities();

        system.assertEquals( JobActivitiesListController.UNDEFINED_VALUE, listActivities[0].Started );
        system.assertEquals( JobActivitiesListController.UNDEFINED_VALUE, listActivities[0].Finished );

        Job__c irrelevantJob         = new Job__c();
        irrelevantJob.Name           = 'irrelevantJob';
        irrelevantJob.Assigned__c    = newContact.Id;
        irrelevantJob.Contact__c     = newContact.Id;
        irrelevantJob.JobTemplate__c = newJobTemplate.Id;
        irrelevantJob.StartDate__c   = null;
        irrelevantJob.EndDate__c     = null;
        insert irrelevantJob;

        Job__c newJob         = new Job__c();
        newJob.Name           = 'nameJob';
        newJob.Assigned__c    = newContact.Id;
        newJob.Contact__c     = newContact.Id;
        newJob.JobTemplate__c = newJobTemplate.Id;
        newJob.StartDate__c   = Datetime.now();
        newJob.EndDate__c     = Datetime.now();
        insert newJob;

        Test.startTest();
            // Obtain the list of JobActivity from that variable.
            listActivities = JobActivitiesListController.getJobActivities();
        Test.stopTest();
        // Assert that three Job activities were created.
        system.assertEquals ( 3, listActivities.size() );

        // Obtain the last created JobActivity.
        JobActivitiesListController.JobActivity lastJobActivity;
        for(JobActivitiesListController.JobActivity jobAct : listActivities){
            if(jobAct.id == newJob.Id){
                lastJobActivity = jobAct;
            }
        }

        // And assert data of recently created Job.
        system.assertEquals ( newContact.Id, lastJobActivity.ClientId );
        system.assertEquals ( newContact.Id, lastJobActivity.StaffId );
        system.assertEquals ( newJobTemplate.Id, lastJobActivity.JobTemplateId );
        system.assertEquals ( newJob.StartDate__c.format('MM/dd/yyyy HH:mm'), lastJobActivity.Started);
        system.assertEquals ( newJob.EndDate__c.format('MM/dd/yyyy HH:mm'), lastJobActivity.Finished);
    }

    /**
     *  Test method for obtainMapTaskJobs method.
     */
    static testmethod void obtainMapTaskJobsTest(){

        // Set data...

        // Set survey data.
        Survey__c survey = TestUtils.createSurvey('Survey 1');

        SurveyVersion__c surveyVersion =[SELECT id FROM SurveyVersion__c WHERE Survey__c = :survey.id];

        // Create contact...
        Contact newContact = TestUtils.createContact('Last Name');

        // Create JobTemplate...
        JobTemplate__c newJobTemplate =
            JobTemplateDO.createJobTemplate('NameJobTemplate', JobTemplateDO.STATUS_DRAFT, '[]');
        insert newJobTemplate;

        // Create two tasks for that job template.
        TaskTemplate__c firstTask =
            TaskTemplateDO.createTaskTemplate(
                'Task 1', 1 , newJobTemplate.Id, TaskTemplateDO.TYPE_FORM, surveyVersion.Id
            );
        TaskTemplate__c secondTask =
            TaskTemplateDO.createTaskTemplate(
                'Task 2', 2 , newJobTemplate.Id, TaskTemplateDO.TYPE_FORM, surveyVersion.Id
            );
        insert new List<TaskTemplate__c>{firstTask, secondTask};

        // Create job activities.
        Job__c jobActivity =
            TestUtils.createJobActivity(
                'Job activity 1',
                newJobTemplate.Id,
                newContact.Id,
                newContact.Id,
                Datetime.now(),
                Datetime.now()
            );
        Job__c anotherJobActivity =
            TestUtils.createJobActivity(
                'Job activity 2',
                newJobTemplate.Id,
                newContact.Id,
                newContact.Id,
                Datetime.now(),
                Datetime.now()
            );
        Job__c yetAnotherJobActivity =
            TestUtils.createJobActivity(
                'Job activity 3',
                newJobTemplate.Id,
                newContact.Id,
                newContact.Id,
                Datetime.now(),
                Datetime.now()
            );

        // Create tasks activities (here is related Job__c and TaskTemplate__c).
        Task__c taskActivity =
            TestUtils.createTaskActivity(
                jobActivity.Id, Datetime.now(), Datetime.now(), firstTask.Id
            );
        Task__c secondTaskActivity =
            TestUtils.createTaskActivity(
                anotherJobActivity.Id, Datetime.now(), Datetime.now(), firstTask.Id
            );
        Task__c thirdTaskActivity =
            TestUtils.createTaskActivity(
                yetAnotherJobActivity.Id, Datetime.now(), Datetime.now(), secondTask.Id
            );

        JobActivitiesListController controller  = new JobActivitiesListController();
        Map<Id, Set<Id>> mapTasksJobs = controller.obtainMapTaskJobs();

        // Expected map:
        // firstTask  => [jobActivity.Id, anotherJobActivity.Id]
        // secondTask => [yetAnotherJobActivity.Id]
        Set<Id> jobsRelatedToFirstTask  = mapTasksJobs.get(firstTask.Id);

        // Contains jobActivity Id...
        system.assert( jobsRelatedToFirstTask.contains(jobActivity.Id), 'Should contain jobActivity Id...' );
        // Contains anotherJobActivity Id...
        system.assert( jobsRelatedToFirstTask.contains(anotherJobActivity.Id), 'Should anotherJobActivity Id...' );
        // Doesn't contains yetAnotherJobActivity Id.
        system.assert( !jobsRelatedToFirstTask.contains(yetAnotherJobActivity.Id), 'Should not contain yetAnotherJobActivity Id...');

        Set<Id> jobsRelatedToSecondTask = mapTasksJobs.get(secondTask.Id);
        // Contains yetAnotherJobActivity Id...
        system.assert( jobsRelatedToSecondTask.contains(yetAnotherJobActivity.Id), 'Should contain yetAnotherJobActivity Id...');
        // Doesn't contains jobActivity Id.
        system.assert( !jobsRelatedToSecondTask.contains(jobActivity.Id), 'Should not contain jobActivity Id...' );
        // Doesn't contains anotherJobActivity Id.
        system.assert( !jobsRelatedToSecondTask.contains(anotherJobActivity.Id), 'Should not contain anotherJobActivity Id...' );

    }
}