src/objects/JobTemplate__c.object
<CustomObject>
    <description>Job</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    -</CustomObject>

src/objects/TaskTemplate__c.object
<CustomObject>
    <description>Templates for Task contained into Jobs.</description>
    <fields>
        <fullName>JobTemplate__c</fullName>
        <description>Id of the job that contains this task</description>
        <inlineHelpText>Select the Job this task belongs to.</inlineHelpText>
        <label>Job</label>
        <referenceTo>JobTemplate__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Task_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DeleteResourceTest.cls
/*
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved.
 *
 * Test class for DeleteResource.trigger.
 */
@isTest
private class DeleteResourceTest {

    /**
     *  Method in charge of test that user cannot deleted a resource used in a task.
     */
    static testMethod void deleteResourceTriggerTest() {

        // Create a job template
        JobTemplate__c jobTemplate = JobTemplateDO.createJobTemplate('JobName', 'Draft', '[]');
        insert jobTemplate;

        // Create a version, so the ContentDocument will be automatically created.
        ContentVersion version = new ContentVersion(
            Title = 'title1',
            VersionData = Blob.valueof('aaa324'),
            PathOnClient = 'fileName.mp4'
        );
        insert version;

        // Obtain the created ContentDocument.
        ContentDocument cd = [SELECT Id From ContentDocument][0];

        // Create the task, and link it to the created ContentDocument.
        TaskTemplate__c taskResource =
            TaskTemplateDO.createResourceTaskTemplate(
                'TaskName',
                1,
                jobTemplate.Id,
                'instructions',
                'j8ji',
                cd.Id
            );
        insert taskResource;

        try {
            delete cd;
            System.assert(false);
        } catch (Exception e) {
            System.assert(
                e.getMessage().contains(System.Label.RESOURCE_CANT_BE_REMOVED_REFERENCED_BY_TASK),
                'Was triggered, but there was no error on the Document'
            );
        }
    }
}