src/objects/JobTemplate__c.object
<CustomObject>
    <description>Job</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    -</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TaskTemplate__c.object
<CustomObject>
    <description>Templates for Task contained into Jobs.</description>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the survey that will be filled in this task</description>
        <inlineHelpText>Associate a Survey to this task.</inlineHelpText>
        <label>Survey</label>
        <referenceTo>SurveyVersion__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Task_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JobTemplate__c</fullName>
        <description>Id of the job that contains this task</description>
        <inlineHelpText>Select the Job this task belongs to.</inlineHelpText>
        <label>Job</label>
        <referenceTo>JobTemplate__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Task_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Position of this task inside its job (defines order)</description>
        <inlineHelpText>Order Position for tasks list.</inlineHelpText>
        <label>Position</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of task (data-view, list-view, form)</description>
        <inlineHelpText>Select a Type of Task.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>data-view</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>list-view</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>form</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TaskTemplateDOTest.cls
/**
 * Test class for the TaskTemplateDO
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author Aditi Satpute
 */
@isTest
public with sharing class TaskTemplateDOTest {

    /**
     * Create Task Template record
     */
    public static TaskTemplate__c createRecord(
            String name,
            JobTemplate__c job,
            String taskType,
            SurveyVersion__c version,
            Integer position
    ) {
        return new TaskTemplate__c(
            Name = name,
            JobTemplate__c = job.Id,
            Type__c = taskType,
            Form__c = version.Id,
            Position__c = position
        );
    }
}