src/objects/JobTemplate__c.object
<CustomObject>
    <description>Job</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Defines if the Job can be downloaded to the phone. Closed jobs will be removed from mobile phones, but submissions of completed jobs are still possible.</description>
        <inlineHelpText>If Job is published its content cannot be edited. Only admits to change to Closed.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    -</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deprecated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyVersions</relationshipLabel>
        <relationshipName>SurveyVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TaskTemplate__c.object
<CustomObject>
    <description>Templates for Task contained into Jobs.</description>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the survey that will be filled in this task</description>
        <inlineHelpText>Associate a Survey to this task.</inlineHelpText>
        <label>Survey</label>
        <referenceTo>SurveyVersion__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Task_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JobTemplate__c</fullName>
        <description>Id of the job that contains this task</description>
        <inlineHelpText>Select the Job this task belongs to.</inlineHelpText>
        <label>Job</label>
        <referenceTo>JobTemplate__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Task_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Position of this task inside its job (defines order)</description>
        <inlineHelpText>Order Position for tasks list.</inlineHelpText>
        <label>Position</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of task (data-view, list-view, form)</description>
        <inlineHelpText>Select a Type of Task.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>data-view</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>list-view</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>form</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdateSurveyOnLastVersionUpdateTest.cls
/*
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 */
@isTest
private class UpdateSurveyOnLastVersionUpdateTest {

    static testMethod void testSurveyUpdateOnLastVersionUpdate() {

        // Create a new Survey
        Survey__c survey = new Survey__c(Name='survey');
        insert survey;
        //refresh survey
        survey = [SELECT Name,Status__c,Version__c FROM Survey__c WHERE Id = :survey.Id];
        SurveyVersion__c version = [SELECT Version__c,Status__c,Name FROM SurveyVersion__c WHERE Survey__r.Id = :survey.Id];
        
        Test.startTest();
            version.Status__c = SurveyDO.STATUS_PUBLISHED;
            update version;

            //the survey would have to be updated
            //refresh survey
            survey = [SELECT Name,Status__c,Version__c FROM Survey__c WHERE Id = :survey.Id];
            system.assertEquals(SurveyDO.STATUS_PUBLISHED, survey.Status__c);
            //get the last version and try to update it FROM any status to draft,it should fail
            version = [SELECT Status__c FROM SurveyVersion__c WHERE Survey__c= :survey.Id order by Version__c desc];
            try{
                version.Status__c = SurveyDO.STATUS_DRAFT;
                update version;
                system.assert(false);
            }
            catch (Exception e){
                system.assert(true);
            }
        Test.stopTest();
    }

    static testMethod void testSurveyStatusUpdates() {
        Survey__c survey = new Survey__c(Name='survey'); insert survey;

        // Test change status FROM Draft to Published
        SurveyVersion__c version = [SELECT Version__c,Status__c,Name FROM SurveyVersion__c WHERE Survey__r.Id = :survey.Id];
        Test.startTest();
            version.Status__c = SurveyDO.STATUS_PUBLISHED; update version;
            system.assertEquals(SurveyDO.STATUS_PUBLISHED, [SELECT Status__c FROM Survey__c WHERE Id = :survey.Id].Status__c);

            // Test change status FROM Published to Closed
            version = [SELECT Version__c,Status__c,Name FROM SurveyVersion__c WHERE Survey__r.Id = :survey.Id];
            version.Status__c = SurveyDO.STATUS_CLOSED; update version;
            system.assertEquals(SurveyDO.STATUS_CLOSED, [SELECT Status__c FROM Survey__c WHERE Id = :survey.Id].Status__c);

            // Test change status FROM Draft to Closed
            Survey__c closeableSurvey = new Survey__c(Name='closeable survey'); insert closeableSurvey;

            version = [SELECT Version__c,Status__c,Name FROM SurveyVersion__c WHERE Survey__r.Id = :closeableSurvey.Id];
            version.Status__c = SurveyDO.STATUS_CLOSED; update version;
            system.assertEquals(SurveyDO.STATUS_CLOSED, [SELECT Status__c FROM Survey__c WHERE Id = :closeableSurvey.Id].Status__c);

            // Test change status FROM Draft to Closed with open job
            Survey__c nonCloseableSurvey = new Survey__c (Name = 'non-closeable survey'); insert nonCloseableSurvey;
            SurveyVersion__C versionNonCloseable = [SELECT Version__c,Status__c,Name FROM SurveyVersion__c WHERE Survey__r.Id = :nonCloseableSurvey.Id];
            JobTemplate__c job           = new JobTemplate__c (Name = 'open job',
                                                               Status__c = JobTemplateDO.STATUS_DRAFT); insert job;
            TaskTemplate__c firstTask    = new TaskTemplate__c (Form__c = versionNonCloseable.Id,
                                                                JobTemplate__c = job.Id,
                                                                Position__c = 1,
                                                                Type__c = 'form');insert firstTask;
            version = [SELECT Version__c, Status__c, Name FROM SurveyVersion__c WHERE Survey__r.Id = :nonCloseableSurvey.Id];
            version.Status__c = SurveyDO.STATUS_CLOSED;
            try{
                update version;
                system.assert(false, 'This should fail since is not possible to change the status ' +
                                     'of a survey to closed with a non closed job related');
            }catch(DMLException e){
                system.assert(e.getMessage().contains(system.Label.SURVEYVERSION_ERR_CLOSEWITHOPENJOBS));
            }

            System.assertEquals(SurveyDO.STATUS_DRAFT, [SELECT Status__c FROM SurveyVersion__c WHERE Survey__r.Id = :nonCloseableSurvey.Id].Status__c);

            // Test change status FROM Draft to Closed with closed job
            Survey__c withClosedJobSurvey = new Survey__c (Name = 'With Closed Job Survey'); insert withClosedJobSurvey;
            SurveyVersion__c versionWithClosedJobSurvey= [SELECT id FROM SurveyVersion__c Where Survey__c = :withClosedJobSurvey.Id][0];
            JobTemplate__c closedJob      = new JobTemplate__c (Name = 'closed job',
                                                                Status__c = JobTemplateDO.STATUS_DRAFT); insert closedJob;
            TaskTemplate__c secondTask    = new TaskTemplate__c (Form__c = versionWithClosedJobSurvey.Id,
                                                                 JobTemplate__c = closedJob.Id,
                                                                 Position__c = 1,
                                                                 Type__c = 'form');insert secondTask;
            closedJob.Status__c = JobTemplateDO.STATUS_CLOSED;
            update closedJob;
            version = [SELECT Version__c, Status__c, Name FROM SurveyVersion__c WHERE Survey__r.Id = :withClosedJobSurvey.Id];
            version.Status__c = SurveyDO.STATUS_CLOSED;
            update version;
        Test.stopTest();
        system.assertEquals(SurveyDO.STATUS_CLOSED, [SELECT Status__c FROM Survey__c WHERE Id = :withClosedJobSurvey.Id].Status__c);

    }
}