src/objects/JobTemplate__c.object
<CustomObject>
    <description>Job</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    -</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyVersions</relationshipLabel>
        <relationshipName>SurveyVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TaskTemplate__c.object
<CustomObject>
    <description>Templates for Task contained into Jobs.</description>
    <fields>
        <fullName>Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link to the survey that will be filled in this task</description>
        <inlineHelpText>Associate a Survey to this task.</inlineHelpText>
        <label>Survey</label>
        <referenceTo>SurveyVersion__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Task_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>JobTemplate__c</fullName>
        <description>Id of the job that contains this task</description>
        <inlineHelpText>Select the Job this task belongs to.</inlineHelpText>
        <label>Job</label>
        <referenceTo>JobTemplate__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Task_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TaskTemplateSelector.cls
/**
 * Selector class for the TaskTemplate object
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author Aditi Satpute
 */
public with sharing class TaskTemplateSelector extends SObjectSelector {
    public Schema.SObjectType getSObjectType() {
        return TaskTemplate__c.sObjectType;
    }

    public List<Schema.SObjectField> getDefaultSelectFields() {
        return new List<Schema.SObjectField> {
            TaskTemplate__c.Id,
            TaskTemplate__c.Name,
            TaskTemplate__c.Form__c,
            TaskTemplate__c.JobTemplate__c
        };
    }

    public String pathToJobFiltering() {
        return null;
    }

    /**
     * Get all TaskTemplate records for specified Survey Ids
     */
    public List<TaskTemplate__c> getAllForSurveyIds(Set<String> surveyIds) {
        this.mainQueryBuilder.addRelationshipToSelect(
            new List<Schema.SObjectField> {
                TaskTemplate__c.Form__c,
                SurveyVersion__c.Survey__c
            }
        );
        this.createSurveyWhereClause(surveyIds);
        return
            (List<TaskTemplate__c>) runSoqlQuery(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Get all TaskTemplate records
     */
    public List<TaskTemplate__c> getAllRecords() {
        this.setMainLimitAmount(Limits.getLimitQueryRows());
        return
            (List<TaskTemplate__c>) runSoqlQuery(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Method to add Survey Id to where clause
     */
    private void createSurveyWhereClause(Set<String> surveyIds) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardInWhereClause(
                this.getMainQueryBuilder().generateLookUp(
                    new List<Schema.SObjectField> {
                        TaskTemplate__c.Form__c,
                        SurveyVersion__c.Survey__c
                    }
                ),
                SObjectSelector.IN_OPERATOR,
                surveyIds
            )
        );
    }
}