src/objects/JobTemplate__c.object
<CustomObject>
    <description>Job</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Defines if the Job can be downloaded to the phone. Closed jobs will be removed from mobile phones, but submissions of completed jobs are still possible.</description>
        <inlineHelpText>If Job is published its content cannot be edited. Only admits to change to Closed.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    -</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deprecated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyVersions</relationshipLabel>
        <relationshipName>SurveyVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TaskTemplate__c.object
<CustomObject>
    <description>Templates for Task contained into Jobs.</description>
    <fields>
        <fullName>JobTemplate__c</fullName>
        <description>Id of the job that contains this task</description>
        <inlineHelpText>Select the Job this task belongs to.</inlineHelpText>
        <label>Job</label>
        <referenceTo>JobTemplate__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Task_Templates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TaskTemplateSelectorTest.cls
/**
 * Test class for the TaskTemplateSelector
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author Aditi Satpute
 */
@isTest
public with sharing class TaskTemplateSelectorTest {

    private static Survey__c survey1;
    private static Survey__c survey2;

    /**
     * Test method to verify fetching of TaskTemplate records for specified SurveyIds
     */
    static testmethod void testFetchAllForSurveyIds() {
        setUpTestData();

        Test.startTest();
        List<TaskTemplate__c> taskTemplateList =
            new TaskTemplateSelector().getAllForSurveyIds(
                new Set<String> {survey1.Id, survey2.Id}
            );

        // Only one record fetched as Survey2 doesn't have any taskTemplate records
        System.assertEquals(
            1,
            taskTemplateList.size()
        );
        Test.stopTest();
    }

    /**
     * Test method to verify fetching of all TaskTemplate records
     */
    static testmethod void testFetchAllRecords() {
        setUpTestData();

        Test.startTest();
        List<TaskTemplate__c> taskTemplateList =
            new TaskTemplateSelector().getAllRecords();
        Test.stopTest();

        System.assertEquals(
            1,
            taskTemplateList.size()
        );
    }

    /**
     * Method to set up test data for Task Template
     */
    private static void setUpTestData() {
        survey1 = SurveyDOTest.createInsertedSurvey('Survey1');
        survey2 = SurveyDOTest.createInsertedSurvey('Survey2');

        //Publish the version that will be used
        List<SurveyVersion__c> versions =
            new SurveyVersionSelector().getAllWithSurveyIds(
                new Set<String> {survey1.Id, survey2.Id}
            );
        versions[0].Status__c = SurveyDO.STATUS_PUBLISHED;
        SurveyVersionDomain surveyVersionDomainInstance =
            new SurveyVersionDomain.Constructor().constructWithRecords(versions);
        surveyVersionDomainInstance.updateRecords();

        // Set up some jobs
        JobTemplate__c job = JobTemplateDOTest.createRecord(
            'JobTemp2',
            JobTemplateDO.STATUS_DRAFT,
            'Instructions'
        );
        JobTemplateDO jobTemplateDomainInstance =
            new JobTemplateDO.Constructor().constructWithRecords(
                new List<JobTemplate__c> {job}
            );
        jobTemplateDomainInstance.insertRecords();

        TaskTemplate__c task = TaskTemplateDOTest.createRecord(
            'taskTemplate',
            job,
            TaskTemplateDO.TYPE_FORM,
            versions[0],
            1
        );
        TaskTemplateDO taskTemplateDomainInstance =
            new TaskTemplateDO.Constructor().constructWithRecords(
                new List<TaskTemplate__c> {task}
            );
        taskTemplateDomainInstance.insertRecords();
    }
}