src/objects/LicenseSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>To block or enable functionality in the client package . Indicates whether a function is enable or if there is a limit to use it.</description>
    <fields>
        <fullName>UseTemplates__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UseTemplates</label>
        <type>Checkbox</type>
    </fields>
    <label>LicenseSettings</label>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the survey is a PPI Survey</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this survey is actually a template. If this is checked then this survey cannot be distributed on its own. It must be included into another survey</description>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PpiIdentifier__c</fullName>
        <label>PPI Identifier</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SurveyLibrary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The survey library that the survey was downloaded from. Allows easy update</description>
        <label>Survey Library</label>
        <referenceTo>SurveyLibrary__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyLibrary__c.object
<CustomObject>
    <description>Stores the connection details for a library on another server that this org can download surveys from</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Information about the library</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the remote library allows downloads of PPI Templates</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this library allows downloads of templates</description>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <label>Survey Library</label>
    <nameField>
        <label>Survey Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <fields>
        <fullName>Distributed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag means that the version could be downloaded by a partner.</description>
        <label>Distributed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DistributionDate__c</fullName>
        <description>Indicate the date when the survey was distributed.</description>
        <label>Distribution Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deprecated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyVersions</relationshipLabel>
        <relationshipName>SurveyVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SurveyVersionSelector.cls
/**
 * Selector class for the SurveyVersion__c object
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author - Kaushik Ray
 * @author - Aditi Satpute
 * @author - Owen Davies - odavies@grameenfoundation.org
 */
public with sharing class SurveyVersionSelector extends SObjectSelector {

    public Schema.SObjectType getSObjectType() {
        return SurveyVersion__c.sObjectType;
    }

    public List<Schema.SObjectField> getDefaultSelectFields() {
        return new List<Schema.SObjectField> {
            SurveyVersion__c.Distributed__c,
            SurveyVersion__c.DistributionDate__c,
            SurveyVersion__c.Id,
            SurveyVersion__c.Name,
            SurveyVersion__c.Status__c,
            SurveyVersion__c.Survey__c,
            SurveyVersion__c.Version__c,
            SurveyVersion__c.Distributed__c
        };
    }

    public String pathToJobFiltering() {
        return null;
    }

    /**
     * Fetch all survey version records for specified Ids along with Survey details
     */
    public List<SurveyVersion__c> getAllWithSurveyDetails(Set<Id> surveyVersionIds) {
        this.mainQueryBuilder.addRelationshipToSelect(
            new List<Schema.SObjectField> {
                SurveyVersion__c.Survey__c,
                Survey__c.PpiIdentifier__c
            }
        );
        return
            (List<SurveyVersion__c>) getRecordsById(surveyVersionIds);
    }

    /**
     * Get the most recent SurveyVersions for a list of surveys
     *
     * @param surveyList - List of surveys
     *
     * @return - A map of the surveyVersions with the key being the survey.Id
     */
    public Map<Id, SurveyVersion__c> getLatestSurveyVersion(List<Survey__c> surveyList) {

        Map<Id, SurveyVersion__c> versionMap = new Map<Id, SurveyVersion__c>();
        Set<String> setSurveyId = new Set<String>(
            String.join(new List<Id>(
                new Map<Id, Survey__c>(surveyList).keySet()
            ), ',').split(',')
        );
        for (SurveyVersion__c version : getAllWithSurveyIds(setSurveyId)) {
            versionMap.put(version.Survey__c, version);
        }
        return versionMap;
    }

    /**
     * Fetch all survey version records for specified Survey Ids
     */
    public List<SurveyVersion__c> getAllWithSurveyIds(Set<String> surveyIds) {

        return getAllForSurveyIds(new Set<Id> (C.convertListToId(new List<String> (surveyIds))));
    }

    /**
     * Fetch all survey version records for specified Survey Ids
     */
    public List<SurveyVersion__c> getAllForSurveyIds(Set<Id> surveyIds) {

        this.createSurveyIdsWhereClause(surveyIds);
        this.addToMainOrderByClause(
             SurveyVersion__c.Version__c.getDescribe().getName() +
             SObjectSelector.ASCENDING_OPERATOR
        );
        return
            (List<SurveyVersion__c>)
                runSoqlQueryDbFullAccess(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Fetch all survey version records for specified IsPpi, IsTemplate, SurveyLibrary and
     * Status not equal to Deprecated
     */
    public List<SurveyVersion__c> getAllTemplatesForLicense(
            String libraryToView,
            Boolean showPpi,
            Boolean showAll,
            String orderByClause
    ) {
 
        // Check the license. Everyone can use PPI but stop seeing templates if license doesn't allow
        LicenseSettings__c license = C.getLicense();
        if (!license.UseTemplates__c) {
            showAll = false;
            showPPI = true;
        }

        this.createSurveyRelations();

        if (showAll) {
            this.createShowAllTemplatesWithStatusWhereClause(
                showPpi,
                true,
                SurveyDO.STATUS_DEPRECATED
            );
        } else {
            this.createShowPpiTemplatesWithStatusWhereClause(
                showPpi,
                true,
                SurveyDO.STATUS_DEPRECATED
            );
        }

        // Form where clause based on libraryToView
        this.generateSurveyLibraryWhereClause(libraryToView);
        this.addToMainOrderByClause(orderByClause);
        return (List<SurveyVersion__c>) runSoqlQuery(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Create and add relationship fields to be used in query
     */
    private void createSurveyRelations() {
        this.getMainQueryBuilder().addRelationshipToSelect(
            new List<List<Schema.SObjectField>> {
                new List<Schema.SObjectField> {
                    SurveyVersion__c.Survey__c,
                    Survey__c.Name
                },
                new List<Schema.SObjectField> {
                    SurveyVersion__c.Survey__c,
                    Survey__c.Id
                },
                new List<Schema.SObjectField> {
                    SurveyVersion__c.Survey__c,
                    Survey__c.Status__c
                },
                new List<Schema.SObjectField> {
                    SurveyVersion__c.Survey__c,
                    Survey__c.Description__c
                },
                new List<Schema.SObjectField> {
                    SurveyVersion__c.Survey__c,
                    Survey__c.Version__c
                },
                new List<Schema.SObjectField> {
                    SurveyVersion__c.Survey__c,
                    Survey__c.IsPPI__c
                },
                new List<Schema.SObjectField> {
                    SurveyVersion__c.Survey__c,
                    Survey__c.IsTemplate__c
                },
                new List<Schema.SObjectField> {
                    SurveyVersion__c.Survey__c,
                    Survey__c.CreatedDate
                },
                new List<Schema.SObjectField> {
                    SurveyVersion__c.Survey__c,
                    Survey__c.SurveyLibrary__c,
                    SurveyLibrary__c.Name
                },
                new List<Schema.SObjectField> {
                    SurveyVersion__c.Survey__c,
                    Survey__c.CreatedById,
                    User.Name
                }
            }
        );
    }

    private void createShowAllTemplatesWithStatusWhereClause(
            Boolean isPpi,
            Boolean isTemplate,
            String statusValue
    ) {
        this.getMainQueryBuilder().addToWhereClause(returnIsPpiWhereClause(isPpi));
        this.getMainQueryBuilder().addToWhereClause(returnIsTemplateWhereClause(isTemplate));
        String ppiTemplateWhereClause =
            '(' +
            this.getMainQueryBuilder().generateConcatenatedWhereClause(
                SObjectSelector.AND_OPERATOR
            ) +
            ')';
        this.getMainQueryBuilder().resetWhereClause();
        this.getMainQueryBuilder().addToWhereClause(ppiTemplateWhereClause);
        this.getMainQueryBuilder().addToWhereClause(returnIsTemplateWhereClause(isTemplate));
        ppiTemplateWhereClause = 
            '(' +
            this.getMainQueryBuilder().generateConcatenatedWhereClause(
                SObjectSelector.OR_OPERATOR
            ) +
            ')';
        this.getMainQueryBuilder().resetWhereClause();
        this.getMainQueryBuilder().addToWhereClause(ppiTemplateWhereClause);
        this.getMainQueryBuilder().addToWhereClause(returnStatusNotEqualWhereClause(statusValue));
        ppiTemplateWhereClause = 
            '(' +
            this.getMainQueryBuilder().generateConcatenatedWhereClause(
                SObjectSelector.AND_OPERATOR
            ) +
            ')';
        this.getMainQueryBuilder().resetWhereClause();
        this.getMainQueryBuilder().addToWhereClause(ppiTemplateWhereClause);
    }

    private void createShowPpiTemplatesWithStatusWhereClause(
            Boolean isPpi,
            Boolean isTemplate,
            String statusValue
    ) {
        this.createIsPpiWhereClause(isPpi);
        this.createIsTemplateWhereClause(isTemplate);
        this.createStatusNotEqualWhereClause(statusValue);
    }

    /**
     * Create where clause with Survey isPpi for main Survey Version query
     */
    private void createIsPpiWhereClause(Boolean isPpi) {
        this.addToMainWhereClause(
            returnIsPpiWhereClause(isPpi)
        );
    }

    private String returnIsPpiWhereClause(Boolean isPpi) {
        return this.getMainQueryBuilder().generateStandardWhereClause(
            this.getMainQueryBuilder().generateLookUp(
                new List<Schema.SObjectField> {
                    SurveyVersion__c.Survey__c,
                    Survey__c.IsPPI__c
                }
            ),
            SObjectSelector.EQUALS_OPERATOR,
            isPpi
        );
    }

    /**
     * Create where clause with Survey isTemplate for main Survey Version query
     */
    private void createIsTemplateWhereClause(Boolean value) {
        this.addToMainWhereClause(
            returnIsTemplateWhereClause(value)
        );
    }

    private String returnIsTemplateWhereClause(Boolean value) {
        return this.getMainQueryBuilder().generateStandardWhereClause(
            this.getMainQueryBuilder().generateLookUp(
                new List<Schema.SObjectField> {
                    SurveyVersion__c.Survey__c,
                    Survey__c.IsTemplate__c
                }
            ),
            SObjectSelector.EQUALS_OPERATOR,
            value
        );
    }

    /**
     * Create where clause with survey status for main Survey Version query
     */
    private void createStatusNotEqualWhereClause(String value) {
        this.addToMainWhereClause(
            returnStatusNotEqualWhereClause(value)
        );
    }

    private String returnStatusNotEqualWhereClause(String value) {
        return this.getMainQueryBuilder().generateStandardWhereClause(
            this.getMainQueryBuilder().generateLookUp(
                new List<Schema.SObjectField> {
                    SurveyVersion__c.Survey__c,
                    Survey__c.Status__c
                }
            ),
            SObjectSelector.NOT_EQUALS_OPERATOR,
            value
        );
    }

    /**
     * Method to create SurveyLibrary where clause for specified library
     */
    private void generateSurveyLibraryWhereClause(String libraryToView) {
        if (libraryToView.equals('myLib')) {
            this.createSurveyLibraryNullWhereClause();
        } else if (!libraryToView.equals('default')) {
            this.createSurveyLibraryNameWhereClause(libraryToView);
        } 
    }

    /**
     * Create where clause with Survey Library for main Survey Version query
     */
    private void createSurveyLibraryNullWhereClause() {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                this.getMainQueryBuilder().generateLookUp(
                    new List<Schema.SObjectField> {
                        SurveyVersion__c.Survey__c,
                        Survey__c.SurveyLibrary__c
                    }
                ),
                SObjectSelector.EQUALS_OPERATOR,
                SObjectSelector.NULL_VALUE
            )
        );
    }

    /**
     * Create where clause with Survey Library Name for main Survey Version query
     */
    private void createSurveyLibraryNameWhereClause(String libraryToView) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                this.getMainQueryBuilder().generateLookUp(
                    new List<Schema.SObjectField> {
                        SurveyVersion__c.Survey__c,
                        Survey__c.SurveyLibrary__c,
                        SurveyLibrary__c.Name
                    }
                ),
                SObjectSelector.EQUALS_OPERATOR,
                libraryToView
            )
        );
    }

    /**
     * Create where clause with survey Ids for main query of SurveyVersion object
     */
    private void createSurveyIdsWhereClause(Set<Id> surveyIds) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardInWhereClause(
                SurveyVersion__c.Survey__c,
                SObjectSelector.IN_OPERATOR,
                surveyIds
            )
        );
    }
}