src/objects/LicenseSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>To block or enable functionality in the client package . Indicates whether a function is enable or if there is a limit to use it.</description>
    <fields>
        <fullName>PPI_Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PPI_Editable</label>
        <type>Checkbox</type>
    </fields>
    <label>LicenseSettings</label>
</CustomObject>

src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PPIScore__c</fullName>
        <description>The score that PpiScoreValue__c contains. This needs to be manually updated via a trigger each time the PpiScoreValue__c is changed. If PpiScoreValue__c is blank then this left blank. Should only be set by the trigger on ScoreValue__c</description>
        <label>PPI Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Parent question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RemoteServerId__c</fullName>
        <description>Deprecated. Use RemoteId__c as it is indexed</description>
        <label>Remote Server Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ScoreValue__c.object
<CustomObject>
    <fields>
        <fullName>Option__c</fullName>
        <label>Option</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Score Values</relationshipLabel>
        <relationshipName>Score_Values</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ScoringGroup__c</fullName>
        <label>Scoring Group</label>
        <referenceTo>ScoringGroup__c</referenceTo>
        <relationshipLabel>Score Values</relationshipLabel>
        <relationshipName>Score_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Score Value</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>Score Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ScoringGroup__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Scoring Group is for a PPI Template</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Scoring Groups</relationshipLabel>
        <relationshipName>Scoring_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Scoring Group</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Scoring Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <description>This is the alias of the Survey</description>
        <label>Alias</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the survey is a PPI Survey</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this survey is actually a template. If this is checked then this survey cannot be distributed on its own. It must be included into another survey</description>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SurveyScoringController.cls
/*
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 */
 public with sharing class SurveyScoringController {

    public Survey__c survey{get; set;}                                    // Actual survey.
    public BuilderQuestion[] questions = new BuilderQuestion[]{};
    public List<ScoringGroupDomain.ScoringGroup> listGroups =
        new List<ScoringGroupDomain.ScoringGroup>{};
    public List<ScoreValueDomain.ScoringValue> listScoreValues =
        new List<ScoreValueDomain.ScoringValue>{};
    public String scoringGroupStr {get; set;}                             // JSON string passed from the page with the group data.
    public String scoringValuesJson {get; set;}                           // JSON string passed from the page with the Score values data.
    public String continueAfterwards {get;set;}                           // String that decides if should stay in the page (quick save) or continue
    public boolean hasPPILicense {get;set;}
    public boolean wasDownloaded {get;set;}                               // True if it is distributed
    public Boolean concurrentSave{ get; set; }

    public String getQuestions()      { return JSON.serialize(questions); }
    public String getListGroups()     { return JSON.serialize(listGroups); }
    public String getListScoreValues(){ return JSON.serialize(listScoreValues); }

    public static final string PPI_ID = 'PPI';
    public static final string PPI_LABEL = 'Progress out of poverty index';
    public boolean hasApexMessage{
                                get{
                                    return (ApexPages.hasMessages(ApexPages.Severity.ERROR) || ApexPages.hasMessages(ApexPages.Severity.FATAL));
                                }set;}
    public Boolean isPublished {
                                get{
                                    return (survey.Status__c == SurveyDO.STATUS_PUBLISHED);
                                }set;}

    private Integer offset;            // offset to retrieve next batch of questions
    private Boolean hasMoreQuestions;  // set if all questions have already been retrieved
    private BuilderQuestion[] lastBatchOfQuestions;

    public Integer getOffset(){ return offset; }
    public Boolean getHasMoreQuestions(){ return hasMoreQuestions; }
    public String getLastBatchOfquestions(){ return JSON.serialize(lastBatchOfQuestions); }

    /*
    *    Class constructor
    */
    public SurveyScoringController (ApexPages.StandardController stdController) {

        GenericObjectCreator surveyCreator =
            new GenericObjectCreator(Survey__c.SObjectType);
        surveyCreator.checkObjectAccessible();
        surveyCreator.checkFieldsAccessible(new List<Schema.SObjectField> {
            Survey__c.Name,
            Survey__c.Alias__c,
            Survey__c.Version__c,
            Survey__c.IsPPI__c,
            Survey__c.IsTemplate__c,
            Survey__c.Status__c
        });

        this.survey = (Survey__c)stdController.getRecord();

        // Check if has ppi license
        LicenseSettings__c license = C.getLicense();
        hasPPILicense = license.PPI_Editable__c;

        // Catching when the url id is null
        if (this.survey.Id != null) {
            this.survey = new SurveySelector().getSpecificWithSurveyVersion(survey.id);
        } else {
            throw new C.InvalidUrlException(System.Label.BUILDER_ERR_INVALIDURL);
        }

        // setting concurrent save to false
        concurrentSave = false;

        offset = 0;
        lastBatchOfQuestions = new BuilderQuestion[]{};

        SurveyScoringService.loadScoringGroups(this.survey, listGroups);
        loadMoreQuestions();

        //if the survey is published add an error
        if (survey.Status__c == SurveyDO.STATUS_PUBLISHED) {
            ApexPages.message myMsg =
                new ApexPages.Message(
                    ApexPages.Severity.ERROR,
                    system.Label.BUILDER_ERR_SURVEYALREADYPUBLISHED
                );
            ApexPages.addMessage(myMsg);
        }
    }

    /**
     * Load More Operations of Questions
     */
    public void loadMoreQuestions() {

        hasMoreQuestions = false;
        lastBatchOfQuestions.clear();

        // Obtain all questions and their options, for this survey.
        List<Question__c> questionList =
            new QuestionSelector().getWithOptions(this.survey.Id, offset);
        Set<Id> processedQuestions = new Set<Id>();

        // Load questions until I'm close to script statement limit
        Integer cpuTimeLimit = Limits.getLimitCpuTime() - 1000; // save some CPU time for score values
        for(Question__c q : questionList){

            BuilderQuestion bq = new BuilderQuestion(q);
            questions.add(bq);
            lastBatchOfQuestions.add(bq);

            // If at least one question has origin id is a distributed survey
            if(q.RemoteServerId__c != null && q.RemoteServerId__c != ''){
                wasDownloaded = true;
            }

            for(Option__c o : q.Options__r){
                bq.options.add(new BuilderQuestion.Option(o));

                // Add an additional score value for the PPI scoring group
                if (this.survey.isPPI__c) {
                    listScoreValues.add(
                        new ScoreValueDomain.ScoringValue(
                            String.valueof(o.PPIScore__c),
                            String.valueof(o.Id),
                            PPI_ID
                        )
                    );
                }
            }

            offset++;
            processedQuestions.add(q.Id);

            if (cpuTimeLimit > 0 && cpuTimeLimit < Limits.getCpuTime()) {
                hasMoreQuestions = true;
                return;
            }
        }

        // Load score values for processed batch of questions
        ScoreValueSelector scoreValueSelector = new ScoreValueSelector();
        for (ScoreValue__c scoreValue :
                new ScoreValueSelector().getForQuestionIds(processedQuestions)
        ) {
            listScoreValues.add(
                new ScoreValueDomain.ScoringValue(
                    scoreValue,
                    scoreValue.ScoringGroup__r.Caption__c
                )
            );
        }
    }

    // Find a question on the list by it's id
    private BuilderQuestion findQuestion(String id) {
        BuilderQuestion questionReturn = null;
        for (BuilderQuestion q : questions){
            if (q.id == id){
                questionReturn = q;
            }
        }
        return questionReturn;
    }

    // Called from the page when clicking "Save and continue".
    public PageReference saveScoring() {

        PageReference returnPage = null;

        try {

            Survey__c dummySurvey = (Survey__c) new SurveySelector().getRecordById(this.survey.id);

            // Save point in case of an error
            Savepoint sp = Database.setSavepoint();

            if (dummySurvey.Status__c != SurveyDO.STATUS_DRAFT) {
                throw new SurveyScoringService.SurveyScoringServiceException(
                    System.Label.BUILDER_ERR_SURVEYALREADYPUBLISHED
                );
            } else if (dummySurvey.LastModifiedDate != this.survey.LastModifiedDate) {
                // Set boolean to true to display popup to refresh the page
                concurrentSave = true;
                return null;
            } else {
                ScoringGroupDomain scoringGroupDomain =
                    new ScoringGroupDomain.Constructor().constructWithRecords(
                        new ScoringGroupSelector().getAllForSurvey(survey.Id)
                    );
                scoringGroupDomain.deleteRecords();

                // Creates groups.
                if (this.scoringGroupStr != '') {
                    try {
                        SurveyScoringService.databaseSavepoint = sp;
                        this.survey =
                            SurveyScoringService.parseSurveyScoring(
                                this.survey,
                                scoringGroupStr,
                                scoringValuesJson
                            );
                        if (this.continueAfterwards == 'true') {
                            returnPage = survey.IsPPI__c ? Page.LookupTables : Page.SurveyQuestionLogic;
                            returnPage.getParameters().put('id', survey.Id);
                        }
                    } catch (Exception e) {
                        Database.rollback(sp);
                        throw e;
                    }
                }
            }
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            returnPage = null;
        }
        return returnPage;
    }

}