src/objects/LicenseSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>To block or enable functionality in the client package . Indicates whether a function is enable or if there is a limit to use it.</description>
    <fields>
        <fullName>PPI_Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PPI_Editable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DownloadPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DownloadPPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UsePPI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UsePPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateTemplates__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CreateTemplates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DeleteTemplates__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DeleteTemplates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DownloadTemplates__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DownloadTemplates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EditTemplates__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EditTemplates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UseTemplates__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UseTemplates</label>
        <type>Checkbox</type>
    </fields>
    <label>LicenseSettings</label>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the survey is a PPI Survey</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this survey is actually a template. If this is checked then this survey cannot be distributed on its own. It must be included into another survey</description>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SurveyLibrary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The survey library that the survey was downloaded from. Allows easy update</description>
        <label>Survey Library</label>
        <referenceTo>SurveyLibrary__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyLibrary__c.object
<CustomObject>
    <description>Stores the connection details for a library on another server that this org can download surveys from</description>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the remote library allows downloads of PPI Templates</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this library allows downloads of templates</description>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <label>Survey Library</label>
    <nameField>
        <label>Survey Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SurveyControllerExtension.cls
/*
* (c) Copyright 2013 Grameen Foundation USA. All rights reserved
*/
public with sharing class SurveyControllerExtension {

    // License settings
    private LicenseSettings__c license;
    public Boolean isPPIEnabled { get; set; }
    public Boolean canDownloadPpi { get; set; }
    public Boolean canEditPPI { get; set; }
    public Boolean canDeletePpi { get; set; }
    public Boolean canUsePPI { get; set; }
    public Boolean canEditTemplates { get; set; }
    public Boolean canDownloadTemplates { get; set; }
    public Boolean canCreateTemplates { get; set; }
    public Boolean canDeleteTemplates { get; set; }
    public Boolean canUseTemplates { get; set; }
    public Boolean canDistribute { get; set; }

    public Survey__c[] surveysToClone {get; set;}
    public Survey__c survey {get; set;}

    /**
     * Class that represent a survey only with the data being retrieved.
     */
    public class SurveyWrapper {
        public String id {get; set;}
        public String name {get; set;}
        public Boolean isPPI {get; set;}
        public Boolean isTemplate {get; set;}
        public Boolean isDemographicPpiSurvey {get; set;}

        /**
         * Constructor from a Survey__c.
         */
        public SurveyWrapper(Survey__c survey) {
            this.id = survey.Id;
            this.name = survey.Name;
            this.isPPI = survey.IsPPI__c;
            this.isTemplate = survey.IsTemplate__c;

            if (SurveyDO.isNewPpiSurvey(survey) && survey.IsPPI__c ) {
                this.isDemographicPpiSurvey = true;
            } else {
                this.isDemographicPpiSurvey = false;
            }
        }
    }

    /**
     * Get all surveys list and create a json list from a SurveyWrapper list only with the retrieved data
     */
    public String getSurveyList() {
        List<SurveyWrapper> surveyWrapperList = new List<SurveyWrapper>();
        SurveySelector surveySelectorInstance = new SurveySelector();
        surveySelectorInstance.addToMainOrderByClause('');

        for (Survey__c surveyInstance : surveySelectorInstance.getAllSurveys()) {
            surveyWrapperList.add(new SurveyWrapper(surveyInstance));
        }
        return JSON.serialize(surveyWrapperList);
    }

    public void init() {
        LicenseSettings__c license = C.getLicense();

        // PPI license settings
        this.isPPIEnabled = license.PPI_Editable__c;
        this.canDeletePpi = license.PPI_Editable__c;
        this.canDownloadPpi = license.DownloadPPI__c;
        this.canEditPPI = license.PPI_Editable__c;
        this.canUsePPI = license.UsePPI__c;

        this.canCreateTemplates = license.CreateTemplates__c;
        this.canDeleteTemplates = license.DeleteTemplates__c;
        this.canDownloadTemplates = license.DownloadTemplates__c;
        this.canEditTemplates = license.EditTemplates__c;
        this.canUseTemplates = license.UseTemplates__c;
    }

    public SurveyControllerExtension() {
        surveysToClone = new SurveySelector().getAllSurveys();
    }

    /**
     * Generate the Survey Library List.
     * Load all existing Survey Libraries from the database and wrapper them into a dedicated class.
     * (Related: IDALMSA-3213)
     *
     * @return surveyLibraryItems List[] SurveyLibraryItem       List of Survey Library List
     */
    @RemoteAction
    public static List <SurveyLibraryItem> generateSurveyLibraryList() {

        List <SurveyLibrary__c> surveyLibraries =
            new SurveyLibrarySelector().getAllForIsSurveyWithActiveStatus(true);

        // Copy the custom object to a wrapper class to send it to UI.
        List <SurveyLibraryItem> surveyLibraryItems = new List <SurveyLibraryItem>();

        for (SurveyLibrary__c surveyLibrary: surveyLibraries) {
            surveyLibraryItems.add( new SurveyLibraryItem(surveyLibrary));
        }

        return surveyLibraryItems;
    }

    /**
     * Wrapper Class of Survey Library
     * Class to wrapper the query result of Survey Library to send it to UI.
     * (Related: IDALMSA-3213)
     */
    public class SurveyLibraryItem {
        public Id id {get; set;}
        public String Name {get; set;}
        public SurveyLibraryItem() {}

        public SurveyLibraryItem(SurveyLibrary__c surveyLibrary) {
            this.id = surveyLibrary.Id;
            this.Name = surveyLibrary.Name;
        }
    }
}