src/objects/ObjectRelationshipMapping__c.object
<CustomObject>
    <fields>
        <fullName>ChildSurveyMapping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Survey Mapping</label>
        <referenceTo>SurveyMapping__c</referenceTo>
        <relationshipName>Object_Relationship_Mappings_Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieldApiName__c</fullName>
        <label>FieldApiName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentSurveyMapping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Survey Mapping</label>
        <referenceTo>SurveyMapping__c</referenceTo>
        <relationshipName>Object_Relationship_Mappings_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Object Relationship Mapping</label>
    <nameField>
        <label>Object Relationship Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object Relationship Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyMapping__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Mappings</relationshipLabel>
        <relationshipName>Survey_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Mapping</label>
    <nameField>
        <label>SurveyMapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ObjectRelationshipMappingSelector.cls
/**
 * Selector class for the ObjectRelationshipMapping__c object
 *
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 *
 * @author Owen Davies - odavies@grameenfoundation.org
 */
public with sharing class ObjectRelationshipMappingSelector extends SObjectSelector {

    public Schema.SObjectType getSObjectType() {
        return ObjectRelationshipMapping__c.sObjectType;
    }

    public List<Schema.SObjectField> getDefaultSelectFields() {
        return new List<Schema.SObjectField>{
            ObjectRelationshipMapping__c.Id,
            ObjectRelationshipMapping__c.Name,
            ObjectRelationshipMapping__c.ChildSurveyMapping__c,
            ObjectRelationshipMapping__c.FieldApiName__c,
            ObjectRelationshipMapping__c.ParentSurveyMapping__c
        };
    }

    public String pathToJobFiltering() {
        return null;
    }

    public List<ObjectRelationshipMapping__c> getAllForSurvey(Id surveyId) {
        this.mainQueryBuilder.setSelectClauseWithAllFields();
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                new List<Schema.SObjectField>{
                    ObjectRelationshipMapping__c.ParentSurveyMapping__c,
                    SurveyMapping__c.Survey__c
                },
                SObjectSelector.EQUALS_OPERATOR,
                surveyId
            )
        );
        return (List<ObjectRelationshipMapping__c>)
            runSoqlQuery(SObjectSelector.AND_OPERATOR, null);
    }
}