src/objects/ObjectRelationshipMapping__c.object
<CustomObject>
    <fields>
        <fullName>ChildSurveyMapping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Survey Mapping</label>
        <referenceTo>SurveyMapping__c</referenceTo>
        <relationshipName>Object_Relationship_Mappings_Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieldApiName__c</fullName>
        <label>FieldApiName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentSurveyMapping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Survey Mapping</label>
        <referenceTo>SurveyMapping__c</referenceTo>
        <relationshipName>Object_Relationship_Mappings_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Object Relationship Mapping</label>
    <nameField>
        <label>Object Relationship Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object Relationship Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyMapping__c.object
<CustomObject>
    <label>Survey Mapping</label>
    <nameField>
        <label>SurveyMapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ObjectRelationshipMappingDomainTest.cls
/**
 * Test class for the ObjectRelationshipMapping__c object domain class
 * Deals with:
 *     - Creation of a Object Relationship Mapping
 *     - Adding Object Relationship Mapping to a UnitOfWork
 *
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 *
 * @author Owen Davies - odavies@grameenfoundation.org
 */
@isTest
public class ObjectRelationshipMappingDomainTest {

    public static ObjectRelationshipMapping__c createObjectRelationMapping(
            String fiedApiName
    ) {
        return createObjectRelationMapping(new Map<Schema.SObjectField, Object>{
            ObjectRelationshipMapping__c.FieldApiName__c => fiedApiName
        });
    }

    public static ObjectRelationshipMapping__c createObjectRelationMapping(
            Map<Schema.SObjectField, Object> fieldMap
    ) {

        GenericObjectCreator creator =
            new GenericObjectCreator(ObjectRelationshipMapping__c.getSObjectType());
        ObjectRelationshipMapping__c objectRelationMapping =
            (ObjectRelationshipMapping__c) creator.createNewRecord();
        creator.populateFields(
            objectRelationMapping,
            fieldMap
        );
        return objectRelationMapping;
    }

    public static UnitOfWork addObjectRelationshipToUnitOfWork(
        ObjectRelationshipMapping__c objectRelationMapping,
        SurveyMapping__c childMapping,
        SurveyMapping__c parentMapping,
        UnitOfWork unitOfWork
    ) {

        unitOfWork.addToInsertionOrder(ObjectRelationshipMapping__c.getSObjectType(), 1);
        unitOfWork.addToInsertList(
            objectRelationMapping,
            ObjectRelationshipMapping__c.ChildSurveyMapping__c,
            childMapping,
            1
        );
        unitOfWork.createRelationship(
            objectRelationMapping,
            ObjectRelationshipMapping__c.ParentSurveyMapping__c,
            parentMapping,
            1
        );
        return unitOfWork;
    }
}