src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>PPIScore__c</fullName>
        <description>The score that PpiScoreValue__c contains. This needs to be manually updated via a trigger each time the PpiScoreValue__c is changed. If PpiScoreValue__c is blank then this left blank. Should only be set by the trigger on ScoreValue__c</description>
        <label>PPI Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ScoreValue__c.object
<CustomObject>
    <fields>
        <fullName>Option__c</fullName>
        <label>Option</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Score Values</relationshipLabel>
        <relationshipName>Score_Values</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Score Value</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>Score Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScoreValueTHTest.cls
/**
 * This test class is used to cover test cases for ScoreValueTH class
 * 
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author Owen Davies - odavies@grameenfoundation.org
 * @author Kaushik Ray
 */
@isTest
public class ScoreValueTHTest {

    /**
     * Test that creating a PPI score value updates the PPI score on the Option
     */
    static testMethod void testAddPpiScoringDetails() {

        Test.startTest();
        TestSurveyData testSurvey = TestSurveyData.addPpiTablesToStandardSurvey(
            TestSurveyData.addScoringGroupToStandardSurvey(
                TestSurveyData.createStandardTestSurvey(
                    SurveyDOTest.createInsertedPpiTemplate(), true
                ),
                true
            )
        );
        Test.stopTest();
        Map<Id, ScoreValue__c> createScoreValues = new Map<Id, ScoreValue__c>(
            testSurvey.getScoreValues(0)
        );
        System.assertEquals(5, createScoreValues.size());
        List<ScoreValue__c> updatedScoreValueList =
            new ScoreValueSelector().getWithParentFields(createScoreValues.keySet());
        for (ScoreValue__c scoreValue : updatedScoreValueList) {
            System.assertEquals(
                scoreValue.Value__c,
                scoreValue.Option__r.PPIScore__c,
                'Trigger should update Ppi score'
            );
        }
    }
}