src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>PPIScore__c</fullName>
        <description>The score that PpiScoreValue__c contains. This needs to be manually updated via a trigger each time the PpiScoreValue__c is changed. If PpiScoreValue__c is blank then this left blank. Should only be set by the trigger on ScoreValue__c</description>
        <label>PPI Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Parent question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PpiResult__c.object
<CustomObject>
    <description>Stores the results of a PPI survey. This is a snapshot in time so the demographic data in here may not actually reflect the current state but rather reflects the state at the time the survey was conducted.
Lookups to custom objects can be added to allow for reporting against custom data gathered alongside the PPI. Individual fields can also be added to allow for the same</description>
    <fields>
        <fullName>Age__c</fullName>
        <description>The age of the client at the time they took the PPI Survey</description>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AnswerOne__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The option that was chosen as the answer to the first PPI question</description>
        <label>Answer One</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>PPI Results Answer One</relationshipLabel>
        <relationshipName>PpiResultsOne</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientId__c</fullName>
        <description>The Id of the client that took the PPI Survey</description>
        <externalId>true</externalId>
        <label>Client Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>The gender of the client that took the PPI Survey</description>
        <label>Gender</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HouseholdSize__c</fullName>
        <description>The size of the client's household at the time they took the PPI Survey</description>
        <label>Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JoinedDate__c</fullName>
        <description>The date the client joined the organisation that is carrying out the PPI Survey</description>
        <label>Joined Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <label>Organization Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PpiCollectionDate__c</fullName>
        <label>PPI Collection Date</label>
        <type>DateTime</type>
    </fields>
        <fields>
        <fullName>UniqueKey__c</fullName>
        <label>UniqueKey</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PpiScore__c</fullName>
        <description>The total PPI Score for this submission. Should only count towards any Reports if the PPI is valid</description>
        <formula>AnswerOne__r.PPIScore__c + AnswerTwo__r.PPIScore__c + AnswerThree__r.PPIScore__c + AnswerFour__r.PPIScore__c + AnswerFive__r.PPIScore__c + AnswerSix__r.PPIScore__c + AnswerSeven__r.PPIScore__c + AnswerEight__r.PPIScore__c + AnswerNine__r.PPIScore__c + AnswerTen__r.PPIScore__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PPI Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PpiTemplate__c</fullName>
        <description>The PPI Template that the Submission was for</description>
        <label>PPI Template</label>
        <referenceTo>SurveyVersion__c</referenceTo>
        <relationshipLabel>PPI Template</relationshipLabel>
        <relationshipName>PPI_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RetrievedByParent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this record has been successfully sent back to the Parent Org</description>
        <label>Retrieved By Parent</label>
        <type>Checkbox</type>
    </fields>
    <label>PPI Result</label>
    <nameField>
        <displayFormat>PPIR-{0000000000}</displayFormat>
        <label>PPI Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPI Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PpiSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <label>PPI Settings</label>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>PpiIdentifier__c</fullName>
        <label>PPI Identifier</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyVersions</relationshipLabel>
        <relationshipName>SurveyVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PpiResultDomainTest.cls
/**
 * This class contains unit tests for validating the behavior of PpiResultDomain
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author - Kaushik Ray
 * @author - Aditi Satpute
 */
@isTest
public with sharing class PpiResultDomainTest {

    public static final String ACCOUNT_API_NAME =
        Account.sObjectType.getDescribe().getName();

    /**
     * Create sample Ppi records with all data necessary
     */
    public static List<PpiResult__c> createSamplePpiResultData(
            Integer numberOfRecords,
            Boolean isRetrievedByParent
    ) {

        Survey__c survey = SurveyDOTest.createInsertedSurvey();
        Set<String> surveyIdSet = new Set<String>{survey.Id};

        List<SurveyVersion__c> surveyVersionList =
            new SurveyVersionSelector().getAllWithSurveyIds(surveyIdSet);

        List<Question__c> sectionList =
            new List<Question__c>{
                QuestionDOTest.createSection(1),
                QuestionDOTest.createSection(2)
            };
        sectionList[0].Survey__c = survey.Id;
        sectionList[1].Survey__c = survey.Id;
        insert sectionList;
        System.assertEquals(2, sectionList.size());

        List<Question__c> questionList = new List<Question__C>{};
        for (Question__c section : sectionList) {
            Question__c newSelect = QuestionDOTest.createQuestion(
                QuestionDO.TYPE_RADIO,
                'SelectQuestion',
                'Caption',
                1
            );
            newSelect.Survey__c = section.Survey__c;
            newSelect.Parent__c = section.Id;
            questionList.add(newSelect);
        }
        insert questionList;

        List<Option__c> optionList =
            OptionDomainTest.createOptionsForQuestions(
                questionList,
                'Option_Name',
                'Option_caption',
                numberOfRecords
        );
        System.assertEquals(numberOfRecords * 2, optionList.size());
        insert optionList;

        List<PpiResult__c> ppiResultList = createMultipleRecords(
            numberOfRecords,
            surveyVersionList[0],
            optionList,
            isRetrievedByParent
        );

        PpiResultDomain ppiDomainInstance =
            new PpiResultDomain.Constructor().constructWithRecords(
                ppiResultList
            );
        ppiDomainInstance.insertRecords();

        return ppiResultList;
    }

    /**
     * Create multiple records for PpiResult 
     */
     public static List<PpiResult__c> createMultipleRecords(
            Integer numberOfRecords,
            SurveyVersion__c surveyVersion,
            List<Option__c> optionList,
            Boolean isRetrievedByParent
    ) {
        List<PpiResult__c> ppiResultList = new List<PpiResult__c>();
        for (Integer i = 0; i < numberOfRecords; i++) {
            PpiResult__c ppiResult =
                createRecord(
                    surveyVersion,
                    optionList[i],
                    isRetrievedByParent
                );
            ppiResultList.add(ppiResult);
        }
        return ppiResultList;
    }

    /**
     * Create record for PpiResult 
     */
    public static PpiResult__c createRecord(
            SurveyVersion__c surveyVersion,
            Option__c option,
            Boolean isRetrievedByParent
    ) {
        PpiResult__c ppiResult = new PpiResult__c(
            PpiTemplate__c = surveyVersion.Id,
            AnswerOne__c = option.Id,
            RetrievedByParent__c = isRetrievedByParent,
            GeoLocation__Latitude__s = 17.345,
            GeoLocation__Longitude__s = 75.342
        );
        return ppiResult;
    }

    /**
     * Test method for setCollectionDatePpiResults
     */
    static testMethod void testSetCollectionDatePpiResults() {
        List<PpiResult__c> ppiResultList = createSamplePpiResultData(10, false);

        Test.startTest();
        new PpiResultDomain().setCollectionDatePpiResults(ppiResultList, false);
        Test.stopTest();

        for (PpiResult__c ppiResult : ppiResultList) {
            System.assert(
                ppiResult.PpiCollectionDate__c != null,
                'Collection Date should not be null'
            );
        }
    }

    /**
     * Test method to verify set uniqueKey
     */
    static testMethod void testSetUniqueKey() {

        TestSurveyData testSurvey = TestSurveyData.createStandardTestSurvey(null, false);

        Map<Integer, String> optionIdsWithSequenceMap = new Map<Integer, String>();
        Integer countValue = 0;
        for (
                Option__c option :
                    testSurvey.optionMap.get(
                        testSurvey.questionMap.get(testSurvey.topLevelSections[0].Id)[2].Id
                    )
        ) {
            optionIdsWithSequenceMap.put(countValue++, option.Id);
        }

        PpiResult__c ppiResult = PpiResultDomain.createRecord(
            optionIdsWithSequenceMap,
            'clientId',
            'Female',
            32,
            Date.valueOf('2014-11-11'),
            12,
            '17.345 75.342 0 0',
            'organisation',
            testSurvey.testSurveyVersion.Id,
            null,
            Datetime.newInstance(2014, 12, 1)
        );
        PpiDataSubmissionService.organizationName = ppiResult.OrganizationName__c;

        Test.startTest();
        new PpiResultDomain().setUniqueKeys(new List<PpiResult__c> {ppiResult});
        Test.stopTest();

        System.assert(ppiResult != null, 'PpiResult not created properly');

        String expectedUniqueKey =
            PpiResultDomain.encodePpiUniqueKey(
                getExpectedUniqueKey(
                    ppiResult,
                    testSurvey.testSurvey.PpiIdentifier__c,
                    optionIdsWithSequenceMap
                )
            );
        System.assertEquals(
            expectedUniqueKey,
            ppiResult.UniqueKey__c
        );
    }

    /**
     * Test method for validating uniqueKey Creation
     */
    static testMethod void testUniqueKeyCreation() {
        PpiDataSubmissionServiceTest.setUpTestData();

        List<PpiResult__c> ppiResultList =
            new PpiResultSelector().getAllWithSyncValue(
                PpiDataSubmissionServiceTest.ppiResultIds,
                false
            );
        System.assertEquals(2, ppiResultList.size());

        Map<Integer, String> ppiResultOptionRemoteIdsWithSequenceMap =
            PpiResultDomain.populateSequenceOptionRemoteIdsMap(ppiResultList[0]);

        Test.startTest();
        String actualUniqueKey =
            PpiResultDomain.createPpiResultUniqueKey(
                ppiResultList[0],
                PpiDataSubmissionServiceTest.childSurvey.testSurvey.PpiIdentifier__c,
                ppiResultOptionRemoteIdsWithSequenceMap
            );
        Test.stopTest();

        System.assertEquals(
            getExpectedUniqueKey(
                ppiResultList[0],
                PpiDataSubmissionServiceTest.childSurvey.testSurvey.PpiIdentifier__c,
                ppiResultOptionRemoteIdsWithSequenceMap
            ),
            actualUniqueKey
        );
    }

    /**
     * Test method for validating encoding of uniqueKey
     */
    static testmethod void testUniqueKeyEncoding() {
        PpiDataSubmissionServiceTest.setUpTestData();

        List<PpiResult__c> ppiResultList =
            new PpiResultSelector().getAllWithSyncValue(
                PpiDataSubmissionServiceTest.ppiResultIds,
                false
            );

        System.assertEquals(2, ppiResultList.size());

        Map<Integer, String> ppiResultOptionRemoteIdsWithSequenceMap =
            PpiResultDomain.populateSequenceOptionRemoteIdsMap(ppiResultList[0]);

        Test.startTest();
        String actualEncodedUniqueKey =
            PpiResultDomain.encodePpiUniqueKey(
                getExpectedUniqueKey(
                    ppiResultList[0],
                    PpiDataSubmissionServiceTest.childSurvey.testSurvey.PpiIdentifier__c,
                    ppiResultOptionRemoteIdsWithSequenceMap
                )
            );
        Test.stopTest();

        String expectedEncodedUniqueKey =
            EncodingUtil.base64Encode(
                Crypto.generateDigest(
                    'MD5',
                    Blob.valueof(
                        getExpectedUniqueKey(
                            ppiResultList[0],
                            PpiDataSubmissionServiceTest.childSurvey.testSurvey.PpiIdentifier__c,
                            ppiResultOptionRemoteIdsWithSequenceMap
                        )
                    )
                )
            );
 
        System.assertEquals(
            expectedEncodedUniqueKey,
            actualEncodedUniqueKey
        );
    }

    /**
     * Method to test fetching of PpiResult's SurveyVersionIds
     */
    static testmethod void testFetchPpiResultSurveyIds() {

        Survey__c survey = SurveyDOTest.createInsertedSurvey();

        List<SurveyVersion__c> surveyVersionList =
            new SurveyVersionSelector().getAllWithSurveyIds(
                new Set<String> {survey.Id}
            );

        System.assertEquals(1, surveyVersionList.size());

        PpiResult__c ppiResult = createRecord(surveyVersionList[0], new Option__c(), false);
        PpiResultDomain ppiResultDomainInstance = new PpiResultDomain();
        ppiResultDomainInstance.addRecord(ppiResult);
        ppiResultDomainInstance.insertRecords();

        System.assert(ppiResult != null, 'Ppi Result not created properly');

        Test.startTest();
        Set<Id> surveyVersionIds =
            PpiResultDomain.fetchPpiResultSurveyVersionIds(new List<PpiResult__c> {ppiResult});
        Test.stopTest();

        System.assertEquals(1, surveyVersionIds.size());
        System.assert(
            surveyVersionIds.contains(ppiResult.PpiTemplate__c),
            'SurveyVersion Ids not fetched properly'
        );
    }

    /**
     * Method to populate a map with Sequence of OptionRemoteIds
     */
    static testmethod void testPopulateSequenceOptionRemoteIdsMap() {

        Set<String> parentOptionIds = new Set<String>();
        Boolean isRemoteIdSet = false;
        PpiDataSubmissionServiceTest.setUpTestData();

        List<PpiResult__c> ppiResultList =
            new PpiResultSelector().getAllWithSyncValue(
                PpiDataSubmissionServiceTest.ppiResultIds, false
            );

        System.assertEquals(2, ppiResultList.size());

        Test.startTest();
        Map<Integer, String> ppiResultSequenceOptionRemoteIdsMap =
            PpiResultDomain.populateSequenceOptionRemoteIdsMap(ppiResultList[0]);
        Test.stopTest();

        System.assertEquals(10, ppiResultSequenceOptionRemoteIdsMap.size());
        System.assertEquals(2, PpiDataSubmissionServiceTest.parentSurvey.topLevelSections.size());
        List<Question__c> questionList =
            PpiDataSubmissionServiceTest.parentSurvey.questionMap.get(
                PpiDataSubmissionServiceTest.parentSurvey.topLevelSections[0].Id
            );
        System.assertEquals(3, questionList.size());
        List<Option__c> parentOptions =
            PpiDataSubmissionServiceTest.parentSurvey.optionMap.get(
                questionList[2].Id
            );

        for (Option__c option : parentOptions) {
            parentOptionIds.add(option.Id);
        }

        for (String optionRemoteIds : ppiResultSequenceOptionRemoteIdsMap.values()) {
            // Remote Ids should match with parent option Ids
            if (parentOptionIds.contains(optionRemoteIds)) {
                isRemoteIdSet = true;
            }
        }
        System.assert(isRemoteIdSet, 'Remote Ids should set with respect to parent option Ids');
    }

    /**
     * Test method to verify ppi result wrapper data is populated for missing demograhic data
     */
    static testMethod void testUpdateDemographicFieldsWithExistingData() {
        PpiSettings__c ppiSettings = createPpiSettingsRecord();
        Account accountRecord = createAccountRecord();

        PpiResultDomain.PpiResultWrapper wrapperInstance =
            new PpiResultDomain.PpiResultWrapper('Test Template');
        wrapperInstance.clientId = Schema.sObjectType.Account.fields.Site.getName();

        System.assert(wrapperInstance.clientId != null);

        Test.startTest();
        wrapperInstance.updateDemographicFieldsWithExistingData(
            ppiSettings,
            accountRecord
        );
        Test.stopTest();

        System.assertEquals(accountRecord.AccountNumber, wrapperInstance.gender);
        System.assertEquals(null, wrapperInstance.householdSize);
        System.assertEquals(accountRecord.CreatedDate, wrapperInstance.joinedDate);
        System.assertEquals(accountRecord.NumberOfEmployees, wrapperInstance.age);
    }

    /**
     * Test method to verify ppi result wrapper data is not populated if ClientId is null
     */
    static testMethod void testUpdateDemographicFieldsWithNullClientId() {
        PpiSettings__c ppiSettings = createPpiSettingsRecord();
        Account accountRecord = createAccountRecord();

        PpiResultDomain.PpiResultWrapper wrapperInstance =
            new PpiResultDomain.PpiResultWrapper('Test Template');

        Test.startTest();
        wrapperInstance.updateDemographicFieldsWithExistingData(
            ppiSettings,
            accountRecord
        );
        Test.stopTest();

        System.assert(wrapperInstance.gender == null);
        System.assert(wrapperInstance.householdSize == null);
        System.assert(wrapperInstance.joinedDate == null);
        System.assert(wrapperInstance.age == null);
    }

    /**
     * Method for creating Ppi Settings
     */
    public static PpiSettings__c createPpiSettingsRecord() {

        PpiSettings__c ppiSettingsRecord = PpiSettingsWrapper.insertRecord(
            ACCOUNT_API_NAME,
            Schema.sObjectType.Account.fields.NumberOfEmployees.getName(),
            Schema.sObjectType.Account.fields.Site.getName(),
            Schema.sObjectType.Account.fields.CreatedDate.getName(),
            Schema.sObjectType.Account.fields.AccountNumber.getName(),
            ''
        );
        PpiSettings__c ppiSettings =
            PpiSettingsWrapper.getRecordForName(ACCOUNT_API_NAME);
        System.assert(
            ppiSettings != null,
            'PpiSettings record not found for : ' + ACCOUNT_API_NAME
        );
        return ppiSettings;
    }

    /**
     * Method for creating and verifying Account record
     */
    public static Account createAccountRecord() {
        Account accountRecord =
            AccountDomainTest.createRecord(
                'Test Account',
                15,
                'Test Site',
                'ACC-001'
            );

        AccountDomain accountDomain = new AccountDomain();
        accountDomain.addRecord(accountRecord);
        accountDomain.insertRecords();
        System.assert(accountDomain.records.size() > 0);
        System.assert(accountDomain.records[0].Id != null);

        return (Account) accountDomain.records[0];
    }

    /**
     * Method for generating expected unique key
     */
    public static String getExpectedUniqueKey(
            PpiResult__c ppiResult,
            String ppiIdentifier,
            Map<Integer, String> optionIdsWithSequenceMap
    ) {
        List<String> uniqueKeyDataList = new List<String>();
        String ppiScore = null;
        uniqueKeyDataList.add(ppiIdentifier);
        uniqueKeyDataList.add(ppiResult.OrganizationName__c);
        uniqueKeyDataList.add(String.valueOf(ppiResult.PpiCollectionDate__c));
        uniqueKeyDataList.add(String.valueOf(
            ppiResult.PpiScore__c != null
            ? ppiResult.PpiScore__c.setScale(1)
            : ppiResult.PpiScore__c
        ));
        uniqueKeyDataList.add(ppiResult.ClientId__c);
        uniqueKeyDataList.add(ppiResult.Gender__c);
        uniqueKeyDataList.add(String.valueOf(ppiResult.Age__c));
        uniqueKeyDataList.add(String.valueOf(ppiResult.HouseholdSize__c));
        uniqueKeyDataList.add(String.valueOf(ppiResult.JoinedDate__c));
        uniqueKeyDataList.add(String.valueOf(ppiResult.GeoLocation__Latitude__s));
        uniqueKeyDataList.add(String.valueOf(ppiResult.GeoLocation__Longitude__s));
        uniqueKeyDataList.add(optionIdsWithSequenceMap.get(1));
        uniqueKeyDataList.add(optionIdsWithSequenceMap.get(2));
        uniqueKeyDataList.add(optionIdsWithSequenceMap.get(3));
        uniqueKeyDataList.add(optionIdsWithSequenceMap.get(4));
        uniqueKeyDataList.add(optionIdsWithSequenceMap.get(5));
        uniqueKeyDataList.add(optionIdsWithSequenceMap.get(6));
        uniqueKeyDataList.add(optionIdsWithSequenceMap.get(7));
        uniqueKeyDataList.add(optionIdsWithSequenceMap.get(8));
        uniqueKeyDataList.add(optionIdsWithSequenceMap.get(9));
        uniqueKeyDataList.add(optionIdsWithSequenceMap.get(10));

        StringBuilder stringBuilderInstance = new StringBuilder(uniqueKeyDataList);
        stringBuilderInstance.setJoiner(PpiResultDomain.SPLITTER);

        return stringBuilderInstance.generateString();
    }
}