src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>Question__c</fullName>
        <description>Parent question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the survey is a PPI Survey</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this survey is actually a template. If this is checked then this survey cannot be distributed on its own. It must be included into another survey</description>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QuestionSelectorTest.cls
/**
 * Test class for the QuestionSelector
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author Aditi Satpute
 * @author Kaushik Ray
 */
@isTest
public with sharing class QuestionSelectorTest {

    private static Survey__c survey1;
    private static Survey__c survey2;

    /**
     * Test method to verify fetching of Question records with specified Ppi survey Id
     */
    static testmethod void testFetchAllForPpiSurveyIds() {
        TestUtils.updatePpiLicenseSettings();

        TestSurveyData kenyaPpiSurvey =
            TestSurveyData.addPpiTablesToStandardSurvey(
                TestSurveyData.createStandardTestSurvey(SurveyDOTest.createInsertedPpiTemplate(
                    LanguageWrapperTest.insertRecord('AA', 'Afar'),
                    ISOCountryWrapperTest.insertRecord('KE', 'KENYA'),
                    2011
                ), false)
            );
        TestSurveyData italyPpiSurvey =
            TestSurveyData.addPpiTablesToStandardSurvey(
                TestSurveyData.createStandardTestSurvey(SurveyDOTest.createInsertedPpiTemplate(
                    LanguageWrapperTest.insertRecord('LA', 'LATIN'),
                    ISOCountryWrapperTest.insertRecord('IT', 'ITALY'),
                    2013
                ), false)
            );
        italyPpiSurvey.testSurvey.isTemplate__c = false;
        italyPpiSurvey.testSurvey.isPPI__c = false;
        update italyPpiSurvey.testSurvey;

        Test.startTest();
        List<Question__c> kenyaQuestionList =
            new QuestionSelector().getAllForPPISurveyId(kenyaPpiSurvey.testSurvey.Id);
        List<Question__c> italyQuestionList =
            new QuestionSelector().getAllForPPISurveyId(italyPpiSurvey.testSurvey.Id);
        Test.stopTest();

        // Question records are fetched properly for Survey1 having isPPI and isTemplate true
       System.assertEquals(7, kenyaQuestionList.size());

        // Question records are not fetched as Survey2 is having isPPI true and isTemplate false
        System.assertEquals(0, italyQuestionList.size());
    }

    /**
     * Test method to verify fetching of Question records with specified survey Ids
     */
    static testmethod void testFetchAllForSurveyIds() {

        TestSurveyData testSurvey1 = TestSurveyData.createStandardTestSurvey(null, false);
        TestSurveyData testSurvey2 = TestSurveyData.createStandardTestSurvey(null, false);

        Test.startTest();
        List<Question__c> questionsList = new QuestionSelector().getAllForSurveyIds(
            new Set<String> {testSurvey1.testSurvey.Id, testSurvey2.testSurvey.Id},
            1
        );
        Test.stopTest();
    }
    /**
     * Method to test fetching all question records for specified PPI Survey Id
     */
    static testMethod void testGetAllForPpiSurveyId() {
        Id surveyId = addSurvey();
        Test.startTest();
        List<Question__c> questions = new QuestionSelector().getAllForPpiSurveyId(surveyId);
        Test.stopTest();

        System.assertEquals(2, questions.size(), 'Question should get selected properly');
    }

    /**
     * Method to test fetching all question records along with related options
     */
    static testMethod void testGetWithOptions() {
        Id surveyId = addSurvey();

        Test.startTest();
        List<Question__c> questions = new QuestionSelector().getWithOptions(surveyId, 0);
        Test.stopTest();

        System.assertEquals(2, questions.size(), 'Question should get selected properly');
        System.assertEquals(
            5,
            questions[1].Options__r.size(),
            'Options should get selected properly'
        );
    }

    private static Id addSurvey() {
        Survey__c survey = SurveyDOTest.createInsertedPpiTemplate();
        survey = new SurveySelector().getSpecificWithSurveyVersion(survey.Id);
        UnitOfWork unitOfWork = new UnitOfWork();

        Question__c section = QuestionDOTest.createSection(0);
        unitOfWork = QuestionDOTest.addQuestionToUnitOfWork(
            section,
            null,
            survey,
            unitOfWork,
            1
        );
        QuestionDOTest.SelectQuestion selectQuestion = new QuestionDOTest.SelectQuestion(
            QuestionDO.TYPE_RADIO,
            section,
            survey
        );
        selectQuestion.generateQuestion(0);
        selectQuestion.createOptions(5);
        unitOfWork = selectQuestion.addQuestionToUnitOfWork(unitOfWork, 2);
        unitOfWork = selectQuestion.addOptionsToUnitOfWork(unitOfWork, 1);

        unitOfWork.commitWork();
        return survey.Id;
    }
}