src/objects/Option__c.object
<CustomObject>
    <description>Answer option for a survey question</description>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PPIScore__c</fullName>
        <description>The score that PpiScoreValue__c contains. This needs to be manually updated via a trigger each time the PpiScoreValue__c is changed. If PpiScoreValue__c is blank then this left blank. Should only be set by the trigger on ScoreValue__c</description>
        <label>PPI Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Position of the option within the option group</description>
        <label>Position</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Parent question</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OptionDomainTest.cls
/**
 * Test class for the OptionDomain class.
 * Deals with Option creation for test
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author - Owen Davies - odavies@grameenfoundation.org
 * @author - Aditi Satpute
 * @author - Kaushik Ray
 */
@isTest
public class OptionDomainTest {

    public static List<Option__c> createOptionsForQuestions(
            List<Question__c> questions,
            String namePrefix,
            String captionPrefix,
            Integer optionPerQuestion
    ) {
        List<Option__c> createdOptions = new List<Option__c>();
        for (Question__c question : questions) {
            for (Integer count = 1; count <= optionPerQuestion; count++) {
                createdOptions.add(
                    createOption(new Map<Schema.SObjectField, Object>{
                        Option__c.Name => namePrefix + '_' + count,
                        Option__c.Caption__c => captionPrefix + '_' + count,
                        Option__c.PPIScore__c => count,
                        Option__c.Position__c => count,
                        Option__c.Question__c => question.Id
                    })
                );
            }
        }
        return createdOptions;
    }

    public static List<Option__c> createOptions(Integer numberOfOptions) {

        List<String> captions = new List<String>();
        for (Integer i = 1; i <= numberOfOptions; i++) {
            captions.add('Caption_' + i);
        }
        return createOptions(captions);
    }

    public static List<Option__c> createOptions(List<String> captions) {
        Integer i = 1;
        List<Option__c> options = new List<Option__c>();
        for (String caption : captions) {
            options.add(createOption(caption, i));
            i++;
        }
        return options;
    }

    public static Option__c createOption(String caption, Integer position) {
        return createOption(
            new Map<Schema.SObjectField, Object>{
                Option__c.Caption__c => caption,
                Option__c.PPIScore__c => position,
                Option__c.Position__c => position
            }
        );
    }

    public static Option__c createOption(Map<Schema.SObjectField, Object> fieldMap) {
        GenericObjectCreator creator = new GenericObjectCreator(Option__c.getSObjectType());
        Option__c option = (Option__c) creator.createNewRecord();
        creator.populateFields(
            option,
            fieldMap
        );
        return option;
    }

    /**
     * Create record for Option 
     */
    public static Option__c createRecord(
            String name,
            Question__c question,
            Integer position
    ) {
        Option__c option = new Option__c(
            Name = name,
            Caption__c = name,
            Question__c = question.Id,
            Position__c = position
        );
        return option;
    }
}