src/objects/PpiResult__c.object
<CustomObject>
    <description>Stores the results of a PPI survey. This is a snapshot in time so the demographic data in here may not actually reflect the current state but rather reflects the state at the time the survey was conducted.
Lookups to custom objects can be added to allow for reporting against custom data gathered alongside the PPI. Individual fields can also be added to allow for the same</description>
    <fields>
        <fullName>PpiScore__c</fullName>
        <description>The total PPI Score for this submission. Should only count towards any Reports if the PPI is valid</description>
        <formula>AnswerOne__r.PPIScore__c + AnswerTwo__r.PPIScore__c + AnswerThree__r.PPIScore__c + AnswerFour__r.PPIScore__c + AnswerFive__r.PPIScore__c + AnswerSix__r.PPIScore__c + AnswerSeven__r.PPIScore__c + AnswerEight__r.PPIScore__c + AnswerNine__r.PPIScore__c + AnswerTen__r.PPIScore__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PPI Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PpiTemplate__c</fullName>
        <description>The PPI Template that the Submission was for</description>
        <label>PPI Template</label>
        <referenceTo>SurveyVersion__c</referenceTo>
        <relationshipLabel>PPI Template</relationshipLabel>
        <relationshipName>PPI_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PPI Result</label>
    <nameField>
        <displayFormat>PPIR-{0000000000}</displayFormat>
        <label>PPI Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPI Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PPITable__c.object
<CustomObject>
    <description>The PPI scoring table</description>
    <label>PPI Table</label>
    <nameField>
        <label>PPI Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPI Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PPITableDataSet__c.object
<CustomObject>
    <description>A junction object that links a Survey Version to a PPI Table. This allows for a m-m relationship between these two objects so that a PPI Table can be referenced by a Survey Version as opposed to needing to be copied. All fields on this object are deprecated and moved to PPI Table except for Survey Version and PPI Table. Survey is kept here as it cannot be moved. It is not needed any more</description>
    <fields>
        <fullName>PPITable__c</fullName>
        <label>PPI Table</label>
        <referenceTo>PPITable__c</referenceTo>
        <relationshipLabel>PPI Table Data Sets</relationshipLabel>
        <relationshipName>PPI_Table_Data_Sets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SurveyVersion__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Survey Version that this junction object is for</description>
        <label>Survey Version</label>
        <referenceTo>SurveyVersion__c</referenceTo>
        <relationshipLabel>Survey Version</relationshipLabel>
        <relationshipName>Survey_Version</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>PPI Table Data Set</label>
    <nameField>
        <displayFormat>PTDS-{00000000}</displayFormat>
        <label>PPI Table Data Set Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPI Table Data Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PPITableLine__c.object
<CustomObject>
    <description>Represents a bucket in the Poverty Table. Used to convert raw score in to a probability</description>
    <fields>
        <fullName>From__c</fullName>
        <description>Scoring range start score</description>
        <label>From</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PpiTable__c</fullName>
        <description>The PPI Table that the line is for</description>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PPI Table</label>
        <referenceTo>PPITable__c</referenceTo>
        <relationshipLabel>PPI Table</relationshipLabel>
        <relationshipName>PPI_Table</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PPITableDataSet__c</fullName>
        <description>Field is deprecated. Use PpiTable__c instead. Set to null in all future PPITableLine records. Leaving existing values to allow for backwards compatibility</description>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PPI Table Data Set</label>
        <referenceTo>PPITableDataSet__c</referenceTo>
        <relationshipLabel>PPI Table Lines</relationshipLabel>
        <relationshipName>PPI_Table_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <description>Scoring range finish score</description>
        <label>To</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PPI Table Line</label>
    <nameField>
        <displayFormat>PPIL-{00000000}</displayFormat>
        <label>PPI Table Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPI Table Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SubmissionPpiAssociation__c.object
<CustomObject>
    <fields>
        <fullName>PpiResult__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The PPI Result record that this value belongs to</description>
        <label>PPI Result</label>
        <referenceTo>PpiResult__c</referenceTo>
        <relationshipLabel>Submission PPI Associations</relationshipLabel>
        <relationshipName>Submission_Ppi_Associations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PpiTableLine__c</fullName>
        <description>The PPI Table line that this record maps to</description>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>PPI Table Line</label>
        <referenceTo>PPITableLine__c</referenceTo>
        <relationshipLabel>Submission PPI Associations</relationshipLabel>
        <relationshipName>Submission_Ppi_Associations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Submission PPI Association</label>
    <nameField>
        <displayFormat>SPA-{0000000000}</displayFormat>
        <label>Junction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission PPI Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PpiResultTH.cls
/**
 * This class contains all the logic that is carried out by a
 * trigger on PpiResult__c object.
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author - Aditi Satpute
 */
public with sharing class PpiResultTH extends TriggerHandler {

    // Boolean to check if any migration is going on
    public static Boolean isMigration;

    static {
        // Set false only if this variable is not explicitly set from any other places
        if (isMigration == null) {
            isMigration = false;
        }
    }

    private PpiResultDomain getTriggerDomain() {
        return (PpiResultDomain) this.domain;
    }

    /**
     * Defaults to apply before insert
     */
    public override void applyDefaults() {
        // Set PpiCollection Date first as it is used while creation of Unique Key for ppi Results
        getTriggerDomain().setCollectionDatePpiResults((List<PpiResult__c>) getRecords(), isMigration);
        getTriggerDomain().setUniqueKeys((List<PpiResult__c>) getRecords());
    }

    /**
     * After Insert
     *
     * Check to be carried out:-
     *     - Check that PpiScore lies in valid probabilities
     *
     * Actions carried out:-
     *     - Calculate probabilities based on recieved PpiResult record
     *     - Create Submission Ppi Association records
     */
    public override void onAfterInsert() {
        saveSubmissionPpiData((List<PpiResult__c>) getRecords());
    }

    /**
     * Method to save Submission Ppi data on parent org
     */
    @TestVisible
    private static void saveSubmissionPpiData(List<PpiResult__c> insertedPpiResultList) {
        try {
            List<SubmissionPpiAssociation__c> submissionPpiData =
                new List<SubmissionPpiAssociation__c>();
            Map<Id, List<PPITableDataSet__c>> mapPpiTableIdToDataSetList =
                new Map<Id,List<PPITableDataSet__c>>();
            Map<Id, List<PPITableLine__c>> mapSurveyVersionIdtoTableLines =
                new Map<Id, List<PPITableLine__c>>();
            Map<Id, List<PPITableLine__c>> mapPpiTableIdToLines =
                new Map<Id, List<PPITableLine__c>>();
            Set<Id> surveyVersionIds = new Set<Id>();
            Set<Id> insertedPpiResultIds = new Set<Id>();

            for (PpiResult__c ppiResult : insertedPpiResultList) {
                surveyVersionIds.add(ppiResult.PpiTemplate__c);
                insertedPpiResultIds.add(ppiResult.Id);
            }

            List<PPITableDataSet__c> ppiTableDataSetList =
                new PpiTableDataSetSelector().getForSurveyVersion(surveyVersionIds);

            // Create map with PpiTable Id and list of associated PpiTableDataSets
            setPpiTableIdToDataSetListMap(ppiTableDataSetList, mapPpiTableIdToDataSetList);

            // Create map with PpiTable Id and list of associated Table lines
            setPpiTableIdToLinesMap(mapPpiTableIdToDataSetList.keySet(), mapPpiTableIdToLines);

            // Create map with SurveyVersion Id and list of Table lines
            setSurveyVersionIdToLinesMap(
                ppiTableDataSetList,
                mapPpiTableIdToLines,
                mapSurveyVersionIdtoTableLines
            );

            // Create submission ppi records only for successfully inserted Ppi Result records
            // Fetch the ppiResult records again as formula field can only be used when queried
            for (PpiResult__c ppiResult :
                    (List<PpiResult__c>)
                        new PpiResultSelector().getRecordsById(insertedPpiResultIds)) {
                if (mapSurveyVersionIdtoTableLines.containsKey(ppiResult.PpiTemplate__c)) {
                    submissionPpiData.addAll(calculateProbabilities(
                        ppiResult,
                        mapSurveyVersionIdtoTableLines.get(ppiResult.PpiTemplate__c)
                    ));
                }
            }

            // Insert SubmissionPpi data in database
            if (!submissionPpiData.isEmpty()) {
                SubmissionPpiAssociationDomain submissionPpiAssociationDomainInstance =
                    new SubmissionPpiAssociationDomain.Constructor().constructWithRecords(
                        submissionPpiData
                    );
                submissionPpiAssociationDomainInstance.insertRecords();
            }
        } catch (Exception genericException) {
            throw new PpiResultTHException(genericException.getMessage());
        }
    }

    /**
     * Method to create a map with parent PpiTable's Id as key along with its linked dataset list
     */
    @TestVisible
    private static void setPpiTableIdToDataSetListMap(
            List<PPITableDataSet__c> ppiTableDataSetList,
            Map<Id, List<PPITableDataSet__c>> mapPpiTableIdToDataSetList
    ) {
        for (PPITableDataSet__c dataSet : ppiTableDataSetList) {
            List<PPITableDataSet__c> dataSetsList =
                mapPpiTableIdToDataSetList.get(dataSet.PPITable__c);

            if (dataSetsList == null) {
                dataSetsList = new List<PPITableDataSet__c>();
                mapPpiTableIdToDataSetList.put(
                    dataSet.PPITable__c,
                    dataSetsList
                );
            }
            dataSetsList.add(dataSet);
        }
    }

    /**
     * Method to create a map with parent PpiTable's Id as key along with list of its
     * linked table lines
     */
    @TestVisible
    private static void setPpiTableIdToLinesMap(
            Set<Id> ppiTableIds,
            Map<Id, List<PPITableLine__c>> mapPpiTableIdToLines
    ) {
        for (PPITableLine__c ppiTableLine :
                new PpiTableLineSelector().getForPpiTableIds(ppiTableIds)
        ) {
            List<PPITableLine__c> tableLines =
                mapPpiTableIdToLines.get(ppiTableLine.PPITable__c);

            if (tableLines == null) {
                tableLines = new List<PPITableLine__c>();
                mapPpiTableIdToLines.put(
                    ppiTableLine.PPITable__c,
                    tableLines
                );
            }
            tableLines.add(ppiTableLine);
        }
    }

    /**
     * Method to create a map with parent SurveyVersion's Id as key along with list of its
     * linked table lines
     */
    @TestVisible
    private static void setSurveyVersionIdToLinesMap(
            List<PPITableDataSet__c> ppiTableDataSetList,
            Map<Id, List<PPITableLine__c>> mapPpiTableIdToLines,
            Map<Id, List<PPITableLine__c>> mapSurveyVersionIdtoTableLines
    ) {
        for (PPITableDataSet__c dataSet : ppiTableDataSetList) {
            List<PPITableLine__c> tableLines =
                mapSurveyVersionIdtoTableLines.get(dataSet.SurveyVersion__c);

            if (tableLines == null) {
                tableLines = new List<PPITableLine__c>();
                mapSurveyVersionIdtoTableLines.put(
                    dataSet.SurveyVersion__c,
                    tableLines
                );
            }
            tableLines.addAll(mapPpiTableIdToLines.get(dataSet.PPITable__c));
        }
    }

    /**
     * Method to calculate probabilities and create Submission Ppi data accordingly
     */
    @TestVisible
    private static List<SubmissionPpiAssociation__c> calculateProbabilities(
            PpiResult__c ppiResult,
            List<PPITableLine__c> ppiTableLines
    ) {
        List<SubmissionPpiAssociation__c> submissionPpiDataList =
            new List<SubmissionPpiAssociation__c>();

        for (PPITableLine__c tableLine : ppiTableLines) {
            if (ppiResult.Ppiscore__c >= tableLine.From__c &&
                    ppiResult.Ppiscore__c <= tableLine.To__c
            ) {
                submissionPpiDataList.add(
                    SubmissionPpiAssociationDomain.createRecord(
                        ppiResult,
                        tableLine
                    )
                );
            }
        }
        return submissionPpiDataList;
    }

    /**
     * Exception class for errors found in trigger handler
     */
    public class PpiResultTHException extends BaseException {
        public PpiResultTHException(String message, String[] args) {
            super(message, args);
        }
    }
}