src/objects/PpiResult__c.object
<CustomObject>
    <description>Stores the results of a PPI survey. This is a snapshot in time so the demographic data in here may not actually reflect the current state but rather reflects the state at the time the survey was conducted.
Lookups to custom objects can be added to allow for reporting against custom data gathered alongside the PPI. Individual fields can also be added to allow for the same</description>
        <fields>
        <fullName>UniqueKey__c</fullName>
        <label>UniqueKey</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>PPI Result</label>
    <nameField>
        <displayFormat>PPIR-{0000000000}</displayFormat>
        <label>PPI Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPI Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SubmissionPpiAssociation__c.object
<CustomObject>
    <fields>
        <fullName>PpiResult__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The PPI Result record that this value belongs to</description>
        <label>PPI Result</label>
        <referenceTo>PpiResult__c</referenceTo>
        <relationshipLabel>Submission PPI Associations</relationshipLabel>
        <relationshipName>Submission_Ppi_Associations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Submission PPI Association</label>
    <nameField>
        <displayFormat>SPA-{0000000000}</displayFormat>
        <label>Junction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission PPI Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PpiResultTHTest.cls
/**
 * Test class for the PpiResultTH
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author - Aditi Satpute
 */
@isTest
public with sharing class PpiResultTHTest {

    /**
     * Test method for validating calculate Probabilities
     */
    static testMethod void testCalculateProbabilities() {
        PpiDataSubmissionServiceTest.setUpTestData();

        List<PpiResult__c> ppiResultList =
            new PpiResultSelector().getAllWithSyncValue(
                PpiDataSubmissionServiceTest.ppiResultIds,
                false
            );

        System.assertEquals(2, ppiResultList.size());

        Test.startTest();
        List<SubmissionPpiAssociation__c> submissionPpiDataList =
            PpiResultTH.calculateProbabilities(
                ppiResultList[0],
                PpiDataSubmissionServiceTest.tableLines
            );
        Test.stopTest();

        System.assert(
            submissionPpiDataList != null,
            'Submission Ppi records not created properly'
        );
        System.assertEquals(1, submissionPpiDataList.size());
    }

    /**
     * Test method for validating insertion of Submission Ppi Data
     */
    static testMethod void testSaveSubmissionPpiData() {
        PpiDataSubmissionServiceTest.setUpTestData();
        Set<String> ppiResultRecordIds = new Set<String>();
        List<PpiResult__c> ppiResultList =
            new PpiResultSelector().getAllWithSyncValue(
                PpiDataSubmissionServiceTest.ppiResultIds,
                false
            );

        System.assertEquals(2, ppiResultList.size());

        for (PpiResult__c ppiResult : ppiResultList) {
            ppiResultRecordIds.add(ppiResult.Id);
        }

        Test.startTest();
        PpiResultTH.saveSubmissionPpiData(ppiResultList);
        Test.stopTest();

        List<SubmissionPpiAssociation__c> insertedSubmissionPpiDataList =
            new SubmissionPpiAssociationSelector().getForPpiResult(ppiResultRecordIds);

        System.assert(
            insertedSubmissionPpiDataList != null,
            'Submission Ppi records not created properly'
        );
        System.assertEquals(4, insertedSubmissionPpiDataList.size());
    }

    /**
     * Test method for validating insertion of PpiResult with Unique Key
     */
    static testMethod void testBeforeInsertOnPpiResult() {
        Test.startTest();
        PpiDataSubmissionServiceTest.setUpTestData();
        Test.stopTest();

        Set<String> ppiResultRecordIds = new Set<String>();
        List<PpiResult__c> ppiResultList =
            new PpiResultSelector().getAllWithSyncValue(
                PpiDataSubmissionServiceTest.ppiResultIds,
                false
            );

        // PpiResult records are inserted properly in database
        System.assertEquals(2, ppiResultList.size());
        System.assert(ppiResultList[0].UniqueKey__c != null, 'UniqueKey not set properly');

    }

    /**
     * Test method for validating insertion of PpiResult with Submission Ppi Data
     */
    static testMethod void testAfterInsertOnPpiResult() {
        Test.startTest();
        PpiDataSubmissionServiceTest.setUpTestData();
        Test.stopTest();

        Set<String> ppiResultRecordIds = new Set<String>();
        List<PpiResult__c> ppiResultList =
            new PpiResultSelector().getAllWithSyncValue(
                PpiDataSubmissionServiceTest.ppiResultIds,
                false
            );

        // PpiResult records are inserted properly in database
        System.assertEquals(2, ppiResultList.size());

        for (PpiResult__c ppiResult : ppiResultList) {
            ppiResultRecordIds.add(ppiResult.Id);
        }
        List<SubmissionPpiAssociation__c> insertedSubmissionPpiDataList =
            new SubmissionPpiAssociationSelector().getForPpiResult(ppiResultRecordIds);

        System.assert(
            insertedSubmissionPpiDataList != null,
            'Submission Ppi records not created properly'
        );

        // SubmissionPpiAssociation records are inserted properly in database
        System.assertEquals(2, insertedSubmissionPpiDataList.size());
    }
}