src/objects/PpiResult__c.object
<CustomObject>
    <description>Stores the results of a PPI survey. This is a snapshot in time so the demographic data in here may not actually reflect the current state but rather reflects the state at the time the survey was conducted.
Lookups to custom objects can be added to allow for reporting against custom data gathered alongside the PPI. Individual fields can also be added to allow for the same</description>
    <label>PPI Result</label>
    <nameField>
        <displayFormat>PPIR-{0000000000}</displayFormat>
        <label>PPI Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPI Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PPITableLine__c.object
<CustomObject>
    <description>Represents a bucket in the Poverty Table. Used to convert raw score in to a probability</description>
    <label>PPI Table Line</label>
    <nameField>
        <displayFormat>PPIL-{00000000}</displayFormat>
        <label>PPI Table Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPI Table Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Submission__c.object
<CustomObject>
    <label>Submission</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SubmissionPpiAssociation__c.object
<CustomObject>
    <fields>
        <fullName>PpiResult__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The PPI Result record that this value belongs to</description>
        <label>PPI Result</label>
        <referenceTo>PpiResult__c</referenceTo>
        <relationshipLabel>Submission PPI Associations</relationshipLabel>
        <relationshipName>Submission_Ppi_Associations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PpiTableLine__c</fullName>
        <description>The PPI Table line that this record maps to</description>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>PPI Table Line</label>
        <referenceTo>PPITableLine__c</referenceTo>
        <relationshipLabel>Submission PPI Associations</relationshipLabel>
        <relationshipName>Submission_Ppi_Associations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <description>The Submission record that this value belongs to</description>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission</label>
        <referenceTo>Submission__c</referenceTo>
        <relationshipLabel>Submission PPI Associations</relationshipLabel>
        <relationshipName>Submission_Ppi_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission PPI Association</label>
    <nameField>
        <displayFormat>SPA-{0000000000}</displayFormat>
        <label>Junction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission PPI Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubmissionPpiAssociationDomain.cls
/**
 * Domain class for the SubmissionPpiAssociation object
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author - Aditi Satpute
 */
public with sharing class SubmissionPpiAssociationDomain extends SObjectDomain {

    public SubmissionPpiAssociationDomain() {
        super(SubmissionPpiAssociation__c.SObjectType);
    }

    public SubmissionPpiAssociationDomain(List<SubmissionPpiAssociation__c> sObjects) {
        super(sObjects);
    }

    /**
     * Method to create Submission Ppi Association Record
     */
    public static SubmissionPpiAssociation__c createRecord(
            PpiResult__c ppiResult,
            PPITableLine__c tableLine
    ) {
        GenericObjectCreator submissionPpiDataCreator =
            new GenericObjectCreator(SubmissionPpiAssociation__c.SObjectType);
        submissionPpiDataCreator.checkObjectAccessible();
        submissionPpiDataCreator.checkFieldsAccessible(
            new List<Schema.SObjectField> {
                SubmissionPpiAssociation__c.PpiResult__c,
                SubmissionPpiAssociation__c.PpiTableLine__c
            }
        );

        SubmissionPpiAssociation__c newSubmissionPpiDataInstance =
            (SubmissionPpiAssociation__c) submissionPpiDataCreator.createNewRecord();
        submissionPpiDataCreator.populateFields(
            newSubmissionPpiDataInstance,
                new Map<Schema.SObjectField, Object>{
                    SubmissionPpiAssociation__c.PpiResult__c => ppiResult.Id,
                    SubmissionPpiAssociation__c.PpiTableLine__c => tableLine.Id
                }
            );
        return newSubmissionPpiDataInstance;
    }

    /**
     * Method to link Submission record to calculated SubmissionPpiAssociations for
     * newly created PpiResult records
     */
    public void setSubmissionIdForPpiAssociations(
            PpiResult__c ppiResultInstance,
            Id submissionId
    ) {
        GenericObjectCreator submissionPpiAssociationCreator =
                new GenericObjectCreator(SubmissionPpiAssociation__c.SObjectType);
        submissionPpiAssociationCreator.checkObjectAccessible();
        submissionPpiAssociationCreator.checkObjectUpdateable();
        submissionPpiAssociationCreator.checkFieldsAccessible(new List<Schema.SObjectField> {
            SubmissionPpiAssociation__c.Submission__c
        });
        List<SubmissionPpiAssociation__c> ppiAssociationsToUpdate =
            new List<SubmissionPpiAssociation__c>();

        for (SubmissionPpiAssociation__c ppiAssociationInstance :
                new SubmissionPpiAssociationSelector().getForPpiResult(
                    new Set<String> {ppiResultInstance.Id}
                )
        ) {
            submissionPpiAssociationCreator.populateField(
                ppiAssociationInstance,
                SubmissionPpiAssociation__c.Submission__c,
                submissionId
            );
            ppiAssociationsToUpdate.add(ppiAssociationInstance);
        }

        this.addRecords(ppiAssociationsToUpdate);
        this.updateRecords();
    }

    /**
     * IDomainConstructor class for Separation of Concerns
     */
    public class Constructor implements SObjectDomain.IDomainConstructor {
        public SubmissionPpiAssociationDomain constructWithRecords(List<SObject> sObjectList) {
            return new SubmissionPpiAssociationDomain(sObjectList);
        }
        public SubmissionPpiAssociationDomain constructEmpty() {
            return new SubmissionPpiAssociationDomain ();
        }
    }
}