src/objects/PPITable__c.object
<CustomObject>
    <description>The PPI scoring table</description>
    <label>PPI Table</label>
    <nameField>
        <label>PPI Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPI Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PPITableDataSet__c.object
<CustomObject>
    <description>A junction object that links a Survey Version to a PPI Table. This allows for a m-m relationship between these two objects so that a PPI Table can be referenced by a Survey Version as opposed to needing to be copied. All fields on this object are deprecated and moved to PPI Table except for Survey Version and PPI Table. Survey is kept here as it cannot be moved. It is not needed any more</description>
    <fields>
        <fullName>PPITable__c</fullName>
        <label>PPI Table</label>
        <referenceTo>PPITable__c</referenceTo>
        <relationshipLabel>PPI Table Data Sets</relationshipLabel>
        <relationshipName>PPI_Table_Data_Sets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>The Survey that this Data Set links to. Not really needed but as we cannot remove fields from a package yet this is kept. When allowed will be removed and only the Survey Version will be used. Do not reference to this field in any code</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>PPI Table Data Sets</relationshipLabel>
        <relationshipName>PPI_Table_Data_Sets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SurveyVersion__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Survey Version that this junction object is for</description>
        <label>Survey Version</label>
        <referenceTo>SurveyVersion__c</referenceTo>
        <relationshipLabel>Survey Version</relationshipLabel>
        <relationshipName>Survey_Version</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>PPI Table Data Set</label>
    <nameField>
        <displayFormat>PTDS-{00000000}</displayFormat>
        <label>PPI Table Data Set Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPI Table Data Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyVersions</relationshipLabel>
        <relationshipName>SurveyVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PpiTableDataSetDomain.cls
/**
 * Domain class for the PPITableDataSet__c object
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author Aditi Satpute
 */
public with sharing class PpiTableDataSetDomain extends SObjectDomain {

    public PpiTableDataSetDomain() {
        super(PPITableDataSet__c.SObjectType);
    }

    public PpiTableDataSetDomain(List<PPITableDataSet__c> sObjects) {
        super(sObjects);
    }

    /**
     * Create new PpiTableDataSet record related to each ppiTable id and Survey
     * TODO - Remove this and use addRecordsForPpiTables() below
     */
    public PPITableDataSet__c createRecord(
            Id ppiTableInstanceId,
            Survey__c survey
    ) {
        GenericObjectCreator ppiTableDataSetCreator =
            new GenericObjectCreator(PPITableDataSet__c.SObjectType);
        PPITableDataSet__c newDataSet =
                (PPITableDataSet__c) ppiTableDataSetCreator.createNewRecord();
        ppiTableDataSetCreator.populateFields(
            newDataSet,
            new Map<Schema.SObjectField, Object> {
                PPITableDataSet__c.PPITable__c => ppiTableInstanceId,
                PPITableDataSet__c.Survey__c => survey.Id,
                PPITableDataSet__c.SurveyVersion__c => survey.SurveyVersions__r[0].Id
            }
        );
        return newDataSet;
    }

    /**
     * Create a record
     */
    public PPITableDataSet__c createRecord() {
        return (PPITableDataSet__c) this.genericObjectCreator.createNewRecord();
    }

    public UnitOfWork addRecordsForPpiTables(
            List<PPITable__c> localTables,
            UnitOfWork unitOfWork,
            Survey__c survey,
            SurveyVersion__c version
    ) {
        unitOfWork.addToInsertionOrder(PPITableDataSet__c.getSObjectType(), 1);
        for (PPITable__c localTable : localTables) {
            PPITableDataSet__c dataSet = this.createRecord();
            unitOfWork.addToInsertList(
                dataSet,
                PPITableDataSet__c.SurveyVersion__c,
                version,
                1
            );
            unitOfWork.createRelationship(
                dataSet,
                PPITableDataSet__c.Survey__c,
                survey,
                1
            );
            unitOfWork.createRelationship(
                dataSet,
                PPITableDataSet__c.PPITable__c,
                localTable,
                1
            );
            this.addRecord(dataSet);
        }
        return unitOfWork;
    }

    /**
     * Create a map of each ppi table data Sets with PpiTable PovertyLine Name as its Key
     */
    public static Map<Id, PPITableDataSet__c> getPpiTablePovertyLineToDataSetMap(
            Set<String> ppiPovertyLineNames,
            Survey__c survey
    ) {
        Map<Id, PPITableDataSet__c> mapPpiTableWithDataSets =
            new Map<Id, PPITableDataSet__c>();
        for (PPITableDataSet__c dataSet :
            new PpiTableDataSetSelector().getForSurveyVersionAndPovertyLineNames(
                survey.SurveyVersions__r[0].Id,
                ppiPovertyLineNames
            )
        ) {
            mapPpiTableWithDataSets.put(dataSet.PPITable__c, dataSet);
        }
        return mapPpiTableWithDataSets;
    }

    /**
     * IDomainConstructor class for Separation of Concerns
     */
    public class Constructor implements SObjectDomain.IDomainConstructor {
        public PpiTableDataSetDomain constructWithRecords(List<SObject> sObjectList) {
            return new PpiTableDataSetDomain(sObjectList);
        }
        public PpiTableDataSetDomain constructEmpty() {
            return new PpiTableDataSetDomain();
        }
    }
}