src/objects/PPITable__c.object
<CustomObject>
    <description>The PPI scoring table</description>
    <fields>
        <fullName>PovertyLine__c</fullName>
        <description>The display name of PPI Table</description>
        <label>Poverty Line</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>PPI Table</label>
    <nameField>
        <label>PPI Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPI Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PPITableDataSet__c.object
<CustomObject>
    <description>A junction object that links a Survey Version to a PPI Table. This allows for a m-m relationship between these two objects so that a PPI Table can be referenced by a Survey Version as opposed to needing to be copied. All fields on this object are deprecated and moved to PPI Table except for Survey Version and PPI Table. Survey is kept here as it cannot be moved. It is not needed any more</description>
    <fields>
        <fullName>PPITable__c</fullName>
        <label>PPI Table</label>
        <referenceTo>PPITable__c</referenceTo>
        <relationshipLabel>PPI Table Data Sets</relationshipLabel>
        <relationshipName>PPI_Table_Data_Sets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>The Survey that this Data Set links to. Not really needed but as we cannot remove fields from a package yet this is kept. When allowed will be removed and only the Survey Version will be used. Do not reference to this field in any code</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>PPI Table Data Sets</relationshipLabel>
        <relationshipName>PPI_Table_Data_Sets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SurveyVersion__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Survey Version that this junction object is for</description>
        <label>Survey Version</label>
        <referenceTo>SurveyVersion__c</referenceTo>
        <relationshipLabel>Survey Version</relationshipLabel>
        <relationshipName>Survey_Version</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>PPI Table Data Set</label>
    <nameField>
        <displayFormat>PTDS-{00000000}</displayFormat>
        <label>PPI Table Data Set Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPI Table Data Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyVersions</relationshipLabel>
        <relationshipName>SurveyVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PpiTableDataSetSelectorTest.cls
/**
 * Test class for the PpiTableDataSetSelector
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author - Aditi Satpute
 */
@isTest
public with sharing class PpiTableDataSetSelectorTest {

    private static Survey__c survey;
    private static SurveyVersion__c surveyVersion;
    private static List<PPITable__c> ppiTables;
    private static List<PPITableDataSet__c> ppiDataSets;

    /**
     * Test class for fetching ppiTableDataSets for specified SurveyVersionIds
     */
    static testMethod void testDataSetsForSurveyVersionIds() {
        TestSurveyData testSurvey1 = TestSurveyData.createStandardTestSurvey(null, false);
        TestSurveyData testSurvey2 = TestSurveyData.createStandardTestSurvey(null, false);

        // Create data for PPI related Tables
        List<PPITable__c> ppiTablesList = PpiTableDomainTest.createMultiplePpiTables(3);
        UnitOfWork unitOfWork = new UnitOfWork();
        for (PPITable__c ppiTable : ppiTablesList) {
            PpiTableDomainTest.addPpiTableToUnitOfWork(
                ppiTable,
                null,
                unitOfWork
            );
        }
        PpiTableDataSetDomain domain = new PpiTableDataSetDomain();
        unitOfWork = domain.addRecordsForPpiTables(
            ppiTablesList,
            unitOfWork,
            testSurvey1.testSurvey,
            testSurvey1.testSurveyVersion
        );
        unitOfWork = domain.addRecordsForPpiTables(
            ppiTablesList,
            unitOfWork,
            testSurvey2.testSurvey,
            testSurvey2.testSurveyVersion
        );
        unitOfWork.commitWork();
        Test.startTest();
        PpiTableDataSetSelector dataSetSelectorInstance = new PpiTableDataSetSelector();
        List<PPITableDataSet__c> dataSets = dataSetSelectorInstance.getForSurveyVersion(
            new Set<Id> {
                testSurvey1.testSurveyVersion.Id,
                testSurvey2.testSurveyVersion.Id
            }
        );
        Test.stopTest();

        // PpiTableDataSet records are fetched properly
        System.assertEquals(6, dataSets.size());
    }

    /**
     * Test method for fetching PpiTableDataSets with specified SurveyVersionId
     * and PpiTablePovertyLine Names
     */
    static testMethod void testFetchDataForSurveyVersionIdAndTablePovertyLineNames() {
        createTestData();

        Test.startTest();
        PpiTableDataSetSelector dataSetSelectorInstance = new PpiTableDataSetSelector();
        List<PPITableDataSet__c> dataSets =
            dataSetSelectorInstance.getForSurveyVersionAndPovertyLineNames(
                surveyVersion.Id,
                new Set<String> {
                    ppiTables[0].PovertyLine__c,
                    ppiTables[1].PovertyLine__c,
                    ppiTables[2].PovertyLine__c
                }
            );
        Test.stopTest();

        // PpiTableDataSet records are fetched properly
        System.assertEquals(
            3,
            dataSets.size(),
            '3 Data sets should be found'
        );
    }

    /**
     * Test method for fetching PpiTableDataSets with specified PpiTable Names
     */
    static testMethod void testFetchDataForTableNames() {
        createTestData();

        Test.startTest();
        List<PPITableDataSet__c> dataSets =
            new PpiTableDataSetSelector().getForPpiTableNames(
                new Set<String> {
                    ppiTables[0].Name,
                    ppiTables[1].Name,
                    ppiTables[2].Name
                }
            );
        Test.stopTest();

        // PpiTableDataSet records are fetched properly
        System.assertEquals(
            3,
            dataSets.size()
        );
    }

    /**
     * Test method for fetching PpiTableDataSets with specified PpiTable name
     */
    static testMethod void testLikePpiTableNames() {
        createTestData();

        Test.startTest();
        List<PPITableDataSet__c> dataSets =
            new PpiTableDataSetSelector().getLikePpiTableNames(
                PpiTableDomainTest.TEST_TABLE_NAME
            );
        Test.stopTest();

        // PpiTableDataSet records are fetched properly
        System.assertEquals(
            3,
            dataSets.size()
        );
    }

    /**
     * Method to create all Look Up Tables related data
     */
    private static void createTestData() {
        ppiDataSets = new List<PPITableDataSet__c>();
        survey = SurveyDOTest.createInsertedPpiTemplate();
        survey = new SurveySelector().getWithSurveyVersionAndQuestions(survey.Id);

        System.assert(
            survey.SurveyVersions__r.size() > 0,
            'Survey Version records not fetched properly'
        );
        surveyVersion = survey.SurveyVersions__r[0];

        // Create data for Ppi related Tables
        ppiTables = PpiTableDomainTest.insertMultiplePpiTables(3);

        UnitOfWork unitOfWork = new UnitOfWork();
        for (PPITable__c table : ppiTables) {
            PPITableDataSet__c dataSet = PpiTableDataSetDomainTest.createPpiTableDataSet();
            unitOfWork = PpiTableDataSetDomainTest.addPpiTableDataSetToUnitOfWork(
                dataSet,
                table,
                survey,
                surveyVersion,
                unitOfWork
            );
            ppiDataSets.add(dataSet);
        }
        unitOfWork.commitWork();
    }
}