src/objects/PPITable__c.object
<CustomObject>
    <description>The PPI scoring table</description>
    <label>PPI Table</label>
    <nameField>
        <label>PPI Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPI Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PPITableLine__c.object
<CustomObject>
    <description>Represents a bucket in the Poverty Table. Used to convert raw score in to a probability</description>
    <fields>
        <fullName>From__c</fullName>
        <description>Scoring range start score</description>
        <label>From</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PpiTable__c</fullName>
        <description>The PPI Table that the line is for</description>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PPI Table</label>
        <referenceTo>PPITable__c</referenceTo>
        <relationshipLabel>PPI Table</relationshipLabel>
        <relationshipName>PPI_Table</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <description>Probability of being below the poverty line for the specified scoring range</description>
        <label>Probability</label>
        <precision>4</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <description>Scoring range finish score</description>
        <label>To</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PPI Table Line</label>
    <nameField>
        <displayFormat>PPIL-{00000000}</displayFormat>
        <label>PPI Table Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPI Table Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PpiTableLineDomain.cls
/**
 * Domain class for the PPITableLine__c object
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author Aditi Satpute
 * @author Owen Davies - odavies@grameenfoundation.org
 */
public with sharing class PpiTableLineDomain extends SObjectDomain {

    public PpiTableLineDomain() {
        super(PPITableLine__c.SObjectType);
    }

    public PpiTableLineDomain(List<PPITableLine__c> sObjects) {
        super(sObjects);
    }

    /**
     * Create new Ppi Table Line record
     */
    public PPITableLine__c createRecord(
            Id ppiTableInstanceId,
            Decimal fromValue,
            Decimal toValue,
            Decimal probability
    ) {
        GenericObjectCreator ppiTableLineCreator =
            new GenericObjectCreator(PPITableLine__c.SObjectType);
        PPITableLine__c ppiTableLine =
                (PPITableLine__c) ppiTableLineCreator.createNewRecord();
        ppiTableLineCreator.populateFields(
            ppiTableLine,
            new Map<Schema.SObjectField, Object> {
                PPITableLine__c.PPITable__c => ppiTableInstanceId,
                PPITableLine__c.From__c => fromValue,
                PPITableLine__c.To__c => toValue,
                PPITableLine__c.Probability__c => probability
            }
        );
        return ppiTableLine;
    }

    /**
     * IDomainConstructor class for Separation of Concerns
     */
    public class Constructor implements SObjectDomain.IDomainConstructor {
        public PpiTableLineDomain constructWithRecords(List<SObject> sObjectList) {
            return new PpiTableLineDomain(sObjectList);
        }
        public PpiTableLineDomain constructEmpty() {
            return new PpiTableLineDomain();
        }
    }
}