src/objects/PPITable__c.object
<CustomObject>
    <description>The PPI scoring table</description>
    <fields>
        <fullName>RemoteId__c</fullName>
        <description>The Id of PPI Table as it is in the org that the table was downloaded from</description>
        <externalId>true</externalId>
        <label>Remote Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyLibrary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Survey Library that the PPI Table was downloaded from</description>
        <label>Remote Library</label>
        <referenceTo>SurveyLibrary__c</referenceTo>
        <relationshipLabel>Survey Library</relationshipLabel>
        <relationshipName>Survey_Library</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PPI Table</label>
    <nameField>
        <label>PPI Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PPI Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PPITableDataSet__c.object
<CustomObject>
    <description>A junction object that links a Survey Version to a PPI Table. This allows for a m-m relationship between these two objects so that a PPI Table can be referenced by a Survey Version as opposed to needing to be copied. All fields on this object are deprecated and moved to PPI Table except for Survey Version and PPI Table. Survey is kept here as it cannot be moved. It is not needed any more</description>
    <fields>
        <fullName>PPITable__c</fullName>
        <label>PPI Table</label>
        <referenceTo>PPITable__c</referenceTo>
        <relationshipLabel>PPI Table Data Sets</relationshipLabel>
        <relationshipName>PPI_Table_Data_Sets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>The Survey that this Data Set links to. Not really needed but as we cannot remove fields from a package yet this is kept. When allowed will be removed and only the Survey Version will be used. Do not reference to this field in any code</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>PPI Table Data Sets</relationshipLabel>
        <relationshipName>PPI_Table_Data_Sets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PPI Table Data Set</label>
    <nameField>
        <displayFormat>PTDS-{00000000}</displayFormat>
        <label>PPI Table Data Set Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPI Table Data Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PPITableLine__c.object
<CustomObject>
    <description>Represents a bucket in the Poverty Table. Used to convert raw score in to a probability</description>
    <fields>
        <fullName>From__c</fullName>
        <description>Scoring range start score</description>
        <label>From</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PpiTable__c</fullName>
        <description>The PPI Table that the line is for</description>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PPI Table</label>
        <referenceTo>PPITable__c</referenceTo>
        <relationshipLabel>PPI Table</relationshipLabel>
        <relationshipName>PPI_Table</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PPITableDataSet__c</fullName>
        <description>Field is deprecated. Use PpiTable__c instead. Set to null in all future PPITableLine records. Leaving existing values to allow for backwards compatibility</description>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PPI Table Data Set</label>
        <referenceTo>PPITableDataSet__c</referenceTo>
        <relationshipLabel>PPI Table Lines</relationshipLabel>
        <relationshipName>PPI_Table_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <description>Probability of being below the poverty line for the specified scoring range</description>
        <label>Probability</label>
        <precision>4</precision>
        <required>true</required>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>RemoteId__c</fullName>
        <description>The Id of PPI Table Line as it is in the org that the table was downloaded from</description>
        <externalId>true</externalId>
        <label>Remote Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyLibrary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Survey Library that the PPI Table was downloaded from</description>
        <label>Remote Library</label>
        <referenceTo>SurveyLibrary__c</referenceTo>
        <relationshipLabel>PPI Table Line</relationshipLabel>
        <relationshipName>PPI_Table_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <description>Scoring range finish score</description>
        <label>To</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PPI Table Line</label>
    <nameField>
        <displayFormat>PPIL-{00000000}</displayFormat>
        <label>PPI Table Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPI Table Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>RemoteId__c</fullName>
        <description>The Id of Survey as it is in the org that the survey was downloaded from</description>
        <externalId>true</externalId>
        <label>Remote Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyLibrary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The survey library that the survey was downloaded from. Allows easy update</description>
        <label>Survey Library</label>
        <referenceTo>SurveyLibrary__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyLibrary__c.object
<CustomObject>
    <description>Stores the connection details for a library on another server that this org can download surveys from</description>
    <label>Survey Library</label>
    <nameField>
        <label>Survey Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PpiTableLineSelector.cls
/**
 * Selector class for the PPITableLine__c object
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author Aditi Satpute
 * @author Owen Davies - odavies@grameenfoundation.org
 */
public with sharing class PpiTableLineSelector extends SObjectSelector {

    public Schema.SObjectType getSObjectType() {
        return PPITableLine__c.sObjectType;
    }

    public List<Schema.SObjectField> getDefaultSelectFields() {
        return new List<Schema.SObjectField>{
            PPITableLine__c.Id,
            PPITableLine__c.Name,
            PPITableLine__c.From__c,
            PPITableLine__c.PPITable__c,
            PPITableLine__c.PPITableDataSet__c,
            PPITableLine__c.Probability__c,
            PPITableLine__c.RemoteId__c,
            PPITableLine__c.SurveyLibrary__c,
            PPITableLine__c.To__c
        };
    }

    public String pathToJobFiltering() {
        return null;
    }

    /**
     * Get the list of PpiTableLine records for the specified ppi table Ids
     */
    public List<PPITableLine__c> getForPpiTableIds(Set<Id> ppiTableIds) {
        this.createInWhereClauseForPpiTableIds(ppiTableIds);
        return
            (List<PPITableLine__c>)
                runSoqlQueryDbFullAccess(SObjectSelector.AND_OPERATOR, null);
    }


    /**
     * Get the table lines related to PPITable records
     */
    public List<PPITableLine__c> getForPpiTables(List<PPITable__c> ppiTables) {
        Set<String> tableIds = new Set<String>();
        for (PPITable__c table : ppiTables) {
            tableIds.add(table.Id);
        }
        return getForPpiTables(tableIds);
    }

    /**
     * Get the list of PPI table line records for the specified ppi table ids
     */
    public List<PPITableLine__c> getForPpiTables(Set<String> ppiTableIds) {
        this.createPpiTableWhereClause(ppiTableIds);
        return
            (List<PPITableLine__c>)
                runSoqlQueryDbFullAccess(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Get the list of Ppi table line records for the specified ppi tables names
     */
    public List<PPITableLine__c> getForPpiTableNames(Set<String> ppiTableNames) {
        this.createInWhereClauseForPpiTableNames(ppiTableNames);
        return
            (List<PPITableLine__c>)
                runSoqlQueryDbFullAccess(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Get the list of PpiTableLine records for the specified table name
     */
    public List<PPITableLine__c> getLikePpiTableNames(String ppiTableName) {
        this.createLikePpiTableNameWhereClause(ppiTableName);
        return
            (List<PPITableLine__c>)
                runSoqlQueryDbFullAccess(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Get all Ppi Table Line records for specified old Survey ids
     */
    public List<PPITableLine__c> getAllForOldSurveyIds(Set<Id> setSurveyIds) {
        this.getMainQueryBuilder().addRelationshipToSelect(
            new List<Schema.SObjectField> {
                PPITableLine__c.PPITableDataSet__c,
                PPITableDataSet__c.PPITable__c
            }
        );
        this.createInWhereClauseForSurveyIds(setSurveyIds);
        this.setMainLimitAmount(Limits.getLimitQueryRows());
        return
            (List<PPITableLine__c>)
                runSoqlQueryDbFullAccess(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Create where clause with survey ids
     */
    private void createInWhereClauseForSurveyIds(Set<Id> setSurveyIds) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardInWhereClause(
                createSurveyLookUpUsingPpiTableDataSet(),
                SObjectSelector.IN_OPERATOR,
                setSurveyIds
            )
        );
    }

    /**
     * Create where clause with Ppi Table Ids for main query of PpiTableLine object 
     */
    private void createInWhereClauseForPpiTableIds(Set<Id> ppiTableIds) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardInWhereClause(
                PPITableLine__c.PPITable__c,
                SObjectSelector.IN_OPERATOR,
                ppiTableIds
            )
        );
    }

    /**
     * Create where clause with Ppi Table Names for main query of PpiTableLine object
     */
    private void createInWhereClauseForPpiTableNames(Set<String> ppiTableNames) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardInWhereClause(
                this.getMainQueryBuilder().generateLookUp(
                    new List<Schema.SObjectField> {
                        PPITableLine__c.PPITable__c,
                        PPITable__c.Name
                    }
                ),
                SObjectSelector.IN_OPERATOR,
                ppiTableNames
            )
        );
    }

    /**
     * Create where clause with Name Like Ppitable Name for main query of PpiTableLine object
     */
    private void createLikePpiTableNameWhereClause(String tableName) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateWrappedLikeClause(
                this.getMainQueryBuilder().generateLookUp(
                    new List<Schema.SObjectField> {
                        PPITableLine__c.PPITable__c,
                        PPITable__c.Name
                    }
                ),
                tableName
            )
        );
    }

    /**
     * Create PpiTable where claues for main query of PPITableLine object 
     */
    private void createPpiTableWhereClause(Set<String> ppiTableIds) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardInWhereClause(
                PPITableLine__c.PPITable__c,
                SObjectSelector.IN_OPERATOR,
                ppiTableIds
            )
        );
    }

    /**
     * Create relationship lookup for Survey using Ppi Table Data Set
     */
    private String createSurveyLookUpUsingPpiTableDataSet() {
        return this.getMainQueryBuilder().generateLookUp(
            new List<Schema.SObjectField> {
                PPITableLine__c.PPITableDataSet__c,
                PPITableDataSet__c.Survey__c
            }
        );
    }
}