src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SkipCondition__c.object
<CustomObject>
    <fields>
        <fullName>Condition__c</fullName>
        <description>Condition to apply to the source question value.</description>
        <label>Condition</label>
        <picklist>
            <picklistValues>
                <fullName>Answered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Is</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LesserThan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GreaterThan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InRange</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Negate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determine if the result of the evaluation must be negated (return true instead of false, and back-wise).</description>
        <label>Negate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <description>Question on which this condition is applied</description>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Skip Conditions</relationshipLabel>
        <relationshipName>SkipConditions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SourceQuestion__c</fullName>
        <description>Question whose result will be evaluated to determine if the parent question is shown. This question must be previous to the parent question in the survey.</description>
        <label>SourceQuestion</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Affected Skip Conditions</relationshipLabel>
        <relationshipName>AffectedSkipConditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value to compare against the source question value.</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Skip Condition</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Skip Condition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skip Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SkipConditionSelector.cls
/**
 * Selector class for the SkipCondition__c object
 *
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 *
 * @author Owen Davies - odavies@grameenfoundation.org
 */
public with sharing class SkipConditionSelector extends SObjectSelector {

    public Schema.SObjectType getSObjectType() {
        return SkipCondition__c.sObjectType;
    }

    public List<Schema.SObjectField> getDefaultSelectFields() {
        return new List<Schema.SObjectField>{
            SkipCondition__c.Id,
            SkipCondition__c.Name,
            SkipCondition__c.Condition__c,
            SkipCondition__c.Negate__c,
            SkipCondition__c.Parent__c,
            SkipCondition__c.SourceQuestion__c,
            SkipCondition__c.Value__c
        };
    }

    public String pathToJobFiltering() {
        return null;
    }

    public List<SkipCondition__c> getAllForSurvey(Id surveyId) {
        this.mainQueryBuilder.setSelectClauseWithAllFields();
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                new List<Schema.SObjectField>{
                    SkipCondition__c.SourceQuestion__c,
                    Question__c.Survey__c
                },
                SObjectSelector.EQUALS_OPERATOR,
                surveyId
            )
        );
        return (List<SkipCondition__c>)
            runSoqlQuery(SObjectSelector.AND_OPERATOR, null);
    }
}