src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RemoteId__c</fullName>
        <description>The Id of Question as it is in the org that the survey was downloaded from</description>
        <externalId>true</externalId>
        <label>Remote Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RemoteServerId__c</fullName>
        <description>Deprecated. Use RemoteId__c as it is indexed</description>
        <label>Remote Server Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SurveyLibrary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Survey Library that the Question was downloaded from</description>
        <label>Remote Library</label>
        <referenceTo>SurveyLibrary__c</referenceTo>
        <relationshipLabel>Question</relationshipLabel>
        <relationshipName>Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>repeat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-short</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-long</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-decimal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-datetime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>static-content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>end_of_survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>barcode</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>gps-location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>picture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-select</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-level</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <description>This is the alias of the Survey</description>
        <label>Alias</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Close_Message__c</fullName>
        <label>Message After Submission</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CountryCode__c</fullName>
        <description>The ISO 3166-1 alpha-2 country code</description>
        <label>Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <picklist>
            <picklistValues>
                <fullName>Smartphone</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsCloned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsCloned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the survey is a PPI Survey</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this survey is actually a template. If this is checked then this survey cannot be distributed on its own. It must be included into another survey</description>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LanguageCode__c</fullName>
        <defaultValue>&apos;EN&apos;</defaultValue>
        <label>Language Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PPIDataYear__c</fullName>
        <description>Data year for the PPI survey</description>
        <label>Data Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PpiIdentifier__c</fullName>
        <label>PPI Identifier</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PublishedDate__c</fullName>
        <label>Published Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RemoteId__c</fullName>
        <description>The Id of Survey as it is in the org that the survey was downloaded from</description>
        <externalId>true</externalId>
        <label>Remote Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SurveyLibrary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The survey library that the survey was downloaded from. Allows easy update</description>
        <label>Survey Library</label>
        <referenceTo>SurveyLibrary__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyLibrary__c.object
<CustomObject>
    <description>Stores the connection details for a library on another server that this org can download surveys from</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Information about the library</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the remote library allows downloads of PPI Templates</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this library allows downloads of templates</description>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <label>Survey Library</label>
    <nameField>
        <label>Survey Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Libraries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyMapping__c.object
<CustomObject>
    <fields>
        <fullName>ObjectApiName__c</fullName>
        <description>The Api Name of the parent object of the fields, defined in the related QuestionMappings records, where its going to be store the mapping fields data</description>
        <label>Object Api Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repeat__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated repeated section.</description>
        <label>Repeat</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Survey Mappings</relationshipLabel>
        <relationshipName>Survey_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Mappings</relationshipLabel>
        <relationshipName>Survey_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Mapping</label>
    <nameField>
        <label>SurveyMapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deprecated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyVersions</relationshipLabel>
        <relationshipName>SurveyVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SurveySelector.cls
/**
 * Selector class for the Survey__c object
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author - Aditi Satpute
 * @author - Kaushik Ray
 * @author Owen Davies - odavies@grameenfoundation.org
 * @author - Ketaki Virkar
 */
public with sharing class SurveySelector extends SObjectSelector {

    public Schema.SObjectType getSObjectType() {
        return Survey__c.sObjectType;
    }

    public List<Schema.SObjectField> getDefaultSelectFields() {
        return new List<Schema.SObjectField>{
            Survey__c.Id,
            Survey__c.Name,
            Survey__c.Alias__c,
            Survey__c.CreatedDate,
            Survey__c.Close_Message__c,
            Survey__c.CountryCode__c,
            Survey__c.Description__c,
            Survey__c.Deployment__c,
            Survey__c.IsPPI__c,
            Survey__c.IsTemplate__c,
            Survey__c.LanguageCode__c,
            Survey__c.LastModifiedDate,
            Survey__c.PPIDataYear__c,
            Survey__c.PpiIdentifier__c,
            Survey__c.PublishedDate__c,
            Survey__c.isCloned__c,
            Survey__c.RemoteId__c,
            Survey__c.Status__c,
            Survey__c.Version__c,
            Survey__c.SurveyLibrary__c
        };
    }

    public String pathToJobFiltering() {
        return null;
    }

    public List<Survey__c> getByName(String nameToFetch, String operator) {
        this.addToMainWhereClause(createByNameClause(nameToFetch, operator));
        return (List<Survey__c>)
            runSoqlQueryDbFullAccess(SObjectSelector.AND_OPERATOR, null);
    }

    public List<Survey__c> getByAlias(String aliasToFetch, String operator) {

        this.getMainQueryBuilder().setSelectClause(
            new List<Schema.SObjectField> {Survey__c.Alias__c}
        );
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                Survey__c.Alias__c,
                operator,
                aliasToFetch
            )
        );
        return (List<Survey__c>)
            runSoqlQueryDbFullAccess(SObjectSelector.AND_OPERATOR, null);
    }

    public List<Survey__c> getNameNotForId(String nameToFetch, Id surveyId) {
        this.addToMainWhereClause(createByNameClause(nameToFetch, SObjectSelector.EQUALS_OPERATOR));
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                Survey__c.Id,
                SObjectSelector.NOT_EQUALS_OPERATOR,
                surveyId
            )
        );
        return (List<Survey__c>) runSoqlQueryDbFullAccess(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Get all Non template Surveys By Alias
     */
    public List<Survey__c> getAllByAlias(Set<String> aliases, Boolean isTemplate) {
        this.createAliasWhereClause(aliases);
        this.createIsTemplateWhereClause(isTemplate);
        return
            (List<Survey__c>) runSoqlQuery(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Parent to child query to get the Survey record with Survey Version
     * for given survey Ids
     */
    public List<Survey__c> getWithSurveyVersion(Set<String> surveyIds) {
        this.createSurveyWhereClause(surveyIds);
        buildInnerQueryWithSurveyVersion();
        return
            (List<Survey__c>)
                runSoqlQueryDbFullAccess(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Parent to child query to get the Survey record with Survey Version and Questions
     * for a given survey Id
     */
    public Survey__c getWithSurveyVersionAndQuestions(Id surveyId) {
        this.buildInnerQueryWithSurveyVersion();
        this.buildInnerQueryWithQuestion();
        return (Survey__c) getRecordById(surveyId);
    }

    /**
     * Get specific Survey Instance with Survey Version based on Survey Id
     */
    public Survey__c getSpecificWithSurveyVersion(Id surveyId) {
        this.mainQueryBuilder.setSelectClauseWithAllFields();
        this.buildInnerQueryWithSurveyVersion();
        return (Survey__c) getRecordById(surveyId);
    }

    /**
     * Get All Surveys
     */
    public List<Survey__c> getAllSurveys() {
        this.setMainLimitAmount(Limits.getLimitQueryRows());
        return (List<Survey__c>) runSoqlQuery(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Get Draft Surveys
     */
    public List<Survey__c> getDraftSurveys() {
        this.createStatusWhereClause(SurveyDO.STATUS_DRAFT);
        this.setMainLimitAmount(Limits.getLimitQueryRows());
        return (List<Survey__c>) runSoqlQuery(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Get all Ppi Templates with all related SurveyVersion.
     */
    public List<Survey__c> getPpiTemplatesWithSurveyVersion() {
        this.buildInnerQueryWithSurveyVersion();
        return getPpiTemplatesWithDbFullAccess();
    }

    /**
     * Get all Ppi Templates
     */
    public List<Survey__c> getPpiTemplatesWithDbFullAccess() {
        this.createIsPpiWhereClause(true);
        this.createIsTemplateWhereClause(true);
        return (List<Survey__c>) runSoqlQueryDbFullAccess(SobjectSelector.AND_OPERATOR, null);
    }

    /**
     * Parent to child query to get the Survey record with Survey Mappings
     * for a given survey Ids
     */
    public List<Survey__c> getWithSurveyMappings(Set<Id> surveyIds) {
        this.buildInnerQueryWithSurveyMapping();
        return
            (List<Survey__c>)
                runSoqlQuery(SObjectSelector.AND_OPERATOR, surveyIds);
    }

    /**
     * Method to add Alias value to where clause
     */
    private void createAliasWhereClause(Set<String> aliases) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardInWhereClause(
                Survey__c.Alias__c,
                SObjectSelector.IN_OPERATOR,
                aliases
            )
        );
    }

    private String createByNameClause(String nameToFetch, String operator) {
        return this.getMainQueryBuilder().generateStandardWhereClause(
            Survey__c.Name,
            operator,
            nameToFetch
        );
    }

    /**
     * Method to add IsTemplate__c value to where clause
     */
    private void createIsTemplateWhereClause(Boolean isTemplate) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                Survey__c.IsTemplate__c.getDescribe().getName(),
                SObjectSelector.EQUALS_OPERATOR,
                isTemplate
            )
        );
    }

    /**
     * Method to add IsPpi__c value to where clause
     */
    private void createIsPpiWhereClause(Boolean isPpi) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                Survey__c.IsPpi__c.getDescribe().getName(),
                SObjectSelector.EQUALS_OPERATOR,
                isPpi
            )
        );
    }

    /**
     * Method to add survey Ids to where clause
     */
    private void createSurveyWhereClause(Set<String> surveyIds) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardInWhereClause(
                Survey__c.Id,
                SObjectSelector.IN_OPERATOR,
                surveyIds
            )
        );
    }

    /**
     * Method to add survey Status to where clause
     */
    private void createStatusWhereClause(String status) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                Survey__c.Status__c.getDescribe().getName(),
                SObjectSelector.EQUALS_OPERATOR,
                status
            )
        );
    }

    /**
     * Build the inner query with SurveyVersion
     */
    private void buildInnerQueryWithSurveyVersion() {
        SObjectSelector.SoqlQueryBuilder innerQueryWithSurveyVersion =
            new SObjectSelector.SoqlQueryBuilder(
                'SurveyVersions__r',
                SurveyVersion__c.sObjectType.getDescribe().getName(),
                new List<Schema.SObjectField> {
                    SurveyVersion__c.Id,
                    SurveyVersion__c.Name,
                    SurveyVersion__c.Status__c
                },
                SurveyVersion__c.Version__c.getDescribe().getName() +
                SObjectSelector.DESCENDING_OPERATOR
            );
        innerQueryWithSurveyVersion.setLimitAmount(1);
        this.addInnerSelectQuery(innerQueryWithSurveyVersion);
    }

    /**
     * Build the inner query with Question
     */
    private void buildInnerQueryWithQuestion() {
        SObjectSelector.SoqlQueryBuilder innerQueryWithQuestion =
            new SObjectSelector.SoqlQueryBuilder(
                'Questions__r',
                Question__c.sObjectType.getDescribe().getName(),
                new List<Schema.SObjectField> {
                    Question__c.Id,
                    Question__c.Name,
                    Question__c.RemoteServerId__c,
                    Question__c.Type__c
                },
                Question__c.Id.getDescribe().getName()
            );
        innerQueryWithQuestion.addToWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                Question__c.RemoteServerId__c.getDescribe().getName(),
                SObjectSelector.NOT_EQUALS_OPERATOR,
                ''
            )
        );
        innerQueryWithQuestion.addToWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                Question__c.RemoteServerId__c.getDescribe().getName(),
                SObjectSelector.NOT_EQUALS_OPERATOR,
                SObjectSelector.NULL_VALUE
            )
        );
        this.addInnerSelectQuery(innerQueryWithQuestion);
    }

    /**
     * Build the inner query with SurveyMapping
     */
    private void buildInnerQueryWithSurveyMapping() {
         this.addInnerSelectQuery(
            new SObjectSelector.SoqlQueryBuilder(
                'Survey_Mappings__r',
                SurveyMapping__c.sObjectType.getDescribe().getName(),
                new List<Schema.SObjectField> {
                    SurveyMapping__c.Id,
                    SurveyMapping__c.ObjectApiName__c
                },
                SurveyMapping__c.Id.getDescribe().getName()
            )
        );
    }
}