src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>repeat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-short</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-long</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-decimal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-datetime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>static-content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>end_of_survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>barcode</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>gps-location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>picture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-select</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-level</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuestionMapping__c.object
<CustomObject>
    <fields>
        <fullName>FieldApiName__c</fullName>
        <description>Field api name of the object defined in the parent Survey Answer, where will be saved the answer for the QuestionAnswer&apos;s related question question</description>
        <label>Field Api Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Question Mappings</relationshipLabel>
        <relationshipName>QuestionMappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyMapping__c</fullName>
        <label>Survey Mapping</label>
        <referenceTo>SurveyMapping__c</referenceTo>
        <relationshipLabel>Question Mappings</relationshipLabel>
        <relationshipName>QuestionMappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Question Mapping</label>
    <nameField>
        <label>Question Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyMapping__c.object
<CustomObject>
    <fields>
        <fullName>ObjectApiName__c</fullName>
        <description>The Api Name of the parent object of the fields, defined in the related QuestionMappings records, where its going to be store the mapping fields data</description>
        <label>Object Api Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Mappings</relationshipLabel>
        <relationshipName>Survey_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UseAsInterviewee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use This Mapped Contact As Interviewee</label>
        <type>Checkbox</type>
    </fields>
    <label>Survey Mapping</label>
    <nameField>
        <label>SurveyMapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SurveyMappingAsIntervieweeValidationTest.cls
/**
 *    Test class for SurveyMappingAsIntervieweeValidation
 *    @author Ernesto Quesada
 *
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 *
 */
@isTest
private class SurveyMappingAsIntervieweeValidationTest {

    /*static testMethod void ValidateUseAsIntervieweeTest() {
        // insert a survey with a question
        Survey__c survey      = new Survey__c(Name = 'survey');
        insert survey;
        Question__c sec1      = new Question__c(Survey__c = survey.Id, Type__c = QuestionDO.TYPE_SECTION , Name = 'section', Caption__c = 'caption', Position__c = 1);
        insert sec1;
        Question__c q1        = new Question__c(Survey__c = survey.Id, Parent__c = sec1.Id, Type__c = QuestionDO.TYPE_TEXT_SHORT , Name = 'q1', Caption__c = 'caption', Position__c = 1);
        insert q1;
        SurveyMapping__c sM   = new SurveyMapping__c(ObjectApiName__c = 'Contact', Survey__c = survey.Id, UseAsInterviewee__c = true);
        insert sM;
        QuestionMapping__c qM = new QuestionMapping__c(Question__c = q1.Id, SurveyMapping__c = sM.Id, FieldApiName__c = 'LastName');
        insert qM;
        SurveyMapping__c sM2  = new SurveyMapping__c(ObjectApiName__c = 'Contact', Survey__c = survey.Id, UseAsInterviewee__c = true);

        //the insert should fail since there is already a UseAsInterviewee SurveyMapping for this survey
        Test.startTest();
            try{
                insert sM2;
                system.assert(false, 'The insert should fail since there is already a UseAsInterviewee SurveyMapping for this survey');
            }
            catch (Exception e) {
                system.assert(e.getMessage().contains(system.Label.BUILDER_ERR_INTERVIEWEE_MAPPING), e.getMessage());
            }

            sM2.UseAsInterviewee__c = false;
            insert sM2;

            sM2.UseAsInterviewee__c = true;
            //the update should fail because there is already a UseAsInterviewee SurveyMapping for this survey
            try{
                update sM2;
                system.assert(false, 'The update should fail since there is already a UseAsInterviewee SurveyMapping for this survey');
            }
            catch (Exception e) {
                system.assert(e.getMessage().contains(system.Label.BUILDER_ERR_INTERVIEWEE_MAPPING), e.getMessage());
            }

            sM2.UseAsInterviewee__c = true;
            sM.UseAsInterviewee__c = false;
            update new SurveyMapping__c[]{sM,sM2};
        Test.stopTest();

        system.assertEquals(false,sM.UseAsInterviewee__c);
        system.assertEquals(true,sM2.UseAsInterviewee__c);
    }*/
    /**
    * Test to validate the mapping of surveys to a mobile survey object
    *//*
    static testMethod void ValidateNotMappedToObjects(){
        Survey__c survey = new Survey__c(Name = 'survey');
        insert survey;
        Question__c sec1 = new Question__c(Survey__c = survey.Id, Type__c = QuestionDO.TYPE_SECTION , Name = 'section', Caption__c = 'caption', Position__c = 1);
        insert sec1;
        Question__c q1 =new Question__c(Survey__c = survey.Id, Parent__c=sec1.Id, Type__c = QuestionDO.TYPE_TEXT_SHORT, Name = 'q1', Caption__c = 'caption', Position__c = 1);
        insert q1;
        SurveyMapping__c sM = new SurveyMapping__c(ObjectApiName__c = Survey__c.getSObjectType().getDescribe().getName(), Survey__c = survey.Id);
        
        Test.startTest();
            // Insert invalid survey mapping
            try{
                insert sM;
                system.assert(false, 'The insert should fail since is trying to map a mobile-survey object');
            }catch (Exception e){
                system.assert(e.getMessage().contains(system.Label.BUILDER_ERR_MOBILESURVEY_MAPPING));
            }

            // Insert valid survey mapping
            sM.ObjectApiName__c='Contact';
            insert sM;
            // Set the invalid object api name
            sM.ObjectApiName__c = Survey__c.getSObjectType().getDescribe().getName();

            // Update invalid survey mapping
            try{
                update sM;
                system.assert(false, 'The update should fail since is trying to map a mobile-survey object');
            }catch (Exception e){
                system.assert(e.getMessage().contains(system.Label.BUILDER_ERR_MOBILESURVEY_MAPPING));
            }
        Test.stopTest();
    }
    */
}