src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <description>The caption of the question</description>
        <label>Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FromVersion__c</fullName>
        <label>First Version</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PreviousVersionQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous version</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>New version</relationshipLabel>
        <relationshipName>NewVersions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ToVersion__c</fullName>
        <label>Last Version</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>section</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>repeat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-short</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text-long</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>number-decimal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>date-datetime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>static-content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>end_of_survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>barcode</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>gps-location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>picture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-select</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>cascading-level</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ScoringGroup__c.object
<CustomObject>
    <fields>
        <fullName>Caption__c</fullName>
        <label>Caption</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyVersion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Version</label>
        <referenceTo>SurveyVersion__c</referenceTo>
        <relationshipLabel>Scoring Groups</relationshipLabel>
        <relationshipName>Scoring_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Scoring Groups</relationshipLabel>
        <relationshipName>Scoring_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Scoring Group</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Scoring Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deprecated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyVersions</relationshipLabel>
        <relationshipName>SurveyVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuestionVersionRangeAssignationTest.cls
/*
*   (c) Copyright 2013 Grameen Foundation USA. All rights reserved
*/
@isTest
private class QuestionVersionRangeAssignationTest {

    static testMethod void QuestionVersionAssignmentTest() {
        // Insert a survey with a version and check version assignment
        Survey__c survey = new Survey__c(Name = 'Test Question Version');
        insert survey;

        Question__c qSection = new Question__c(Survey__c=survey.Id,Caption__c= 'SECTION',Type__c = QuestionDO.TYPE_SECTION, Position__c = 1);
        insert qSection;

        Question__c q1 = new Question__c(Parent__c= qSection.Id,survey__c=survey.Id,Caption__c= 'Username',Type__c = QuestionDO.TYPE_TEXT_SHORT, Position__c = 1);
        insert q1;
        q1 = [select FromVersion__c,ToVersion__c from Question__c where Id = :q1.Id];

        // Insertion of a question for version1
        system.assertEquals(1, q1.FromVersion__c);
        system.assertEquals(null, q1.ToVersion__c);

        // Publish the version,and leave it in draft to create a new Version
        SurveyVersion__c version = [select Version__c,Status__c from SurveyVersion__c where Survey__c= :survey.Id];
        version.Status__c = SurveyDO.STATUS_PUBLISHED;
        
        Test.startTest();
            update version;

            SurveyTriggerLogic.setOverrideDeleteChecks(true);
            survey.Status__c = SurveyDO.STATUS_DRAFT;
            update survey;
            SurveyTriggerLogic.setOverrideDeleteChecks(false);

            // Insertion of a question for Version 2
            Question__c q2 = new Question__c(Parent__c= qSection.Id,survey__c=survey.Id, Caption__c= 'Username',Type__c = QuestionDO.TYPE_TEXT_SHORT, Position__c = 2);
            insert q2;

            // Assert if the From and To were correctly assigned
            q2 = [select ToVersion__c,FromVersion__c from Question__c where Id = :q2.Id];
            system.assertEquals(2, q2.FromVersion__c);
            system.assertEquals(null, q2.ToVersion__c);

            // Insertion of a modified question in a new Version 3
            // Create new Version
            version = [select Version__c,Status__c from SurveyVersion__c where Survey__c= :survey.Id order by Version__c desc][0];
            version.Status__c = SurveyDO.STATUS_PUBLISHED;
            update version;
            SurveyTriggerLogic.setOverrideDeleteChecks(true);
            survey.Status__c = SurveyDO.STATUS_DRAFT;
            update survey;
            SurveyTriggerLogic.setOverrideDeleteChecks(false);
            Question__c q1new = new Question__c(PreviousVersionQuestion__c=q1.Id,Parent__c= qSection.Id,survey__c=survey.Id,Caption__c= 'Username',Type__c = QuestionDO.TYPE_TEXT_SHORT, Position__c = 3);
            insert q1new;
        Test.stopTest();
        q1 = [select FromVersion__c,ToVersion__c from Question__c where Id = :q1.Id];
        q1new = [select FromVersion__c,ToVersion__c from Question__c where Id = :q1new.Id];

        // Assert if the From and To were correctly assigned
        system.assertEquals(3, q1new.FromVersion__c);
        system.assertEquals(null, q1new.ToVersion__c);
        system.assertEquals(1, q1.FromVersion__c);
        system.assertEquals(2, q1.ToVersion__c);
    }


    static testMethod void VerifySurveyStatusInsertQuestion() {
        // create a new ScoringGroup__c
        Survey__c survey = new Survey__c(Name='survey');
        insert survey;

        //insert a Question
        Question__c qSection = new Question__c(Survey__c=survey.Id,Caption__c= 'SECTION',Type__c = QuestionDO.TYPE_SECTION, Position__c = 1);
        insert qSection;
        Question__c question = new Question__c(Parent__c = qSection.Id, Caption__c ='TestQuestion',Survey__c=survey.Id, Position__c = 1);
        insert question;

        //ASSERTIONS
        List<SurveyVersion__c> versions = [select Version__c,Status__c,Name from SurveyVersion__c where Survey__r.Id = :survey.Id];
        survey = [select Status__c from Survey__c where Id=:survey.Id];
        system.assertEquals(1,versions.size());
        system.assertEquals(SurveyDO.STATUS_DRAFT,survey.Status__c);
        versions = [select Version__c,Status__c,Name from SurveyVersion__c where Survey__r.Id = :survey.Id];
        versions[0].Status__c = SurveyDO.STATUS_PUBLISHED;
        Test.startTest();
            update versions;

            // try to insert a new question,it should fail since Survey is Published
            try{
                insert new Question__c(Caption__c ='TestQuestion2',Survey__c=survey.Id, Position__c = 2);
                system.assert(false);
            }catch(Exception e){
                system.assert(true);
            }

            // try to update a new question,it should fail since Survey is Published
            try{
                update question;
                system.assert(false);
            }catch(Exception e){
                system.assert(true);
            }
        Test.stopTest();
    }

    static testMethod void testUpdateQuestionVersionChain(){
        Survey__c survey = new Survey__c(Name = 'survey', Status__c = SurveyDO.STATUS_DRAFT);
        insert survey;
        Question__c qSection = new Question__c(Survey__c = survey.Id, Caption__c = 'SECTION', Name = 'section', Type__c = QuestionDO.TYPE_SECTION, Position__c = 1);
        insert qSection;
        Question__c question = new Question__c(Survey__c = survey.Id, Parent__c = qSection.Id, Name='a', Caption__c='a', Position__c=1, Type__c = QuestionDO.TYPE_TEXT_SHORT);
        insert question;
        question = [SELECT Id, FromVersion__c, ToVersion__c FROM Question__c WHERE Id = :question.Id];
        system.assertEquals(1, question.FromVersion__c);
        system.assertEquals(null, question.ToVersion__c);

        // Publish the survey. Assert it's status is updated.
        SurveyVersion__c version = [SELECT Id, Status__c FROM SurveyVersion__c WHERE Survey__c = :survey.Id];
        system.assertEquals(SurveyDO.STATUS_DRAFT, version.Status__c);
        version.Status__c = SurveyDO.STATUS_PUBLISHED;
        
        Test.startTest();
            update version;
            survey = [SELECT Id, Status__c, Version__c FROM Survey__c WHERE Id = :survey.Id];
            system.assertEquals(SurveyDO.STATUS_PUBLISHED, survey.Status__c);

            // Move the survey to Draft again. Assert a new version is created, and survey version is updated.
            SurveyTriggerLogic.setOverrideDeleteChecks(true);
            survey.Status__c = SurveyDO.STATUS_DRAFT;
            update survey;
            SurveyTriggerLogic.setOverrideDeleteChecks(false);

            survey = [SELECT Id, Status__c, Version__c FROM Survey__c WHERE Id = :survey.Id];
            system.assertEquals(2, survey.Version__c);
            system.assertEquals(2, [SELECT Id FROM SurveyVersion__c WHERE Survey__c = :survey.Id].size());

            // Insert a new version of the question, assert the version range is updated
            Question__c question2 = new Question__c(Survey__c = survey.Id, Parent__c = qSection.Id, Name='b', Caption__c='b', Position__c=1, Type__c=QuestionDO.TYPE_TEXT_SHORT, PreviousVersionQuestion__c = question.Id);
            insert question2;

            question = [SELECT Id, FromVersion__c, ToVersion__c FROM Question__c WHERE Id = :question.Id];
            system.assertEquals(1, question.FromVersion__c);
            system.assertEquals(1, question.ToVersion__c);

            question2 = [SELECT Id, FromVersion__c, ToVersion__c FROM Question__c WHERE Id = :question2.Id];
            system.assertEquals(2, question2.FromVersion__c);
            system.assertEquals(null, question2.ToVersion__c);
        Test.stopTest();
    }
}