src/objects/ScoreValue__c.object
<CustomObject>
    <fields>
        <fullName>ScoringGroup__c</fullName>
        <label>Scoring Group</label>
        <referenceTo>ScoringGroup__c</referenceTo>
        <relationshipLabel>Score Values</relationshipLabel>
        <relationshipName>Score_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Score Value</label>
    <nameField>
        <displayFormat>SV-{0000}</displayFormat>
        <label>Score Value Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Score Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ScoringGroup__c.object
<CustomObject>
    <fields>
        <fullName>IsPPI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Scoring Group is for a PPI Template</description>
        <label>Is PPI</label>
        <type>Checkbox</type>
    </fields>
    <label>Scoring Group</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Scoring Group Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScoreValueSelectorTest.cls
/**
 * Test class for the ScoreValueSelector class
 *
 * (c) Copyright 2013 Grameen Foundation USA. All rights reserved
 *
 * @author Kaushik Ray  
 * @author Owen Davies - odavies@grameenfoundation.org
 */
@isTest
public class ScoreValueSelectorTest {

    /**
     * Test method to verify fetching all score value records for specified question Ids
     */
    static testmethod void testGetForQuestionIds() {
        TestSurveyData testSurvey = TestSurveyData.addScoringGroupToStandardSurvey(
            TestSurveyData.createStandardTestSurvey(null, false, false), true
        );

        Test.startTest();
        List<ScoreValue__c> scoreValueList =
            new ScoreValueSelector().getForQuestionIds(
                new Set<Id> {testSurvey.getQuestion(0, 2).Id}
            );
        Test.stopTest();

        System.assertEquals(5, scoreValueList.size(), 'Score Value records should get selected');
    }

    /**
     * Test method to verify fetching all score value records along with relationship fields
     */
    static testmethod void testGetWithParentFields() {
        TestSurveyData testSurvey = TestSurveyData.addScoringGroupToStandardSurvey(
            TestSurveyData.createStandardTestSurvey(null, false, false), true
        );
        Test.startTest();
        List<ScoreValue__c> actualScoreValueList =
            new ScoreValueSelector().getWithParentFields(
                new Set<Id> {
                    testSurvey.getScoreValue(0, 0).Id,
                    testSurvey.getScoreValue(0, 1).Id
                }
            );
        Test.stopTest();
        System.assertEquals(
            2,
            actualScoreValueList.size(),
            'Score Value records should get selected'
        );

        System.assert(
            actualScoreValueList[0].ScoringGroup__r.isPPI__c,
            'Field isPPI_c should be true. Relationship field not properly fetched'
        );
    }

    /**
     * Test get all for a survey
     */
    static testMethod void testGetAllForSurvey() {

        TestSurveyData testSurvey =
            TestSurveyData.addScoringGroupToStandardSurvey(
                TestSurveyData.createStandardTestSurvey(null, true), false
            );
        Test.startTest();
        ScoreValueSelector scoreValueSelector = new ScoreValueSelector();
        List<ScoreValue__c> scoreValues =
            scoreValueSelector.getAllForSurvey(testSurvey.testSurvey.Id);
        Test.stopTest();
        System.assertEquals(5, scoreValues.size());
    }
}