src/objects/SObjectContactAssociation__c.object
<CustomObject>
    <description>Links a contact to a list of records of a given type. Allows for multiple records of the same sobject type to be assigned to the same user with just one record</description>
    <fields>
        <fullName>AssociatedIds__c</fullName>
        <description>A comma separated list of the SObject.Ids that are linked to the Contact</description>
        <label>Associated Ids</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The contact that is being associated with the given records</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SObjects Contact Associations</relationshipLabel>
        <relationshipName>SObjects_Contact_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <defaultValue>1</defaultValue>
        <description>This is the instance number for the record. Defaults to 1 as most Mobile Users will only ever need 1</description>
        <label>Instance</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumberOfRecords__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The number of associated records that are contained in this record</description>
        <label>Number Of Records</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SObjectApiName__c</fullName>
        <description>The API Name of the object type that this record is linked to. Must be an existing API Name. If the object this refers to is deleted then the record will also be deleted lazily when it is accessed for the first time after the delete</description>
        <label>SObject API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SObjects Contact Association</label>
    <nameField>
        <displayFormat>SOCA-{00000000}</displayFormat>
        <label>SObjects Contact Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SObjects Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SObjectContactAssociationSelector.cls
/**
 * Selector class for the SObjectContactAssociation object
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author Owen Davies - odavies@grameenfoundation.org
 */
public with sharing class SObjectContactAssociationSelector extends SObjectSelector {

    public Schema.SObjectType getSObjectType() {
        return SObjectContactAssociation__c.sObjectType;
    }

    public List<Schema.SObjectField> getDefaultSelectFields() {
        return new List<Schema.SObjectField>{
            SObjectContactAssociation__c.Id,
            SObjectContactAssociation__c.Name,
            SObjectContactAssociation__c.AssociatedIds__c,
            SObjectContactAssociation__c.Contact__c,
            SObjectContactAssociation__c.Instance__c,
            SObjectContactAssociation__c.NumberOfRecords__c,
            SObjectContactAssociation__c.SObjectApiName__c
        };
    }

    public String pathToJobFiltering() {
        return null;
    }

    /**
     * Return the default order by clause
     */
    public override String getDefaultOrderByClause() {
        return SObjectContactAssociation__c.SObjectApiName__c.getDescribe().getName();
    }

    /**
     * Get all the SObjectContactAssociations for a given contact
     */
    public List<SObjectContactAssociation__c> getAllForContact(Id contactId) {
        createContactWhereClause(contactId);
        return
            (List<SObjectContactAssociation__c>)
                runSoqlQueryDbFullAccess(SObjectSelector.AND_OPERATOR, null);
    }

    /**
     * Get all the SObjectContactAssociations for a given contact and sObject
     */
    public List<SObjectContactAssociation__c> getAllForContactAndObject(
            Id contactId,
            List<String> sObjectApiNames
    ) {
        this.createContactWhereClause(contactId);
        this.createSobjectApiNameWhereClause(sObjectApiNames);
        return
            (List<SObjectContactAssociation__c>) runSoqlQuery(SObjectSelector.AND_OPERATOR, null);
    }

    private void createContactWhereClause(Id contactId) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardWhereClause(
                SObjectContactAssociation__c.Contact__c.getDescribe().getName(),
                SObjectSelector.EQUALS_OPERATOR,
                contactId
            )
        );
    }

    private void createSobjectApiNameWhereClause(List<String> sObjectApiNames) {
        this.addToMainWhereClause(
            this.getMainQueryBuilder().generateStandardInWhereClause(
                SObjectContactAssociation__c.SObjectApiName__c,
                SObjectSelector.IN_OPERATOR,
                sObjectApiNames
            )
        );
    }
}