src/objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>PPIScore__c</fullName>
        <label>PPI Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubmissionSelector.cls
/**
 * Selector class for the Submission object
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author Kaushik Ray
 */
public with sharing class SubmissionSelector extends SObjectSelector {

    public Schema.SObjectType getSObjectType() {
        return Submission__c.sObjectType;
    }

    public List<Schema.SObjectField> getDefaultSelectFields() {
        return new List<Schema.SObjectField> {
            Submission__c.Id,
            Submission__c.Name,
            Submission__c.PPIScore__c
        };
    }

    public String pathToJobFiltering() {
        return null;
    }

}