src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SurveyVersion__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deprecated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>SurveyVersions</relationshipLabel>
        <relationshipName>SurveyVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Version</label>
    <nameField>
        <displayFormat>SV-{0000000000}</displayFormat>
        <label>Survey Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SurveyVersionDomainTest.cls
/**
 * Test class for the SurveyVersionDomain
 *
 * (c) Copyright 2014 Grameen Foundation USA. All rights reserved
 *
 * @author - Aditi Satpute
 */
@isTest
public with sharing class SurveyVersionDomainTest {

    /**
     * Create SurveyVersion record
     */
    public static SurveyVersion__c createRecord(Survey__c survey, String status) {
        return new SurveyVersion__c(
            Survey__c = survey.id,
            Status__c = status
        );
    }

    /**
     * Method to test fetching Map of SurveyVersion records
     */
    static testmethod void testFetchSurveyVersionIdToInstanceMap() {
        Survey__c survey1 = SurveyDOTest.createInsertedSurvey('SurveyTest1');
        Survey__c survey2 = SurveyDOTest.createInsertedSurvey('SurveyTest');

        List<SurveyVersion__c> surveyVersionList =
            new SurveyVersionSelector().getAllWithSurveyIds(
                new Set<String> {survey1.Id, survey2.Id}
            );

        System.assertEquals(2, surveyVersionList.size());

        Test.startTest();
        Map<String, SurveyVersion__c> mapSurveyVersionIdToInstance =
            SurveyVersionDomain.getSurveyVersionIdToInstanceMap(
                new Set<Id> {
                    surveyVersionList[0].Id,
                    surveyVersionList[1].Id
                }
            );
        Test.stopTest();

        System.assertEquals(2, mapSurveyVersionIdToInstance.size());
    }
}